### ISSUE TITLE
Anybody knows why losses look like this?

### ISSUE THREAD

**Issue by zhangluustb** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#100]
stage1_pafs_loss:     132.33322006225586
stage1_heatmaps_loss: 49.49405616760254
stage2_pafs_loss:     128.0429653930664
stage2_heatmaps_loss: 47.89024211883545
100%|██████████| 516/516 [12:00<00:00,  1.40s/it]
  1%|          | 4/516 [00:13<27:49,  3.26s/it]Iter: 3100
stage1_pafs_loss:     5.463875732421875
stage1_heatmaps_loss: 2.0516973876953126
stage2_pafs_loss:     5.2807315063476565
stage2_heatmaps_loss: **1.9725639724731445**
 20%|██        | 104/516 [02:42<10:42,  1.56s/it]Iter: 3200
stage1_pafs_loss:     131.51344520568847
stage1_heatmaps_loss: 49.36172973632812
stage2_pafs_loss:     127.09879386901855
stage2_heatmaps_loss: 47.67966331481934

**Comment by Daniil-Osokin** [comment]
Hi! This may happen if number of batches to process train dataset is not divisible to number of iterations to log loss after, [these](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L116-L117) lines cause it. So, it is ok.

**Comment by zhangluustb** [comment]
> Hi! This may happen if number of batches to process train dataset is not divisible to number of iterations to log loss after, [these](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L116-L117) lines cause it. So, it is ok.

Thank you for your reply!^_^
