### ISSUE TITLE
 misidentification 

### ISSUE THREAD

**Issue by hsl8856** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#102]
There are many misidentifications using checkpoint_iter_370000.pth, can we reduce the misidentification by adjusting the threshold?

**Comment by Daniil-Osokin** [comment]
Hi! It would be great to know what do you mean under misidentification. Can you please attach some images to illustrate this? In general each pose has own [confidence](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L24), so you can use poses with confidence over some threshold (e.g. > 10), or skip pose if number of detected keypoints is too low.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
