### ISSUE TITLE
The issue of model output

### ISSUE THREAD

**Issue by dongdongqiang2018** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#104]
Hi, thank you for your excellent work and shared a pre-trained high-quality model.
I am trying to convert a pre-trained model into a TRT model and perform inference.
But the output of the two models is not the same.
```
pth model's output -->
[[1,19,32,32]
[1,19,32,32]
[1,19,32,32]
[1,19,32,32]]
```
```
trt   model's output -->
[(1108992,)
(2217984,)
(1108992,)
(2217984,)]
```
Has anyone done the same before, please give me some help

**Comment by Daniil-Osokin** [comment]
Hi! In #42 there is a link with TensorRT instructions: https://github.com/mathblue/Custom-Pose-Estimation-Yaw-Roll-Pitch-detection-tensorrt-compilation#compile-model-with-tensorrt--much-more-faster.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
