### ISSUE TITLE
Could   ~40 AP be used in a real-world scenario？

### ISSUE THREAD

**Issue by sunbin1357** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#105]
Could   ~40 AP be used in a real-world scenario？Have you made any recent progress in the field of pose estimation？

**Comment by Daniil-Osokin** [comment]
Hey, @sunbin1357! Yes, it can be used for real-world scenario. Off course, it totally depends on the use case, but I know, it was successfully used for action recognition and for pose tracking in sport. It worth to try. The focus of this work is on real-time inference for pose estimation. The quality is ok, but problems may arrive for small sized poses. For this case we developed fast and accurate (~70% AP) top-down method in [neighbor repository](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch), but it requires to run person detector first. Moreover, I also have the plans to improve this work in terms of inference speed with similar quality, however it needs some free time and effort :).

**Comment by sunbin1357** [comment]
your paper report the AP of openpose with 5 stages is 48.6, however the
result in other papers is 60+.

Daniil-Osokin <notifications@github.com> 于2020年8月21日周五 上午4:42写道：

**Comment by sunbin1357** [comment]
Do you have a demo that applies to action recognition or other real-world
scenario

>

**Comment by Daniil-Osokin** [comment]
This repository contains just the pose estimation.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
