### ISSUE TITLE
how to know or calculate the sigmas  from similarity

### ISSUE THREAD

**Issue by steel540** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#106]
Hi Daniil , thank you for your excellent work and shared a good code. But, I have one problem need u help, i don't understand about ur sigmas values from modules.pose.py, how do u calculate these values, could u please explain it more detail, thank you!

(sigmas = np.array([.26, .79, .79, .72, .62, .79, .72, .62, 1.07, .87, .89, 1.07, .87, .89, .25, .25, .35, .35],
                      dtype=np.float32) / 10.0)

**Comment by steel540** [comment]
Hi Daniil , Thank you for your quick response, i am working on kinect project that includes 34 parts not 18 parts , so it's difficult to define sigmas, let me thinking how to do, thank you so much^^

**Comment by Daniil-Osokin** [comment]
I believe you can extrapolate the same values for keypoints on the same body parts from COCO, i.e. if it is a keypoint on a leg use value from the nearest keypoint from leg in COCO.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
