### ISSUE TITLE
openvino inference on python

### ISSUE THREAD

**Issue by vivek87799** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#107]
Dear @Daniil-Osokin,

I would like to thank you for your wonderful work.

I have integrated a small script for the openvino inference using python and I am getting an inference time of 0.042 (26 FPS) on CPU. 

Please let me know if you feel that it will be of use. I can send a pull request for the same.

Thank you

**Comment by Daniil-Osokin** [comment]
Hi! Great to know it. For faster inference on CPU it is better to use [C++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#c-demo-), not the Python one. Post-processing code in Python is terribly slow, so fast network inference does not help.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by jsynnott** [comment]
Hi @vivek87799 - I am very interested in the work you have mentioned. Does your Python script return keypoints for multiple poses using OpenVino? If so, can you please let me know where I could access your script?

Thanks,
Jonathan
