### ISSUE TITLE
What is the reason why C++ is faster

### ISSUE THREAD

**Issue by sunbin1357** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#108]
I find that your model post-processing is implemented in python and C++, respectively. The implementation details are the same. What is the reason why C++ is faster? Is there any other reason for this besides the fact that c++ is a compiled language

**Comment by vivek87799** [comment]
@sunbin1357 
The c++ implementation uses the OpenVino toolkit for inference, 
whereas the python implementation runs inference with Pytorch.

**Comment by sunbin1357** [comment]
I asked last time about the model post-processing part, not the model inference part.

**Comment by Daniil-Osokin** [comment]
Hi! It is just C++ vs Python comparison. Possibly Python implementation may be made faster. However profile shows, that [this scalar multiplication](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/keypoints.py#L128) takes a lot of time, do not know how to speedup it.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
