### ISSUE TITLE
Question about background heatmap

### ISSUE THREAD

**Issue by javierlorenzod** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#112]
Hi!

I am trying to solve a heatmap regression problem and your code is quite nice and well documented, thank you. I have a question related to the background heatmap. When you create it in [_generate_keypoint_maps ](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/2df5db059db1a043169b65b633d7bb3b8efd13a6/datasets/coco.py#L72) method, you put a value of 1 in positions without keypoints and 1 - the maximum value of all the keypoints heatmaps on each point. I have tried training without a background mask, but usually, with small heatmaps, the model converges in a zero value heatmap because usually, this is the, but I thought about it and I want to know how does it help in training. Thank you.

**Comment by Daniil-Osokin** [comment]
Hi! I have tried to train without background channel, it works similar in this case (as with background channel). So it looks for me as legacy detail, just ot correspond with original OpenPose output channels number.

**Comment by javierlorenzod** [comment]
Hello again! Then I will try to weight the error of the heatmap depending on its value.  Thank you for your help.
