### ISSUE TITLE
Only Ubuntu?

### ISSUE THREAD

**Issue by sajjadh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#113]
Does this code work only for ubuntu?, 

I've been trying in windows, I got some errors while installing the requirements.

![image](https://user-images.githubusercontent.com/31664351/96513767-43f25180-1280-11eb-99ab-ffe66945e736.png)

**Comment by imseunghyun** [comment]
In windows, try to install "pip install pycocotools-windows"

**Comment by sajjadh** [comment]
I am getting the same error. 
![image](https://user-images.githubusercontent.com/31664351/96559361-93fe0200-12da-11eb-9d28-755cafc35d87.png)

Does this mean I should upgrade all these versions?. ow about the torch version, it says 0.4.1 is recommended in the doc

**Comment by sajjadh** [comment]
[check](https://github.com/cocodataset/cocoapi/issues/393) fixed the running setup.py for pycocotool issue

**Comment by imseunghyun** [comment]
I Successfully installed pycocotools windows version with "pip install pycocotools-windows".
![image](https://user-images.githubusercontent.com/43159220/96561259-485b5080-12fa-11eb-962c-439cea6e6146.png)
Check your pip list or try to install new virtualenvs.
i refer to this page(https://pypi.org/project/pycocotools-windows/).
i hope this helps.

**Comment by sajjadh** [comment]
it was sorted, but i am having some other issue with Cuda library. Closing this thread.
