### ISSUE TITLE
CUDA required?

### ISSUE THREAD

**Issue by sajjadh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#114]
When i run this command "python demo.py --checkpoint-path models/checkpoint_iter_370000.pth --video 0" i am getting this 

![image](https://user-images.githubusercontent.com/31664351/96562842-daedf680-12de-11eb-946e-59a9aaa0f8e0.png)

**Comment by Daniil-Osokin** [comment]
Hi! To run on CPU, you can pass `--cpu` option to the `demo.py`.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
