### ISSUE TITLE
Postprocess

### ISSUE THREAD

**Issue by wwdok** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#115]
Hi, bro, i want to change two thing of this repo, one is to reduce the flicker of some keyponit, another is increase the ‘threshold’ of detecting new person id, could you tell me where are the relative codes ? thanks ！

**Comment by Daniil-Osokin** [comment]
Hi! You can use `confidence` field of `Pose` object to filter low-confident detectitons, filter them [before](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L116) tracking. You can tune [default thresholds](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/one_euro_filter.py#L24) for smoothing filter to better stabilize some keypoints.

**Comment by wwdok** [comment]
> Hi! You can use `confidence` field of `Pose` object to filter low-confident detectitons, filter them [before](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L116) tracking. You can tune [default thresholds](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/one_euro_filter.py#L24) for smoothing filter to better stabilize some keypoints.

Thank you for your tips ! I find we can modify the `mincutoff` to control keypoints jitter and modify threshold parameters of `get_similarity()` and `track_poses()` to control the spped of generating new id, but i still have two questions, one is how we determine whether the keypoint coordinate is -1 , do we have the confidence score of 18 keypoints and set threshold to it ? another is the mathematical meaning of `similarity = np.exp(-distance / (2 * (area + np.spacing(1)) * Pose.vars[kpt_id]))`, could you please help me again ?

**Comment by Daniil-Osokin** [comment]
Keypoints are detected as local maximums in heatmaps, so the keypoint confidence is the value at local maximum. Each pose has 18 keypoints, if some of them was not found or their [confidence was less than a threshold](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/keypoints.py#L17), then they marked as `-1`. The mathematical meaning is the similarity measure between two positions of keypoint. This measure takes into account object area and possible allowed variance for this keypoint type. Just look at the values in debugger and you will get it right.

**Comment by wwdok** [comment]
@Daniil-Osokin Good explanation ！It is helpful, thank you very much !

**Comment by Daniil-Osokin** [comment]
Great, that it helped!
