### ISSUE TITLE
why upsample for heatmaps？

### ISSUE THREAD

**Issue by ToBigboss** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#116]
![image](https://user-images.githubusercontent.com/40013733/97968957-5204ae00-1dfa-11eb-8889-471cd976fd8d.png)

**Comment by dongdongqiang2018** [comment]
Zoom in image

**Comment by Daniil-Osokin** [comment]
Hi! We can have better precision if will extract keypoints coordinates at bigger heatmaps, than network output size.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
