### ISSUE TITLE
Unable to detect pedestrians

### ISSUE THREAD

**Issue by aizuon** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#117]
Hello,

I'm working on a deepsort implementation of this repo, using pose bbox info and features from backbone, but the model is unable to detect pedestrians consistently. Weird thing is that, when I use another detector, like YOLOv3, and give the output bbox of that to this model, crop the detected areas of the image, it works beautifully. Any ideas? Is the kernel size of conv layers too big perhaps?

**Comment by Daniil-Osokin** [comment]
Hi! I believe the pedestrian height to image height ratio is too small for the default parameters. You can increase network input size with `--height-size` [option](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L145). Try to set it to `512` or `1024`, and see if it works.

**Comment by aizuon** [comment]
> 
> 
> Hi! I believe the pedestrian height to image height ratio is too small for the default parameters. You can increase network input size with `--height-size` [option](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L145). Try to set it to `512` or `1024`, and see if it works.

Thanks for the reply. Does the network need to be retrained for this?

**Comment by aizuon** [comment]
Thanks, size 512 is able to detect even the smallest pedestrians.

**Comment by Daniil-Osokin** [comment]
Great, that it helped!
