### ISSUE TITLE
about num_channels

### ISSUE THREAD

**Issue by augenstern-lwx** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#118]
Hi, thanks for your great work！I have a question to consult you, when we use mobilenetV1 as the backbone, num_channels = 128. If I adjust its depth to 1024（Currently 512）, Whether the number of channels still need to be set to 128? When I use mobilenetv2 or mobilenetv3？Looking forward to your reply.

**Comment by Daniil-Osokin** [comment]
Hi! It is a hyperparameter, so you can set it to any reasonable value.

**Comment by augenstern-lwx** [comment]
thank you！
