### ISSUE TITLE
keypoints 

### ISSUE THREAD

**Issue by EvgeniaKomleva** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#119]
Thanks for your project, it really works fast!
Please tell me how can I extract keypoints as in openpose? There should be 24 coordinates of the limb

**Comment by Daniil-Osokin** [comment]
Hi! The OpenPose supports different models with different number of joints in skeleton. In this repo we provide the model for 18 joints, which corresponds to [COCO format](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-coco).

**Comment by EvgeniaKomleva** [comment]
Are they contained in pose_keypoints (from demo.py)?

**Comment by Daniil-Osokin** [comment]
Yes, keypoints can be accessed as `pose.keypoints` from [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L119). They order is described in the [Pose](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L10) class.

**Comment by EvgeniaKomleva** [comment]
Thank you so much!

**Comment by Daniil-Osokin** [comment]
Great, that it helped!
