### ISSUE TITLE
Run demo for custom dataset

### ISSUE THREAD

**Issue by ThongNguyen551** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#120]
I am running the demo with my custom dataset but it always get the pose entries equaling to 0. Also, for the keypoints.py in modules, just change the kpt list and the paf as the image below. my data is pigs with the keypoint defined as 0 for neck, 1 for ear left, 2 for ear right, 3 for neck, 4 for back, and 5 for tail. Can you help me on running the demo with custom dataset? Thank you. 

![image](https://user-images.githubusercontent.com/46335839/101243655-f7fd4e00-3701-11eb-9b6a-b3d2dc3e90a0.png)

**Comment by ThongNguyen551** [comment]
sorry 0 for Nose

**Comment by Daniil-Osokin** [comment]
Hi! The indices look reasonable for me, did you trained the network on your dataset?

**Comment by ThongNguyen551** [comment]
Hi, I did train already. However, when doing the demo, it could not work.

**Comment by Daniil-Osokin** [comment]
In this case I suggest to check [ground truth](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L84-L86) images and heatmaps and [predicted](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L90) heatmaps for the training data. You can visualize them with OpenCV. Trained model should produce similar predictions to the ground truth data. Are they similar? BTW, there is similar question #42. It has a link to the guide how this code was adapted for custom dataset, it also may help.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
