### ISSUE TITLE
map persons keypoints coming from ground truth and prediction 

### ISSUE THREAD

**Issue by sana15** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#123]
Suppose in an image there 23 persons, from val 2017 annotations got annotion json file for 13 persons bodypose keypoints and from Prediction got 23 persons bodypose keypoints, how did you match same persons keypoints from Ground truth and prediction? 

I am not able to match person1 from Ground truth and person1 prediction.
Is there any way to do this?
Any help is appreciated

**Comment by Daniil-Osokin** [comment]
In general you have two sets of bounding boxes around poses. They can be matched by the intersection over union ratio: if IoU between ground truth and predicted box is higher than a threshold (e.g. 0.5), then they are matched (just do not forget to sort all predicted boxes by the confidence decrease before). `pycocotools` [does](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/2df5db059db1a043169b65b633d7bb3b8efd13a6/val.py#L25) it, you can check its code for more details.

**Comment by sana15** [comment]
As you suggested in pycocotools [does](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/2df5db059db1a043169b65b633d7bb3b8efd13a6/val.py#L25)  val.py does not give bbox, it just gives scores and keypoints. how can i get two sets of bounding boxes. in demo.py it is gives 1 set of bounding box. Could you please elaborate little on how to map persons in an image? Thanks in advance
![two_persons](https://user-images.githubusercontent.com/13717573/102799356-6ca9db00-43d8-11eb-8e62-956b32f1ac83.jpg)

**Comment by Daniil-Osokin** [comment]
In the demo you can find a tight bounding box around each found person. Another one bounding box you should get from the dataset annotations.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
