### ISSUE TITLE
can not download the mobilenet

### ISSUE THREAD

**Issue by georgeftakla** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#125]
Hi,
I can not Download pre-trained MobileNet mobilenet_sgd_68.848.pth.tar from: https://github.com/marvis/pytorch-mobilenet, and the download from GoogleDrive is not a valid tar
thanks for your advise

**Comment by Daniil-Osokin** [comment]
Hi, MobileNet weights checkpoint is just not a tar file, use it as is. For an example of usage please see paragraph 3 from [training](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#training). Tar postfix was in the original model, so it is left as is. Similar questions: #2, #5.

**Comment by georgeftakla** [comment]
thank you Daniil
