### ISSUE TITLE
it seems CUDA is needed for DataParallel(net).cuda()

### ISSUE THREAD

**Issue by georgeftakla** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#126]
Hi,
The readme states use of CPU and the requirements does not list need of CUDA. However, the train.py errors on train.load on line 62 for cuda which can be solved by setting parameter map_location='cpu'.
Then, I found DataParallel and more calls that need cuda .. 
I am not sure how to solve for that without NVIDIA board and Cuda . I want to use CPU only

thanks for your help

**Comment by Daniil-Osokin** [comment]
Yes, training is usually done on a gpu. You can remove all `.cuda()` calls from `train.py` and `val.py` to run training on cpu.

**Comment by georgeftakla** [comment]
I have Intel HD GPU. can it be used?

**Comment by Daniil-Osokin** [comment]
Not sure, you can check this issue: https://discuss.pytorch.org/t/use-mkldnn-in-pytorch/54943/23.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by georgeftakla** [comment]
Yes. Thank you for the link to pytor h and use of mkldnn that explains many points ... Happy Ne year 2021
