### ISSUE TITLE
How to train a model with my data based on pre-training model

### ISSUE THREAD

**Issue by asd974512** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#129]
Hello, your code is very helpful to my problem. But the detection of the model still has problems with my image data. So I want to train my image data based on the pre-trained model. My data only includes images, not videos. How can I do this? Thank you

**Comment by Daniil-Osokin** [comment]
Hi! Do not know what your data is, may be just passing `--height-size 512` (or 1024) to `demo.py` will make results better. For training on custom data please refer to the [guide](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
