### ISSUE TITLE
theory of the extract keypoints process

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#13]
@Daniil-Osokin 
Hi,thank you for your job!
Could you explain the math theory of extract keypoints process?I want to understand your method deeper,thx.

**Comment by Daniil-Osokin** [comment]
Keypoints are extracted at local maximas of heatmaps, pixel just compared with it's neighbors and, if it has higher value than others, it is the keypoint. You can check the thread: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/8 for some details.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
