### ISSUE TITLE
1 FPS in C++ demo

### ISSUE THREAD

**Issue by nathanRamaNoodles** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#130]
Hi, I am trying to run the C++ demo, but I am getting 1-2 FPS on an intel i3.
This seems to be similar to issue #15
But where do I modify the [openvino's example](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/human_pose_estimation_demo/src/human_pose_estimator.cpp) for using lower resolutions?

**Comment by Daniil-Osokin** [comment]
Hi! This looks strange, even on Movidius NCS2 it runs faster. I believe the easiest way is to convert model to OpenVINO format once again and set [input](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/convert_to_onnx.py#L10) shape to `(1, 3, 192, 344)`.

**Comment by nathanRamaNoodles** [comment]
Thank you, I'm getting 15 FPS now.  I guess this is good enough for now.

**Comment by nathanRamaNoodles** [comment]
I'm re-opening this because I seem to be running into another weird issue.  So my Linux [i3-M370](https://cpu.userbenchmark.com/SpeedTest/259/IntelR-CoreTM-i3-CPU-------M-370----240GHz) is running 15 FPS, but my Windows [i5-3317U](https://cpu.userbenchmark.com/Intel-Core-i5-3317U/Rating/2744) is getting 4 FPS using the same input shape of `(1, 3, 192, 344)`.  What could be bottlenecking it?

**Comment by nathanRamaNoodles** [comment]
Nevermind, apparently I had another python task capturing screenshots in the background.
