### ISSUE TITLE
torch2trt on jetson nano

### ISSUE THREAD

**Issue by zhangchenwei115** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#131]
Hi, I want to speed up this model so I tried to use torch2trt to convert this model into Tensorrt and run it on jetson nano.
so basically I used torch2trt(net, data, fp16_mode=True) to convert the model. And in demo.py, I used
model_trt.load_state_dict(torch.load('trt.pth')) to load the model. i set the input with (1,3,192,192)
It works but did not get higher FPS. I think because of fp16. Since I tried both True and also fp16_mode = False. The result of both models is the same. Do you know what should I fix it?
best regards
chenwei

**Comment by Daniil-Osokin** [comment]
Hi! We have [similar issue](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/issues/41) in the neighborhood repository. I suggest to profile which part of pipeline takes the most of time. This probably may be due to Python-based post-processing. If so, C++ version from that repository can be reused.

**Comment by zhangchenwei115** [comment]
> Hi! We have [similar issue](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/issues/41) in the neighborhood repository. I suggest to profile which part of pipeline takes the most of time. This probably may be due to Python-based post-processing. If so, C++ version from that repository can be reused.

thanks for your advice, I think its because of pose processing.  will try

**Comment by tucachmo2202** [comment]
> It works but did not get higher FPS. I think because of fp16. Since I tried both True and also fp16_mode = False. The result of both models is the same. Do you know what should I fix it?

If your device doesn't support float 16 inference type, fp16 mode on or off is same
