### ISSUE TITLE
Network resolution

### ISSUE THREAD

**Issue by augenstern-lwx** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#132]
Why set the input resolution of the network to: 368x368？ thank you!

**Comment by Daniil-Osokin** [comment]
You should set it to some value. This is a trade-off between speed and accuracy.

**Comment by augenstern-lwx** [comment]
Can I set it to 224 × 224? Does its setting have anything to do with the coco dataset?


________________________________
发件人: Daniil-Osokin <notifications@github.com>
发送时间: Wednesday, February 10, 2021 5:17:48 AM
收件人: Daniil-Osokin/lightweight-human-pose-estimation.pytorch <lightweight-human-pose-estimation.pytorch@noreply.github.com>
抄送: augenstern-lwx <liwenxingICT@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Daniil-Osokin/lightweight-human-pose-estimation.pytorch] Network resolution (#132)


You should set it to some value. This is a trade-off between speed and accuracy.

―

**Comment by Daniil-Osokin** [comment]
Yes, you can.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
