### ISSUE TITLE
Training-step3-'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by RCpengnan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#133]
Hello, I have been training according to the training steps you gave, and I have gone to step 3. I have encountered the following problems, I'm sure the tra2017 and val2017 file paths are correct and all images are.jpg.Do you have any solutions? Thank you very much!

File "/home/rcpengnan/Daniil-openpose/lightweight-human-pose-estimation.pytorch-master/datasets/transformations.py", line 10, in __call__
    h, w, _ = sample['image'].shape
AttributeError: 'NoneType' object has no attribute 'shape'

![image](https://user-images.githubusercontent.com/74439931/109448670-72c7d200-7a81-11eb-914d-dbd97d813133.png)

**Comment by Daniil-Osokin** [comment]
Hi! It likely does not find the dataset. You can put before the [line 37](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/datasets/coco.py#L37) the following:
```
print(os.path.join(self._images_folder, label['img_paths']))
```
and check if image really exists by the printed path.

**Comment by RCpengnan** [comment]
Thank you.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Daniil-Osokin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月2日(星期二) 凌晨4:35
收件人:&nbsp;&quot;Daniil-Osokin/lightweight-human-pose-estimation.pytorch&quot;<lightweight-human-pose-estimation.pytorch@noreply.github.com&gt;;
抄送:&nbsp;&quot;RCpengnan&quot;<2450856237@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Daniil-Osokin/lightweight-human-pose-estimation.pytorch] Training-step3-&#39;NoneType&#39; object has no attribute &#39;shape&#39; (#133)

**Comment by RCpengnan** [comment]
Thank you!
