### ISSUE TITLE
Does the paf map generated by the network affect the occlusion of some key points of the human body？

### ISSUE THREAD

**Issue by tangfayuan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#135]

**Comment by Daniil-Osokin** [comment]
PAFs are used to group already found keypoints into persons instances. So if no keypoint was found, PAF will not help.

**Comment by tangfayuan** [comment]
What is the role of PAF in code？

**Comment by Daniil-Osokin** [comment]
See more details [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md).

**Comment by tangfayuan** [comment]
thanks,it's very useful

**Comment by tangfayuan** [comment]
Network predicts two separate channels: one for x component and one for y component of connection vector for each keypoints pair as its output.   
 x and y are vectors in vertical and horizontal directions of partial affinity fields？

**Comment by Daniil-Osokin** [comment]
Yes.
