### ISSUE TITLE
Demo stride value

### ISSUE THREAD

**Issue by tsampazk** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#138]
Hello @Daniil-Osokin.

First of all, thank you for your great work!

I ran the demo.py and changed the [stride](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/57db93e3b7254acaa0f03bb67950738ff7d7b1a6/demo.py#L86) value to something other than 8, e.g. 4. I noticed that the keypoints show up on wrong places in the webcam window. 

I suspect it has something to do with the way the keypoint coordinates are rescaled back to the original image size [here.](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/57db93e3b7254acaa0f03bb67950738ff7d7b1a6/demo.py#L102-L103)

Do you have any insight on what goes wrong? Does this stride value matter all that much, is there any benefit in changing it?

**Comment by Daniil-Osokin** [comment]
Hi! Stride is the number of times network output smaller network input. Network output is rescaled to network input size, then post-prcessing with coordinates extraction is performed. So it is better not to change stride without changing the network output size.

**Comment by tsampazk** [comment]
Alright, that makes a lot of sense, thank you very much!
