### ISSUE TITLE
Run code on the GPU

### ISSUE THREAD

**Issue by Ritchiegit** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#139]
Hello, I tried to run this code with GPU, so I installed the GPU version of torch and modified demo.py, changed “checkpoint = torch.load(args.checkpoint_path, map_location='cpu') “to “checkpoint = torch.load(args.checkpoint_path, map_location=lambda storage, loc: storage.cuda(0)”, but I found that the frame rate was not changed. Can you tell me the reason? Thank you!

**Comment by Daniil-Osokin** [comment]
Hi! The code runs on GPU by default, that is why fps is the same. The snipped you have mentioned allows to load weights on GPU device. However [later in the code](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L84), the whole network module is also moved to GPU.

**Comment by Ritchiegit** [comment]
Wow, I see, thank you very much.
