### ISSUE TITLE
Joints coordinates in real-time

### ISSUE THREAD

**Issue by mohamdev** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#14]
Hello Daniil-Osokin, hello everyone ! Thank you very much for your work, it's very good. I would like to get the real-time coordinates of each joint and save them in a CSV file. Where is the place in the code I could get them ? 

I already checked in keypoints.py but I don't know how I could clearly identify each joint (left wrist, right wrist, left elbow, right elbow etc etc) and get it's coordinates in real-time.

Thank you very much for your feedback, have a nice day :)

**Comment by Daniil-Osokin** [comment]
Hi! You can call [convert_to_coco_format](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L136) function, which returns keypoints in [MS COCO](http://cocodataset.org/#home) format order: 'nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear', 'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist', 'left_hip', 'right_hip', 'left_knee', 'right_knee', 'left_ankle', 'right_ankle'.

**Comment by mohamdev** [comment]
Thank you very much for your fast feedback :) !

So, if I understand well, the list coco_keypoints contains the coordinates of each joint like this : [[noseX, noseY]; [left_eyeX, left_eyeY]; [right_eyeX, right_eyeY] ... etc] ?

Also,  what does the list 'scores' contain exactly ? Thanx :)

**Comment by Daniil-Osokin** [comment]
It returns list of `17x3` entries, every entry is `x, y,` coordinates of corresponding keypoint and `visibility` (set to 1 or -1, if this type of keypoint not found). Scores is the confidence of method in particular pose.

**Comment by mohamdev** [comment]
Thank you very much for the time you accorded to respond, your answer is
very helpful to me ! Have a nice week-end :)

Best regards,
ADJEL Mohamed


Le ven. 26 avr. 2019 à 22:26, Daniil-Osokin <notifications@github.com> a
écrit :
