### ISSUE TITLE
preprocessing and normalization 

### ISSUE THREAD

**Issue by polydefk** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#140]
Hello @Daniil-Osokin.

Really nice work that you have done thank you! 

On the normalization why do you divide by 256 and not with 255?

**Comment by Daniil-Osokin** [comment]
Hi! It is a typo happened before the training started (so model was trained with it), more details in #19.

**Comment by polydefk** [comment]
Hi! Good to know! Thanks!
