### ISSUE TITLE
l want to use openpose to solve the problem of meter recognition, but l donot know how to modify the code?

### ISSUE THREAD

**Issue by dreamercv** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#141]
l modified the code reference `TRAIN-ON-CUSTOM-DATASET.md`，during the train , it is work ,but during the val, have some proble 
```shell
[]
Running test for keypoints results.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 130, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "/home/fb/project/docker/openpose/val.py", line 168, in evaluate
    run_coco_eval(labels, output_name)
  File "/home/fb/project/docker/openpose/val.py", line 22, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "/home/fb/anaconda3/envs/openpose/lib/python3.6/site-packages/pycocotools/coco.py", line 328, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

How to modify？

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by RCpengnan** [comment]
Hello, I have the same problem. Now I am making 19 key points and have modified the code. The data sets I used are from Val2017 and Train2017 downloaded from the official website of Coco. Do you mean that I need to re-label the data? Isn't the data set downloaded from the official website of Coco already marked?

**Comment by DongLizhong** [comment]
Hi, why the detection.json is emptywhen valid?

**Comment by Daniil-Osokin** [comment]
The issue is is that empty `detections.json` is not valid. This means that no poses were found at all for the whole dataset, so something went wrong.
