### ISSUE TITLE
Difference between “load_state” and “load_from_mobilenet”

### ISSUE THREAD

**Issue by tangfayuan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#144]
Hello, I would like to ask the difference between“ load_state ”and “load_from_mobilenet” in the code?

**Comment by Daniil-Osokin** [comment]
Due to different checkpoints format two loader functions are needed. Please follow the code for the details.

**Comment by tangfayuan** [comment]
thanks for your help
