### ISSUE TITLE
human-pose-estimation-0002.xml: expected to have 2 outputs

### ISSUE THREAD

**Issue by mohamdev** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#148]
Hi Daniil-Osokin,

I hope you're fine :-)

I am trying to run some pre-trained models which I downloaded using OpenVino Downloader. When I use the pre trained model `human-pose-estimation-0001.xml` running the command `./human_pose_estimation_demo -m <path-to-model-dir>/human-pose-estimation-0001.xml -i 0`, it works perfectly fine. But when I try with other pre-trained models, as `human-pose-estimation-0003` or `human-pose-estimation-0004`, I get the following error : 

```
[ ERROR ] <path-to-model-dir>/human-pose-estimation-0002.xml: expected to have 2 outputs

```

Do you know wher it may come from ?
Thank you for your answers and have a nice day. Best regards

**Comment by Daniil-Osokin** [comment]
Hi! Time goes, and guys have added more models support to the demo (there is also pure Python demo, which is almost as fast as C++). I believe you need a fresh OpenVINO install/build, here is the [PR](https://github.com/openvinotoolkit/open_model_zoo/pull/2110) where new models support is added.

**Comment by mohamdev** [comment]
Thank you very much for your answer :-)
Does this mean that I have to reinstall OpenVino to its newest version or does this mean that my open_model_zoo repo version is too old ?
My current version is the 2021.2.185, so I though it would contain the most recent features.

**Comment by mohamdev** [comment]
I actually downloaded the newest version of open zoo (release one) and it worked fine with its demos, thanks for your answers :-)

**Comment by Daniil-Osokin** [comment]
Great, cool!
