### ISSUE TITLE
Fastest version

### ISSUE THREAD

**Issue by MustafaArikan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#15]
Dear Daniil,

what is the fastest version, I ran the C++ version but could get up to 5 FPS on a Intel i5 CPU?
Maybe I am doing something wrong. Do I have to do something special to achieve >20 FPS?

best regards

**Comment by Daniil-Osokin** [comment]
Guess you run it on a laptop. Have you plugged-in power cable? Or just set "performance mode" in OS. This should help. You can also run network on lower resolution (default is 456x256), just modify last value [here](https://github.com/opencv/open_model_zoo/blob/master/demos/human_pose_estimation_demo/src/human_pose_estimator.cpp#L45), e.g. set 192.

**Comment by MustafaArikan** [comment]
Great, set to 192. Really nice, getting >26 FPS on average.

**Comment by Daniil-Osokin** [comment]
Great!

**Comment by prashant-bansod** [comment]
@Daniil-Osokin  I am also trying to run it on the CPU and the speed I am getting is 3 FPS.  I am trying the python version. Is there a way to achieve a better FPS in python? I am not sure where exactly I need to make changes. Is it in the `with_mobilenet.py`?

**Comment by prashant-bansod** [comment]
@Daniil-Osokin I am running it on Ubuntu 16.04, i7 processor

**Comment by Daniil-Osokin** [comment]
@prashant-bansod You need to use [OpenVINO](https://software.intel.com/en-us/openvino-toolkit) to get better fps on `cpu` in python demo. See #9, may be @dgraeber can share his code with python plugin.

**Comment by nathanRamaNoodles** [comment]
What do I modify to 192?  The file changed.

**Comment by WestbrookZero** [comment]
> Guess you run it on a laptop. Have you plugged-in power cable? Or just set "performance mode" in OS. This should help. You can also run network on lower resolution (default is 456x256), just modify last value [here](https://github.com/opencv/open_model_zoo/blob/master/demos/human_pose_estimation_demo/src/human_pose_estimator.cpp#L45), e.g. set 192.

![image](https://user-images.githubusercontent.com/13358789/114360757-f6f49580-9ba7-11eb-8d5d-b85e74537a40.png)

The link is failed,Could you please send the link again?
