### ISSUE TITLE
Skeleton tracker C++ API

### ISSUE THREAD

**Issue by mohamdev** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#151]
Hi Daniil-Osokin,

I hope you are going fine :-)
I wanted to ask if there is any implementation of the skeleton ID tracker on the C++ API, as there it is on the Python API ?

Thank you for your answer and have a nice day

**Comment by Daniil-Osokin** [comment]
Hi! This is Python-only feature.

**Comment by mohamdev** [comment]
Hi :-)

I understand, thank you for your answer
