### ISSUE TITLE
Validation Problem

### ISSUE THREAD

**Issue by c7934597** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#152]
Pytorch:1.8.0
CUDA:11.1

I use the command, but it can't run. Like Stopping, I do mistake?

python3 val.py --labels /home/minggatsby/GitHub/datasets/annotations_trainval2017/annotations/person_keypoints_val2017.json --images-folder /home/minggatsby/GitHub/datasets/val2017 --checkpoint-path /home/minggatsby/GitHub/models/checkpoint_iter_370000.pth

then, I use ctrl+c

^CTraceback (most recent call last):
  File "val.py", line 178, in <module>
    evaluate(args.labels, args.output_name, args.images_folder, net, args.multiscale, args.visualize)
  File "val.py", line 132, in evaluate
    total_keypoints_num += extract_keypoints(avg_heatmaps[:, :, kpt_idx], all_keypoints_by_type, total_keypoints_num)
  File "/home/minggatsby/GitHub/lightweight-human-pose-estimation.pytorch/modules/keypoints.py", line 12, in extract_keypoints
    heatmap[heatmap < 0.1] = 0
KeyboardInterrupt

**Comment by Daniil-Osokin** [comment]
Validation can be extremely slow if network weights were not loaded properly. Is it the full log after running `val.py`? Does demo run well with this checkpoint?

**Comment by c7934597** [comment]
I run the command, my camera already run, but I can't see any windows. Maybe it's my opencv or qt problem?

python3 demo.py --checkpoint-path /home/minggatsby/GitHub/models/checkpoint_iter_370000.pth --video 0

**Comment by Daniil-Osokin** [comment]
Looks like something went wrong. You can try to run the demo with `--cpu` option to check if it is a gpu-related issue. In general try to localize the line in the code which causes the freeze (or works an enormous time), it may give a hint.

**Comment by c7934597** [comment]
I am using other computer about rtx 2070 super / cuda 10.2 / cuDNN : 8.0.5.39-1 / Pytorch 1.8.0 / opencv 4.5.1.

I run the following command , its error.
python3 demo.py --checkpoint-path /home/minggatsby/GitHub/models/checkpoint_iter_370000.pth --video 0

Traceback (most recent call last):
  File "demo.py", line 166, in <module>
    run_demo(net, frame_provider, args.height_size, args.cpu, args.track, args.smooth)
  File "demo.py", line 93, in run_demo
    heatmaps, pafs, scale, pad = infer_fast(net, img, height_size, stride, upsample_ratio, cpu)
  File "demo.py", line 68, in infer_fast
    stages_output = net(tensor_img)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minggatsby/GitHub/lightweight-human-pose-estimation.pytorch/models/with_mobilenet.py", line 115, in forward
    backbone_features = self.model(x)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/minggatsby/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

===================================================================================
then, I run the following command, it has windows, it can run. However, it still has some error hint.
python3 demo.py --checkpoint-path /home/minggatsby/GitHub/models/checkpoint_iter_370000.pth --video 0 --cpu

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

QObject::moveToThread: Current thread (0x55b0ee071e00) is not the object's thread (0x55b0edb95150).
Cannot move to target thread (0x55b0ee071e00)

**Comment by Daniil-Osokin** [comment]
Great, that it works!
