### ISSUE TITLE
demo  error 

### ISSUE THREAD

**Issue by tangfayuan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#153]
excuse me. I used to run the 'demo.py 'file, the key points of the human body can be detected normally. Suddenly, the key points cannot be detected, and the effect is very poor.
Use GPU debugging .

**Comment by Daniil-Osokin** [comment]
I did not get such behavior. Does it reproduce? You can check if there are any modifications in the code by running `git diff` in the repository directory.

**Comment by tangfayuan** [comment]
thank you very much
