### ISSUE TITLE
Validation output format

### ISSUE THREAD

**Issue by zhouxin666251** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#156]
How `detection.json` is generated?

**Comment by Daniil-Osokin** [comment]
Hi! It contains a list of found keypoints for each human in every image, you can check the [code](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L140) for the details. Results are saved in the [COCO format](https://cocodataset.org/#format-results).
