### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by Ritchiegit** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#157]
Hello, I got the key points of the waist through calculation and modified the code, The checkpoints I got is not empty, but I didn't get any points and lines after training. When I train directly with your original code, the result is that there are no points or lines. But I can get results by running the demo using the pre-trained model you provided.
 I used the pre-trained model you provided for validation that I got an error “num_refinement_stages not defined”.Can you tell me how to solve? Thank you!

**Comment by Daniil-Osokin** [comment]
So, you have modified the code, then train with it new model and got bad results for the new model? If you just train with the original code, and got model which does not work, then please post your PyTorch and CUDA versions, will try to reproduce.

**Comment by Ritchiegit** [comment]
Yes, I trained the original code without any results.
The version I used is as follows:                
torch: 1.4.0+cu92
cuda: Cuda compilation tools, release 9.2, V9.2.88

**Comment by Daniil-Osokin** [comment]
I have tried this version, and everything worked. Can you please post the full training log and the model you have tried.

**Comment by Ritchiegit** [comment]
Sorry. After adding a point, I did not modify the number of points defined in the model. This is my mistake, I'm really sorry.

**Comment by Daniil-Osokin** [comment]
Great, that you have figured out the reason!
