### ISSUE TITLE
DeepStream using the model problem

### ISSUE THREAD

**Issue by c7934597** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#158]
[https://forums.developer.nvidia.com/t/conversion-of-model-weights-for-human-pose-estimation-model-to-onnx-results-in-nonsensical-pose-estimation/164417/13](https://forums.developer.nvidia.com/t/conversion-of-model-weights-for-human-pose-estimation-model-to-onnx-results-in-nonsensical-pose-estimation/164417/13)

I saw the article, I can use their model, but MB size is too size. About 82 MB.
Then, I wanna use your lightweight-human model. I already convert model to onnx, about 16.3 MB.

However , model's output is different. resnet18 is two output , your lightweight-human model is four output.
![resnet18_baseline_att_224x224_A_epoch_249 onnx](https://user-images.githubusercontent.com/9107549/112268061-577f6980-8cb1-11eb-9731-ebaa419df511.png)
![human-pose-estimation onnx](https://user-images.githubusercontent.com/9107549/112268065-58b09680-8cb1-11eb-9a12-6583faee661c.png)

**Comment by Daniil-Osokin** [comment]
Hi! Take the last two, as [done](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L70) during inference.

**Comment by c7934597** [comment]
I understand your mean, I am asking the question at deepstream forum. Because I don't know how to change the count of the output.

[https://forums.developer.nvidia.com/t/support-the-questions-of-lightweight-human-pose-estimation/173417](url)

**Comment by Daniil-Osokin** [comment]
You see, channels number of outputs is different in DeepStream SDK and OpenPose. So, I believe you should adjust the code accordingly. My best guess, is that you can try to replace [topology](https://github.com/NVIDIA-AI-IOT/deepstream_pose_estimation/blob/master/post_process.cpp#L34) vector with this one (and recompile):
```
static Vec2D<int> topology{
    {12, 13, 1, 2},
    {20, 21, 1, 5},
    {14, 15, 2, 3},
    {16, 17, 3, 4},
    {22, 23, 5, 6},
    {24, 25, 6, 7},
    {0, 1, 1, 8},
    {2, 3, 8, 9},
    {4, 5, 9, 10},
    {6, 7, 1, 11},
    {8, 9, 11, 12},
    {10, 11, 12, 13},
    {28, 29, 1, 0},
    {30, 31, 0, 14},
    {34, 35, 14, 16},
    {32, 33, 0, 15},
    {36, 37, 15, 17},
    {18, 19, 2, 16},
    {26, 27, 5, 17}};
```

**Comment by c7934597** [comment]
Yes, DeepStream SDK topology is here. Although, after I had changed topology, it can run. However ,topology seems different, I know DeepStream SDK's 4-6 and 3-5 are unnecessary.

But, other topology also is different location. Do you know the topology image of open pose? The following image is DeepStream SDK topology image.

![rt](https://user-images.githubusercontent.com/9107549/112726196-2031e680-8f57-11eb-97d2-a3f10f03e49a.png)

**Comment by Daniil-Osokin** [comment]
We use the original [OpenPose output format](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md#pose-output-format-coco).

**Comment by c7934597** [comment]
OK, I understand, thank you.

**Comment by Daniil-Osokin** [comment]
I believe DeepStream uses the same keypoints (it number is also 18 in their topology), but more pafs (21 vs 19, the new one is between eyes and hips). So looks like changing the topology to the above one may help. Can you please post your experience of integration this model to DeepStream app? It might help to others.

**Comment by c7934597** [comment]
I fix the following two parts of deepstream program about pose estimation. It can detect keypoints but it still needs improving, because some keypoints still are on the top window.



std::tuple<Vec2D, Vec3D>
parse_objects_from_tensor_meta(NvDsInferTensorMeta *tensor_meta)
{
void *cmap_data = tensor_meta->out_buf_ptrs_host[2];
NvDsInferDims &cmap_dims = tensor_meta->output_layers_info[2].inferDims;
void *paf_data = tensor_meta->out_buf_ptrs_host[3];
NvDsInferDims &paf_dims = tensor_meta->output_layers_info[3].inferDims;


static Vec2D<int> topology{
    {0, 1, 1, 8},
    {2, 3, 8, 9},
    {4, 5, 9, 10},
    {6, 7, 1, 11},
    {8, 9, 11, 12},
    {10, 11, 12, 13},
    {12, 13, 1, 2},
    {14, 15, 2, 3},
    {16, 17, 3, 4},
    {18, 19, 2, 16},
    {20, 21, 1, 5},
    {22, 23, 5, 6},
    {24, 25, 6, 7},
    {26, 27, 5, 17},
    {28, 29, 1, 0},
    {30, 31, 0, 14},
    {32, 33, 0, 15},
    {34, 35, 14, 16},
    {36, 37, 15, 17}};


I don't try it yet, but I think model maybe needs to change input to (1,3,256,256). I mean that before training model, crop image size to (256,256).

**Comment by Daniil-Osokin** [comment]
Set `net-scale-factor=0.00390625` (1/256),  `offsets=128;128;128` and `model-color-format=1`. You can change network input size to (1,3,256,256) during conversion to onnx [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/convert_to_onnx.py#L10).

**Comment by c7934597** [comment]
Set net-scale-factor=0.00390625 (1/256), offsets=128;128;128 and model-color-format=1.
Great, I think that's correct setting. 
It can starts to detect keypoints.

However, I tried many convertsion method, I change network input size to (1,3,256,256) or (1,3,256,456) during conversion to onnx.

Then I also tried the following.
void *cmap_data = tensor_meta->out_buf_ptrs_host[2];
NvDsInferDims &cmap_dims = tensor_meta->output_layers_info[2].inferDims;
void *paf_data = tensor_meta->out_buf_ptrs_host[3];
NvDsInferDims &paf_dims = tensor_meta->output_layers_info[3].inferDims;

or

void *cmap_data = tensor_meta->out_buf_ptrs_host[0];
NvDsInferDims &cmap_dims = tensor_meta->output_layers_info[0].inferDims;
void *paf_data = tensor_meta->out_buf_ptrs_host[1];
NvDsInferDims &paf_dims = tensor_meta->output_layers_info[1].inferDims;


It seems to detect only half data.
Actually, I wanna ask why network needs four output, and then using half output. Maybe that's reason? Because I used the first two output or the last two output, but displaying the same effect. 

Maybe network needs to been changed to two output?


![2021-03-29 11-14-36 的螢幕擷圖](https://user-images.githubusercontent.com/9107549/112783331-aea28700-9081-11eb-81de-478a97b6231d.png)
![123](https://user-images.githubusercontent.com/9107549/112783334-b104e100-9081-11eb-9f4a-473310df8f13.png)

**Comment by Daniil-Osokin** [comment]
Line will be displayed if both keypoints in part are visible, check [here](https://github.com/NVIDIA-AI-IOT/deepstream_pose_estimation/blob/master/deepstream_pose_estimation_app.cpp#L118). You see, all keypoints are on their places. So I believe the issue is in the grouping code. Check these [functions](https://github.com/NVIDIA-AI-IOT/deepstream_pose_estimation/blob/master/deepstream_pose_estimation_app.cpp#L71-L73) to see why keypoints were not grouped into single skeleton instance.

**Comment by c7934597** [comment]
I tried many kinds of topology or changed topology, it still has some circles on the windows top. Maybe these circles affect drawing lines.

I also changed many kinds of input size, but situation is the same. I don't understand how to improve that. 

static Vec2D<int> topology{
    {0, 1, 13, 12},
    {2, 3, 12, 11},
    {4, 5, 10, 9},
    {6, 7, 9, 8},
    {8, 9, 11, 8},
    {10, 11, 5, 6},
    {12, 13, 2, 3},
    {14, 15, 6, 7},
    {16, 17, 3, 4},
    {18, 19, 15, 14},
    {20, 21, 0, 15},
    {22, 23, 0, 14},
    {24, 25, 15, 17},
    {26, 27, 14, 16},
    {28, 29, 17, 5},
    {30, 31, 16, 2},
    {32, 33, 1, 0},
    {34, 35, 1, 5},
    {36, 37, 1, 2},
    {38, 39, 1, 11},
    {40, 41, 1, 8}};

**Comment by Daniil-Osokin** [comment]
It is better to use the topology I have provided. Try to debug to dig into the issue, as suggested above.

**Comment by c7934597** [comment]
I understand, I try it again.

**Comment by tucachmo2202** [comment]
Hi @c7934597,
Have you solve the problem? I try this topylogy
        [[ 0,  1,  1,  2],
        [ 2,  3,  1,  5],
        [ 4,  5,  2,  3],
        [ 6,  7,  3,  4],
        [ 8,  9,  5,  6],
        [10, 11,  6,  7],
        [12, 13,  1,  8],
        [14, 15,  8,  9],
        [16, 17,  9, 10],
        [18, 19,  1, 11],
        [20, 21, 11, 12],
        [22, 23, 12, 13],
        [24, 25,  1,  0],
        [26, 27,  0, 14],
        [28, 29, 14, 16],
        [30, 31,  0, 15],
        [32, 33, 15, 17],
        [34, 35,  2, 16],
        [36, 37,  5, 17]]
and it run in Trt Pose python but when I use it in Deepstream, the result is wrong. Can you tell me what did you change in original deepstream app?

**Comment by c7934597** [comment]
@tucachmo2202 Sorry, I haven't solved the problem not yet. Maybe you can try more methods and then tell us.

**Comment by tucachmo2202** [comment]
@c7934597  Thanks for replying. I'll try it again.
