### ISSUE TITLE
loss curve code

### ISSUE THREAD

**Issue by zhouxin666251** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#159]
I have seen question #10, can you share the code that generates the loss curve? I have tried some codes, but the effect is not good.

**Comment by Daniil-Osokin** [comment]
I do not have this code, it just a simple visualization in `matplotlib`. Suggest to use [`tensorboard`](https://pytorch.org/docs/stable/tensorboard.html) for losses visualizations.

**Comment by zhouxin666251** [comment]
thanks  a lot, have a nice day
