### ISSUE TITLE
Skeletons ID

### ISSUE THREAD

**Issue by mohamdev** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#16]
Hello Daniil Osokin, hello everyone. I have a question about the skeletons tracked by the camera. 

Actually I'm doing games on Unity, and I need to recognize each player that is in front of the camera, so I need to affect a skeleton (with an ID) to each player during the whole duration of a game (the game lasts between 2 and 5 minutes). But if the skeletons are refreshed at each frame I won't be able to do that because each skeleton will have a new ID for every new frame. So my questions are :   

Is it possible to get each skeleton's ID ? Or, are the skeletons refreshed at each frame ? 

Thank you very much for your feedback, I wish you a nice day :)

**Comment by Daniil-Osokin** [comment]
Hi, algorithm does per-frame processing, so it doesn't track any information between frames. However, you can try simple heuristic: find bounding rectangle of skeleton keypoints with [cv::boundingRect](https://docs.opencv.org/2.4/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html?highlight=boundingrect#boundingrect) and check "intersection over union" (IoU) of rectangle on the current frame with rectangles from previous frame. Assign id to skeleton on current frame from best by IoU skeleton on previous frame.

**Comment by mohamdev** [comment]
Thank you very much I will try this :) 

Have a nice day
