### ISSUE TITLE
Estimation of the lying person's pose

### ISSUE THREAD

**Issue by boookk** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#160]
hello, 

The pose of the person lying in bed is not estimated.

Should we train more?

Or, can we use annotation files to estimate a person's pose at that coordinate?

But shouldn't the top-down approach be used in the above case?

**Comment by Daniil-Osokin** [comment]
Hi! Please, post the example of image you are talking about. In general, if you need detection under wide angles, increase the [rotation augmentation](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/57db93e3b7254acaa0f03bb67950738ff7d7b1a6/datasets/transformations.py#L89) parameter.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
