### ISSUE TITLE
Are Sigmas correct?

### ISSUE THREAD

**Issue by JunkyByte** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#162]
Hey Daniil, thank you for you work, I wanted to check with you if sigmas are correct.

From this issue https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/106 I see you got the values from the coco metrics, for `hip` the value recommended by coco seems to be `0.107 (.107 in the coco page)` while on your code is `1.07` https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L15 is this a typo or am I missing something?

Thank you!

**Comment by Daniil-Osokin** [comment]
Hi! This is ok, they are divided by 10 on the [next line](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L16), just to not write extra `0` for other keypoints.

**Comment by JunkyByte** [comment]
sorry Daniil, must have deleted it while adding other values for a different dataset and did not check in the original code.
