### ISSUE TITLE
Question about grouping function

### ISSUE THREAD

**Issue by JunkyByte** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#164]
Hi Daniil, I'm trying to adapt your code for a different dataset, your markdown reference is very helpful and well written, thank you!

I have one question on the grouping function https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/keypoints.py#L124 how should I change this line if the number of keypoints is different? It seems to me that you manually manage the last two `part_id` but I'm not sure.
Should I leave it as it is even if the number of PAFS (and keypoints) changed or let's say my`BODY_PARTS_PAF_IDS` has length of 30 should I switch it to `elif part_id == 28 or part_id == 29:`?

Thank you very much.

**Comment by Daniil-Osokin** [comment]
Hi! These two are auxiliary parts. They are not useful for a new pose instance creation (by design), but add keypoint into skeleton if it missed there. Actually, they just add ears if person stands backwards. So, adjust it for your use case.

**Comment by JunkyByte** [comment]
Oh! Is that the ear to shoulder connection? That makes a lot of sense!
Thank you very much that's kinda cleaver
