### ISSUE TITLE
heatmaps

### ISSUE THREAD

**Issue by tangfayuan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#165]
Excuse me, the network generates 19 key point heatmaps, of which 18 represent keypoints. Does the nineteenth represent 18 key points on one map? So is the loss calculation of the same keypoint repeated?

**Comment by Daniil-Osokin** [comment]
Hi! Please check the [code](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/57db93e3b7254acaa0f03bb67950738ff7d7b1a6/datasets/coco.py#L87) for the details.
