### ISSUE TITLE
Network parameter initialization 

### ISSUE THREAD

**Issue by tangfayuan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#167]
At the beginning of training. In the network, only the initial value of the mobilenet network is assigned. How are the parameter values of the network structure in other stages initialized? For example, how the refinement_stage network parameters are initialized？

**Comment by Daniil-Osokin** [comment]
You can check how PyTorch initializes layers of particular types. For example, here is the [method](https://github.com/pytorch/pytorch/blob/ce79bd255d4f3d78f46f3d5f814d2e0fd878cbea/torch/nn/init.py#L360) for the [convolutional layer initialization](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L141).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by tangfayuan** [comment]
thanks a lot
