### ISSUE TITLE
foot detection

### ISSUE THREAD

**Issue by QixingHuang** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#168]
Can lightweight openpose detect only foot keypoints after training on foot keypoint dataset? [https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/](url)

**Comment by Daniil-Osokin** [comment]
Hi! Yes, think so. Not sure how the original pipeline works, but possibly these steps are necessary: detect the skeleton, crop images around foots and run network for foot estimation on these crops.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
