### ISSUE TITLE
mobilenet v2

### ISSUE THREAD

**Issue by naviocean** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#17]
Hello,
Could you please share me the model base on mobilenet v2?

**Comment by Daniil-Osokin** [comment]
We didn't include it in repo due to the result. For the initial experiment we took the **"max"** version, all layers from the MobileNet v2 untill *conv6_4*. Dilation trick was applied for the *conv4_7* and *conv5_3* layers to maintain spatial resolution.

**Comment by naviocean** [comment]
Thank you so much.
