### ISSUE TITLE
about fps

### ISSUE THREAD

**Issue by bravewhh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#170]
Good job!Do you have any official data on how much FPS can be achieved when running the demo with the pre-training model [https://download.01.org/opencv/openvino_training_extensions/models/human_pose_estimation/checkpoint_iter_370000.pth](https://download.01.org/opencv/openvino_training_extensions/models/human_pose_estimation/checkpoint_iter_370000.pth)

**Comment by bravewhh** [comment]
By the way ,my input resolution is 1080*1920,the FPS is only around 10.

**Comment by Daniil-Osokin** [comment]
Hi! Yeah, check the [paper](https://arxiv.org/pdf/1811.12004.pdf) for the details. You can achieve maximum fps with the [C++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by bravewhh** [comment]
Oh,how kind of you,thank you vvvvery much!
