### ISSUE TITLE
training box

### ISSUE THREAD

**Issue by alicera** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#173]
The image have two boxes, one is green, the other is blue.
The green box is compose of keypoints with demo.py.
The blue box is compose of entire person.

When training, which boxes are better for pose network?
Or both of them doesnt affect training trick.

![image](https://user-images.githubusercontent.com/59388989/116842808-74904c00-ac10-11eb-95e1-ba6af85af9da.png)

**Comment by Daniil-Osokin** [comment]
Hi! For the `prepare_train_labels.py`, the box provided by COCO annotations (the blue one) is better.

**Comment by alicera** [comment]
If I use the green one , does it affect training trick?

**Comment by Daniil-Osokin** [comment]
Yes, it [affects](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/prepare_train_labels.py#L22) data preparation for training. But I believe not dramatically.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
