### ISSUE TITLE
INT8

### ISSUE THREAD

**Issue by alicera** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#176]
I try to use your model to generate the INT8.
But the result of INT8 doesnt detect any object.
The result of FP16 can detect the object.
Do you have any idea?

**Comment by Daniil-Osokin** [comment]
You can download INT8 model for OpenVINO with [model downloader](https://docs.openvinotoolkit.org/latest/omz_tools_downloader.html).

**Comment by alicera** [comment]
If I want to export the model with num-refinement-stages = 2.
Do I only modify the num_refinement_stages = 2 in the line 28 ?

![image](https://user-images.githubusercontent.com/59388989/118217109-63b0c780-b4a7-11eb-926f-46455ca3decc.png)

**Comment by Daniil-Osokin** [comment]
Looks so. I would also add one more output pair to the `output_names` for the extra refinement stage.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
