### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by cuichangrui** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#179]
hello,i was trying to Convert PyTorch model to ONNX format: 
when i  run 
python scripts/convert_to_onnx.py --checkpoint-path default_checkpoints/checkpoint_iter_10000.pth
there has a problem:

cui@cui-virtual-machine:~/lightweighthumanposeestimation$ python scripts/convert_to_onnx.py --checkpoint-path default_checkpoints/checkpoint_iter_10000.pth
Traceback (most recent call last):
  File "scripts/convert_to_onnx.py", line 5, in <module>
    from models import with_mobilenet
ModuleNotFoundError: No module named 'models'

can you help me ?
thank you very much

**Comment by Daniil-Osokin** [comment]
Hi! Looks like something is broken with the install. Do you have `models` directory inside `~/lightweighthumanposeestimation`?

**Comment by cuichangrui** [comment]
hi,i have the models directory inside ~/lightweighthumanposeestimation,and i have init.py in models.I used the direct download of your project



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Daniil-Osokin/lightweight-human-pose-estimation.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 凌晨2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Daniil-Osokin/lightweight-human-pose-estimation.pytorch] ModuleNotFoundError: No module named 'models' (#179)





 
Hi! Looks like something is broken with the install. Do you have models directory inside ~/lightweighthumanposeestimation?

**Comment by Daniil-Osokin** [comment]
Ok, execute `export PYTHONPATH=./` in the terminal before running the script.

**Comment by cuichangrui** [comment]
> 好的，`export PYTHONPATH=./`在运行脚本之前在终端中执行。

thanks

**Comment by Daniil-Osokin** [comment]
Ok, closing.
