### ISSUE TITLE
C++ code

### ISSUE THREAD

**Issue by mohamdev** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#18]
Hello Daniil Osokin, Hello everyone :)

I have a little question about the C++ code, I would like to know where I could find it ? In fact, I can easily find the python code and use functions such as convert_to_coco_format. But if I need the sane function in C++, where could I find it ? 

Thank you very much for your feedback, have a nice day :)

**Comment by Daniil-Osokin** [comment]
There is the [C++ demo](https://github.com/opencv/open_model_zoo/tree/master/demos/human_pose_estimation_demo).

**Comment by Daniil-Osokin** [comment]
Hope, this helped.

**Comment by mohamdev** [comment]
Of course it Helped thank you very much ! Sorry I forgot to respond x) ! Have a Nice day :)

**Comment by KiranVelumuri** [comment]
Could you provide the executable file for the OpenVINO demo? 
I get this error when I use the make command

![Screenshot from 2019-06-26 23-10-55](https://user-images.githubusercontent.com/22117081/60202190-b0656800-9867-11e9-9068-7eae9a9080ea.png)

**Comment by Daniil-Osokin** [comment]
Set LD_LIBRARY_PATH: `export LD_LIBRARY_PATH=<path-to-folder-with-libtbb.so>:$LD_LIBRARY_PATH` and rebuild. `libtbb.so` can be found in OpenVINO installation folder by `find . -name libtbb.so`.

**Comment by KiranVelumuri** [comment]
Thank you very much. I'll try it out first thing tomorrow amd contact you in case of any issues
