### ISSUE TITLE
python demo.py   about   FPS read-time display?

### ISSUE THREAD

**Issue by zhenzhongle** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#180]
Can use demo.py to load the model for detection, how to add the fps real-time display function on this basis ?

**Comment by Daniil-Osokin** [comment]
Hi! You can check fps visualization in the [neighborhood repository](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L120). For the best fps consider using [C++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo).

**Comment by zhenzhongle** [comment]
Okay, I succeeded. Thank you.😀

**Comment by zhenzhongle** [comment]
my laptop is rtx2060， FPS=30.  The original open pose frame rate is 7fps on my laptop

**Comment by Daniil-Osokin** [comment]
Great, closing.
