### ISSUE TITLE
Call a single image

### ISSUE THREAD

**Issue by cuichangrui** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#182]
Hello, I downloaded the pre-training model, and then used the command "python demo.py --checkpoint-path default_checkpoints/checkpoint_iter_370000.pth --image test/dance.jpg "to try to use a picture to view the running results, but there is only a very fast flash, no output results, how can I see the results of this picture

**Comment by Daniil-Osokin** [comment]
Hi! Modify the delay between the frames. You can set [`delay=0`](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L90) to see a single image.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
