### ISSUE TITLE
Why are there 18 human keypoints in this code

### ISSUE THREAD

**Issue by LianhaoXue** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#183]
There are 17 human keypoints in coco data and  18 in this code.
what is the reason for this? 
Thanks for your help!

**Comment by Daniil-Osokin** [comment]
Hi! Neck is added for a better grouping keypoints into persons instances. You can check more details in the [readme](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md#how-to-choose-pairs-of-keypoints-to-connect).

**Comment by LianhaoXue** [comment]
Thank you
