### ISSUE TITLE
Question about accessing to the confidence threshold Values

### ISSUE THREAD

**Issue by soheilAppear** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#185]
Thank you so much for your great works!

I wanted to get the confidence threshold values when running the inference on my dataset, however, I could not find it.
Would you help me and tell me how can I access the confidence threshold values in the code?

Thanks,
Soheil.

**Comment by Daniil-Osokin** [comment]
Hi! Confidence value is stored in the [confidence](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L24) field of the `Pose` class.
