### ISSUE TITLE
loss problem

### ISSUE THREAD

**Issue by tangfayuan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#186]
excuse me. When I replaced Mobilev1 with other networks, I changed the input size to 256*256, the network output size was 64*64, and refinementstages=1. I have checked that the output of init_stage and refinemenstage are not the same. But the loss of Init_stage and refinementstage is the same, what is the reason? 

Connected to pydev debugger (build 193.6494.30)
Iter: 100
stage1_pafs_loss:     199.16625
stage1_heatmaps_loss: 1923.9302294921874
stage2_pafs_loss:     199.16625
stage2_heatmaps_loss: 1923.9302294921874
Iter: 200
stage1_pafs_loss:     207.03625
stage1_heatmaps_loss: 1918.85712890625
stage2_pafs_loss:     207.03625
stage2_heatmaps_loss: 1918.85712890625
Iter: 300
stage1_pafs_loss:     104.88248184204102
stage1_heatmaps_loss: 958.1442211914062
stage2_pafs_loss:     104.87878021240235
stage2_heatmaps_loss: 958.0870104980469

**Comment by Daniil-Osokin** [comment]
Actually losses are also not the same:
```
stage1_pafs_loss: 104.88248184204102
stage1_heatmaps_loss: 958.1442211914062
stage2_pafs_loss: 104.87878021240235
stage2_heatmaps_loss: 958.0870104980469
```

**Comment by tangfayuan** [comment]
If I change the size of the heatmap and pafmap output from the network to 64*48, do I only need to modify crop_x and crop_y in CropPad? Whether it is necessary to regenerate the corresponding prepared_train_annotation.pkl file.
