### ISSUE TITLE
change heatmaps size

### ISSUE THREAD

**Issue by zhouxin666251** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#188]
If I change the size of the heatmap and pafmap output from the network to 64*48, do I only need to modify crop_x and crop_y in CropPad? Whether it is necessary to regenerate the corresponding prepared_train_annotation.pkl file.

**Comment by Daniil-Osokin** [comment]
Hi! I believe you can leave it as is.

**Comment by zhouxin666251** [comment]
thanks a lot
