### ISSUE TITLE
Changing the model architecture for working only on single person

### ISSUE THREAD

**Issue by soheilAppear** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#189]
Hello,

I want to make some changes to the model architecture which can make this algorithm work only on a single person.
I also got your other explanation which was related to changes in the demo code to detect the single person based on this:
for n in range(min(1, len(pose_entries))):

But what I'm looking for is not the above and I want to see which part of the model architecture and algorithm work on the multiple people pose detection? 

Thanks for your great works!

**Comment by soheilAppear** [comment]
So for further explanation, i want to see if its possible to reduce the computational process for detecting multiple people in this model.

**Comment by Daniil-Osokin** [comment]
Hi! If the frame has just 1 person, then no additional costs will be spend just due to mutli-person nature of the method. If you check the [paper](https://arxiv.org/pdf/1811.12004.pdf), final post-processing works > 100 fps with the more than 20 poses estimated. Which speed up you are looking for?

**Comment by Daniil-Osokin** [comment]
I mean that computation part for 2nd or 3rd person is negligible to the rest pipeline. However if you are 100% sure, that your video has no more than 1 person, you can just take the global maximum in each channel of heatmap network output to obtain just 1 the most confident keypoint location. These locations will be keypoints for the just 1 (the most confident) person.

**Comment by soheilAppear** [comment]
thank you for the info!
