### ISSUE TITLE
Is the default value of img_scale the right one?

### ISSUE THREAD

**Issue by LucasVandroux** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#19]
Hello, 
Thanks a lot for your great repo. I have a question about the variable `img_scale` used on the following line: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1f39919c0b5cfffcb57e1a4c3c99eb16d16aad8d/demo.py#L54

According to its use on the line: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/a70ef04304b282f40739383fe6c4e7af245e5395/val.py#L32 I would say that the default value should be `1/255` and not `1/256` as it is a cross product to convert the color values from `0 to 255` to `0 to 1`. 

Is it just a confusion regarding the input size of the image or is there something I didn't understand correctly?

Looking forward to your answer,

**Comment by Daniil-Osokin** [comment]
Hi, good remark! Actually this initially was a typo. After it was observed, we left it as is, just to not redo previous experiments. I don't believe this will change the results, but in general the right value is `1/255` of course.

**Comment by LucasVandroux** [comment]
Thank you for your fast answer. You are right it does not have a big impact to change it.
