### ISSUE TITLE
BODY_PARTS_PAF_IDS

### ISSUE THREAD

**Issue by kevkid** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#191]
Hi @Daniil-Osokin,

I am trying to train on a custom dataset. I know you have probably answered this question a million times and I have read your responses 2x that and I am still confused about how properly set these ids. 

Here are my custom ids:
```
BODY_PARTS_KPT_IDS = [[0, 1], [1, 2], [2, 3], [2, 4], [3, 4]]
BODY_PARTS_PAF_IDS = ([0,1], [1, 2], [2, 3], [2, 4], [3, 4])
```

What I don't understand is what the PAF_IDS correspond to? for example:
```
BODY_PARTS_KPT_IDS = [[1, 2], [1, 5], [2, 3], [3, 4], [5, 6], [6, 7], [1, 8], [8, 9], [9, 10], [1, 11],
                      [11, 12], [12, 13], [1, 0], [0, 14], [14, 16], [0, 15], [15, 17], [2, 16], [5, 17]]
BODY_PARTS_PAF_IDS = ([12, 13], [20, 21], [14, 15], [16, 17], [22, 23], [24, 25], [0, 1], [2, 3], [4, 5],
                      [6, 7], [8, 9], [10, 11], [28, 29], [30, 31], [34, 35], [32, 33], [36, 37], [18, 19], [26, 27])
```

looking at the last element in both ID lists: what does [5, 17] have to do with [26, 27]? There are not even 27 joints? I guess my question is once I have done the first part of training: 
`python train.py --train-images-folder <COCO_HOME>/train2017/ --prepared-train-labels prepared_train_annotation.pkl --val-labels val_subset.json --val-images-folder <COCO_HOME>/val2017/ --checkpoint-path <path_to>/mobilenet_sgd_68.848.pth.tar --from-mobilenet`
What do I do to get my BODY_PARTS_PAF_IDS?

Sorry to ask, but I am really confused about this.

**Comment by Daniil-Osokin** [comment]
Hi! `BODY_PARTS_PAF_IDS` list defines indices of network output channels which encodes connection between corresponding keypoints pair (hope you have went through [TRAIN-ON-CUSTOM-DATASET.md](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md#what-is-body_parts_kpt_ids-and-body_parts_paf_ids)).

**Comment by kevkid** [comment]
> Hi! `BODY_PARTS_PAF_IDS` list defines indices of network output channels which encode connection between corresponding keypoints pair. So, to group keypoints with 5 and 17 ids in a person part, 26 and 27 channels of the second network output need to be used (hope you have went through [TRAIN-ON-CUSTOM-DATASET.md](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md#what-is-body_parts_kpt_ids-and-body_parts_paf_ids)).

Thank you! I will try. 

One more question, I can make this a separate issue if that works.
I have been trying to evaluate my model trained with a custom dataset that consists of a entity with a more limited number of joints (only 5). I was able to modify the train code and train the model, but I can't evaluate? I am getting:

`AssertionError: Results do not correspond to current coco set`

Any idea why this may be happening? I changed:
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L58 to
`keypoints = [0] * 5 * 3`

removed:
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L64-L65

changed https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L73-L75 to:
`            keypoints[position_id + 0] = cx
            keypoints[position_id + 1] = cy
            keypoints[position_id + 2] = visibility`
Changed https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L73-L75 to
```
avg_heatmaps = np.zeros((height, width, 6), dtype=np.float32)# 19
avg_pafs = np.zeros((height, width, 10), dtype=np.float32)# 38
```
and changed  #https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L174 to:
`PoseEstimationWithMobileNet(1, num_heatmaps=6, num_pafs=10)`

But I am getting:
```
Traceback (most recent call last):
  File "val.py", line 216, in <module>
    evaluate(args.labels, args.output_name, args.images_folder, net, args.multiscale, args.visualize)
  File "val.py", line 198, in evaluate
    run_coco_eval(labels, output_name)
  File "val.py", line 21, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "C:\Users\kevin\Anaconda3\lib\site-packages\pycocotools\coco.py", line 327, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
```
Is this due to the coco evaluator expecting 17 keypoints? Is there a way for me to get this to work with only the 5 kps? Do I keep all 17 and only use 5 of them (although it is different anatomy/kp than coco)

**Comment by Daniil-Osokin** [comment]
COCO evaluator works with custom annotation, but it has to be correctly formatted. I believe it is due to gold annotation has different format with predicted. Please, check [COCO](https://cocodataset.org/#format-data) format description. Possibly `categories` in `json` contain more keypoints, than needed. You can make some minimal snippet for gold annotation and predicted to check that you have got the format right.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
