### ISSUE TITLE
train picture

### ISSUE THREAD

**Issue by zhouxin666251** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#192]
I wanted to ask if the pictures used in the training were only pictures containing the human body, and other images that were not participate in the training.

**Comment by Daniil-Osokin** [comment]
Hi! I think so, but please, follow the data preparation [code](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/prepare_train_labels.py).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
