### ISSUE TITLE
About the original open pose and the GFLOPs of the lightweight open pose 

### ISSUE THREAD

**Issue by zhenzhongle** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#193]
hello，The gflops of your lightweight model is 9, while the original 6-stage is 136.1 gflops, and the second-stage is 61.7. But the Dilated MobileNet v1 in Table 4 is 27.7, why is there only 9 in Table 5? Should it be 27.7+1.3+3.4
Looking forward to your answer, thank you very much!

**Comment by Daniil-Osokin** [comment]
Hi! Table 4 for refers to FLOPs of the whole network, varying backbone architectures. So it also includes FLOPs of the initial and refinement stages.

**Comment by zhenzhongle** [comment]
You mean the actual model is Dilated MobileNet v1 in Table 5.  It is part of Dilated MobileNet v1 ( conv5 _ 5 ) in Table 4, about 3.7 / 27.7 = 13 %.  Is it so understood ? 😀

**Comment by Daniil-Osokin** [comment]
Looks so.

**Comment by Daniil-Osokin** [comment]
Ok, closing.
