### ISSUE TITLE
Excluding `area` in the annotation

### ISSUE THREAD

**Issue by renziver** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#194]
I'm working on a custom dataset for keypoint estimation and I'm following the guide to convert the custom data to COCO-Keypoint format. 

One thing that the [prepare_train_labels.py](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/prepare_train_labels.py#:~:text=segment_area%27%3A%20annotation%5B%27area%27%5D%2C) requires is the `segment_area` annotation or the `annotation[area]`. My custom dataset doesn't contain `area` annotations, would it be possible to exclude/remove lines here that uses the `annotation[area]` variable? would there be any impact in the training process if that is omitted?

**Comment by Daniil-Osokin** [comment]
Hi! I believe it can be safely omitted.
