### ISSUE TITLE
Validation error - Group Keypoints doesn't return anything

### ISSUE THREAD

**Issue by renziver** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#197]
I'm encountering some issue with training a custom dataset.

When running validation during training, i'm not getting any results from the `evaluate` function, upon checking deeper, the function `group_keypoints` inside the `evaluate` function is the one that is not returning anything. What is the possible reason for this?

```
print("all_keypoints_by_type length: ", len(all_keypoints_by_type)) 
print("avg_pafs length ", len(avg_pafs)) 

pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, avg_pafs)
print("pose_entries length", len(pose_entries))

coco_keypoints, scores = convert_to_coco_format(pose_entries, all_keypoints)
print("coco_keypoints length: ", len(coco_keypoints))

---

for idx in range(len(coco_keypoints)):
            coco_result.append({
                'image_id': image_id,
                'category_id': 1,  # person
                'keypoints': coco_keypoints[idx],
                'score': scores[idx]
            })
print("coco result length: ", len(coco_result))
```

Output:
```
all_keypoints_by_type length:  18
avg_pafs length  907
pose entries length: 0
coco_keypoints length: 0
coco result length:  0
```

This ultimately causes an error in the training pipeline where no annotations can be found during validation:
```
Traceback (most recent call last):
  File "train.py", line 170, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 130, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "/home/jupyter/lightweight-human-pose-estimation.pytorch/val.py", line 167, in evaluate
    run_coco_eval(labels, output_name)
  File "/home/jupyter/lightweight-human-pose-estimation.pytorch/val.py", line 22, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "/opt/conda/envs/pytorch==1.2.0/lib/python3.6/site-packages/pycocotools/coco.py", line 318, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
```

**Comment by renziver** [comment]
I tested the checkpoint saved and it is not outputting anything on the `demo.py` file. I'm checking if it has something to do with the dataset format that affected the training.

**Comment by Daniil-Osokin** [comment]
Hi! I believe something is wrong with grouping. You can try to check your implementation by passing target data for images in training set into grouping (just replace network output with target data). If it will be also no results, then something is wrong in grouping or there is inconsistency with training data.

**Comment by renziver** [comment]
Resolved the issue by training the model further before doing validations. pre-mature validation from a high-loss training causes the model to not produce outputs.
