### ISSUE TITLE
Y value compared with w instead of h

### ISSUE THREAD

**Issue by nikhilchh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#199]
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/57db93e3b7254acaa0f03bb67950738ff7d7b1a6/datasets/transformations.py#L176

I guess y values should be compared with height of the image.

**Comment by Daniil-Osokin** [comment]
Thanks, fixed in #202.
