### ISSUE TITLE
about pre-trained model

### ISSUE THREAD

**Issue by murdockhou** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#2]
Hi, thanks for your nice work. I have download the pre_trained model from [link](https://download.01.org/openvinotoolkit/open_model_zoo/training_toolbox_pytorch/models/hpe/checkpoint_iter_370000.pth.tar), but can not successfully open it such as there is nothing contained in this .tar file.

**Comment by Daniil-Osokin** [comment]
It is a serialized with `torch.save(...)` checkpoint (`dict` with net state, optimizer state, etc.), so open it as usual with `torch.load(...)`.

**Comment by murdockhou** [comment]
This issue has been solved. If you download pre_trained model with appendix `.tar`, remove it and make its  appendix with `.pth`, it will be work.
