### ISSUE TITLE
using IP camera for real-time demo 

### ISSUE THREAD

**Issue by prashant-bansod** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#20]
@Daniil-Osokin  thanks for sharing your excellent work. I am trying to use an IP camera. 
I used 
```
python demo.py --checkpoint-path scripts/checkp
oint_iter_370000.pth --video rtsp://root:KpShuje@192.168.2.222/axis-media/media.amp

```
I got the following output:
`OSError: Video rtsp://root:KpShuje@192.168.2.222/axis-media/media.amp cannot be opened
` 

It is not able to read the image. Am I doing something wrong here? I am a newbie to CV.
I would really appreciate your advice on this. Thank you

**Comment by Daniil-Osokin** [comment]
This due to OpenCV's `VideoCapture` cannot open video stream by this path. May be you need to specify `ip:port` instead of `user:password@ip`, as mentioned [here](https://stackoverflow.com/questions/49978705/access-ip-camera-in-python-opencv).

**Comment by yogen-p** [comment]
Hey @prashant-bansod , did it work and what did you write to make it work ?
