### ISSUE TITLE
Data preparation always keeping one person at/around center. Why ?

### ISSUE THREAD

**Issue by nikhilchh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#201]
When you center your data around the main person center(+-40), does it not mean that the network is biased by being too good at detecting a person towards the center of the image. And not good at detecting person which are on the edge of the images.
I feel the model will then work better when the body is towards the center of the image. This problem will not happen if there is a fully convolutional network.
Correct me if I am wrong ?

**Comment by Daniil-Osokin** [comment]
Hi! I believe this preprocessing is to ensure, that at least one person will have reasonable size of keypoints in heatmaps to have stable training. But possibly it is a legacy, and network may train without it.

**Comment by nikhilchh** [comment]
Thanks for the clarification.
