### ISSUE TITLE
checkpoint 370000 is with 1 refinement stage

### ISSUE THREAD

**Issue by nikhilchh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#203]
The readme says that checkpoint 370000 is saved after training with 3 refinement stages.
But seems like the model is with 1 refinement stage.
Can you confirm is the model is with 1 refinement stage ?
If yes then you can edit readme Point number 5 of training steps.

**Comment by Daniil-Osokin** [comment]
Hi! No, you can find all 3 refinement stages in the checkpoint.

**Comment by nikhilchh** [comment]
If see the code in demo.py or even in val.py
You initiate the PoseEstimationWithMobileNet with default values.
And default value for num_refinement_stages =1

Your Code in demo.py and val.py
net = PoseEstimationWithMobileNet()
checkpoint = torch.load(args.checkpoint_path, map_location='cpu')

And this code works with the checkpoint that you have provided (370000). Which means your checkpoint has 1 refinement layer as it is able to load in to PoseEstimationWithMobileNet which was initialised with 1 refinement layer.

**Comment by Daniil-Osokin** [comment]
But you can find all 3 refinement stages in the checkpoint.

**Comment by nikhilchh** [comment]
ok got your point. You are saying checkpoint has 3 stages. And it also works fine when only 1 stage loaded.
Thank you for clarifying.
