### ISSUE TITLE
Can we run this model on a CPU only device ?

### ISSUE THREAD

**Issue by jsm2312** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#204]
I am trying to run this model on a CPU only device, NO GPU available.

**Comment by Daniil-Osokin** [comment]
Hi! It is totally fine, how is your progress?

**Comment by jsm2312** [comment]
I am trying to train the model on CPU only, found the code depending on CUDA, thus, I modified the code, removed CUDA dependency. Post that the train.py gives my BrokenPipeError: [Errno 32] Broken pipe. Appreciate your help

**Comment by Daniil-Osokin** [comment]
Oh, you are going to train it, not run the demo. I believe you can just remove `.cuda()` calls since [line 74](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L74) to run training on cpu.

**Comment by jsm2312** [comment]
> Oh, you are going to train it, not run the demo. I believe you can just remove `.cuda()` calls since [line 74](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L74) to run training on cpu.

Already did that and replaced it with .cpu(), I get a whole set of warnings and then after a while of training BrokenPipeError: [Errno 32] Broken pipe , I have an Intel i5 8th Gen CPU

**Comment by Daniil-Osokin** [comment]
Are you using Windows? You can follow this [advice](https://github.com/pytorch/pytorch/issues/2341#issuecomment-346539682) to set `num_workers=1`.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
