### ISSUE TITLE
This is a problem of updating the project

### ISSUE THREAD

**Issue by zhenzhongle** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#205]
Hello, your project is based on early openpose lightweight improvements, this project is very practical.  The openpose updated in 2019 turns the prediction of PAFs and key points heatmaps into six stages in series, and it is the first prediction of PAFs and then the prediction of key points, which makes it more accurate and faster.   I don ' t know if you have time to update your project in the prediction stage, expect your project can become faster, better, have more praise and collection !  ! !😀👍

**Comment by Daniil-Osokin** [comment]
Hi! Thanks for letting know this 😃.

**Comment by zhenzhongle** [comment]
you're welcome！  The address of the paper is  [https://ieeexplore.ieee.org/abstract/document/8765346](url)  。They also changed the original 7 * 7 convolution to the same 3 * 3 combination as in your project, but they didn 't use the dilated convolution 。

**Comment by Daniil-Osokin** [comment]
Ok, closing.
