### ISSUE TITLE
What dataset was used ?

### ISSUE THREAD

**Issue by mrgiba** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#206]
Hello,

I would like to try out the model available here, but firstly I would like to ask if the CMU Panoptic dataset has been used to train the model - if so, my concern is that CMU dataset can only be used for research purposes (according to [their website](http://domedb.perception.cs.cmu.edu/)), which makes me wonder whether the Apache License, which allows commercial usage, is suitable for Lightweight Open Pose 

Thanks

**Comment by Daniil-Osokin** [comment]
Hi! We have used COCO dataset to train the model. Backbone was trained using ImageNet dataset.

**Comment by mrgiba** [comment]
Nice !

So my concern now only applies to the 3d model variation, which was trained on MS COCO and CMU Panoptic

Thanks

**Comment by Daniil-Osokin** [comment]
Ok, closing.
