### ISSUE TITLE
Ambiguous arm position depending on person perspective

### ISSUE THREAD

**Issue by mrgiba** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#209]
Hello,

Now that I have the keypoints being recognized by the model, I am starting to think of the logic to catch specific limb movements, for example an arm raise

Say a camera is at one corner of the ceiling, capturing image of a person with his back to the camera and leaning over a table with his arms. From the camera perspective, since the vertical coordinate of both elbow and wrist would be above the shoulder (which could be a good candidate for a arm raise), I wonder what heuristic could be applied to not regard that scenario as an arm raise

Thanks

**Comment by Daniil-Osokin** [comment]
Hi! For the action recognition you can check the [specific models](https://docs.openvinotoolkit.org/latest/omz_models_model_person_detection_raisinghand_recognition_0001.html) or use tricks from various papers, such as [this](https://tel.archives-ouvertes.fr/tel-02492463/document) or [this](https://www.mdpi.com/2079-9292/10/9/1118/pdf).

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
