### ISSUE TITLE
Identify detected People

### ISSUE THREAD

**Issue by fclyyxy1999** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#21]
Thanks for your contribution.
I want to know how can I identify all detected people? For example,label them.
And then,add rectangular box for one.Now I was blocked in identifying people,I just know "len(pose_entries)" means number of detected people.

Is it possible for my idea to come true?  Or could you please give me a suggestion

Best wishes.

**Comment by mohamdev** [comment]
Hello :), I had the same issue, Daniil Osokin responded to me here : https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/16

I didnt implement the script yet

Have a nice day !

**Comment by fclyyxy1999** [comment]
Hi, thanks for your reply. I've read #16.And I will try that method.I have two suggestions for your situation.

1.At present, I have completed the detection of a simple action through key points coordinates and then tracking the human who do it(signal tracking).But real time and accuracy are not good when using webcam.That's my problem.For you,I think you can look at multi tracking.
2.I've seen an action recognition project based on openpose that mentions adding Numbers to everyone, but not unique Numbers.If you are interested, you can reproduce the project and determine if it is useful.

I will send them to you. I forgot my gmail so I used 163 email in China. If you don't receive.Please tell me.
Besides, I would be very glad too if you achieved your work and send it to me! :) 
fclyyxy1999@163.com(send more than one times~~)

**Comment by Daniil-Osokin** [comment]
Looks like this feature is :fire:. Check it out #24!
![jumpers](https://user-images.githubusercontent.com/2491976/57970861-61d2cd00-798f-11e9-8887-a8acc85562a5.gif)

**Comment by mohamdev** [comment]
Wooow Nice man thank you very much !! This will save us so much Time and energy haha ! I hope God brings you to heaven

**Comment by fclyyxy1999** [comment]
Thanks a lot!! You are really a good man!
