### ISSUE TITLE
模型的速度问题

### ISSUE THREAD

**Issue by GitHubjinliu** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#210]
可以达到实时要求吗？（25-30fps）

**Comment by Daniil-Osokin** [comment]
Hi! It works in real-time. Method consists of two parts: the network inference and results post-processing. Post-processing code is a bit slow in Python, so consider using [C++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
