### ISSUE TITLE
Top-down or Bottom-up

### ISSUE THREAD

**Issue by GitHubjinliu** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#211]
Top-down or Bottom-up？

**Comment by zhenzhongle** [comment]
Like the original open pose, it is bottom-up.

**Comment by GitHubjinliu** [comment]
Thanks for your answer！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Daniil-Osokin/lightweight-human-pose-estimation.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 中午11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Daniil-Osokin/lightweight-human-pose-estimation.pytorch] Top-down or Bottom-up (#211)





 
Like the original open pose, it is bottom-up.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Daniil-Osokin** [comment]
@zhenzhongle Thanks for the answer!
