### ISSUE TITLE
Questions about the application and fps.

### ISSUE THREAD

**Issue by poornimajd** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#215]
Hello Thank you for the open-source code and great work!
I had the following questions -

1)Can we apply this code to a use-case as follows-
A static camera is observing 2-3 moving robots in its FOV,and if I retrain the network with the images of the robot,with its corresponding ground-truth keypoints,the network can still predict the 2d keypoints of the moving robots right?

2)For this does the robot have to be at a particular distance from the camera,so that the keypoint estimation is accurate enough?Meaning is the network's accuracy dependent on "the distance the object is from the camera"?

3)Also in the paper the inference time is reported on the cpu as 26 fps,so can I use this network on nvidia xavier also? I will get higher fps in that case right?

4)The network is not specific to run only on intel cpu right?

Any suggestions/replies are greatly appreciated!
Thank you

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
