### ISSUE TITLE
Using MPII and other datasets for training

### ISSUE THREAD

**Issue by nikhilchh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#216]
Current code has dependency on COCO format at various stages:
1- JSON file should be similar to COCO even though sequence/number of keypoints can be different.
2- pkl should be same
3- data loading also depends on coco format. PAF pairs are hard coded according to coco.
4- data transformation (reordering and neck creation).

I tried to add MPII data for training. Even though i got json file which similar to coco( but different set of keypoints and sequence) i still need to do a lot of changes to be able to use it.

These are the changes that I am planning to do:
1- Create json file for every dataset in coco format and only consider 12 keypoints which are common with most of the datasets. (pairs of shoulders, elbows, wrists, hips, knees, ankles.). Create extra keypoints like neck and head-center at this stage. Neck head-center keypoint creation code will be specific to every dataset. Now we will have a standard json file for every dataset with 14 keypoints. 
2- Rest of the code will be modified according to 14 keypoints, their standard sequence and paf pairs. This include cocodataset class, keypoint transformations if any required. 

I would like to get your feedback regarding above.

I saw that you created a branch to use custom dataset but seems like it doesn't exist anymore. What's the reason ?

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by nikhilchh** [comment]
It worked. 
I have now 14 keypoints, (15 heatmaps) and 13 Limbs (PAFs).
