### ISSUE TITLE
What is the significance of reordering?

### ISSUE THREAD

**Issue by nikhilchh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#217]
reorder_map = [1, 7, 9, 11, 6, 8, 10, 13, 15, 17, 12, 14, 16, 3, 2, 5, 4]

1- Why do you reorder the coco to above order ?
2- And what is the advantage of adding a neck ? 
3- And why do this during training why not during pkl data preparation ?

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by nikhilchh** [comment]
Thanks. 
You are right. It worked even when i made the sequence same in both files.
