### ISSUE TITLE
val

### ISSUE THREAD

**Issue by alicera** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#218]
How to val custom data ?

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by alicera** [comment]
I use the val.py and meet the error.
```
Traceback (most recent call last):
  File "val.py", line 188, in <module>
    evaluate(args.labels, args.output_name, args.images_folder, net, args.multiscale, args.visualize)
  File "val.py", line 139, in evaluate
    image_id = int(file_name[0:file_name.rfind('.')])
ValueError: invalid literal for int() with base 10: 
```

**Comment by Daniil-Osokin** [comment]
Looks like the names of images you have differ from the names of images in the COCO dataset. Just adjust the code for your data.

**Comment by alicera** [comment]
You mean 000000000139.jpg ?

**Comment by Daniil-Osokin** [comment]
Yes. Anyway, you can set a breakpoint and debug this line of code.

**Comment by alicera** [comment]
Hi,
I try to eval 800 images, but its speed is slow.
I wait for 30 minutes above to eval it.
Do you have the method to speed up?

**Comment by Daniil-Osokin** [comment]
I do not have it, however you can use smaller number of images. Slow speed during validation usually means, that network was not trained well, try to train it more iterations, before the evaluation.
