### ISSUE TITLE
python demo too slow

### ISSUE THREAD

**Issue by jesszgc** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#22]
<1fps, cpu :i7-4790 3.6GHz, too slow

**Comment by Daniil-Osokin** [comment]
Have you ran it in `cpu` mode? Python demo is for the quick results preview (run it on `gpu` to get better fps). To run it on `cpu` you need a good inference backend, e.g. [OpenVINO](https://software.intel.com/en-us/openvino-toolkit). Use [c++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo) for the best performance on cpu.

**Comment by Daniil-Osokin** [comment]
Hope this helped.
