### ISSUE TITLE
body_keypoint Confidence

### ISSUE THREAD

**Issue by fenfen-code** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#221]
Please,where can I get the confidence of each body key point?

**Comment by Daniil-Osokin** [comment]
Hi! Keypoint confidence is a value in the heatmap at corresponding keypoint coordinates. You can find it [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/keypoints.py#L38), 3rd value.

**Comment by fenfen-code** [comment]
Thanks！

**Comment by Daniil-Osokin** [comment]
Great!
