### ISSUE TITLE
shift = stride / 2 - 0.5，why -0.5?

### ISSUE THREAD

**Issue by lawo123** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#223]
def _add_gaussian(self, keypoint_map, x, y, stride, sigma):

        n_sigma = 4
        tl = [int(x - n_sigma * sigma), int(y - n_sigma * sigma)]
        tl[0] = max(tl[0], 0)
        tl[1] = max(tl[1], 0)
        br = [int(x + n_sigma * sigma), int(y + n_sigma * sigma)]
        map_h, map_w = keypoint_map.shape
        br[0] = min(br[0], map_w * stride)
        br[1] = min(br[1], map_h * stride)

        shift = stride / 2 - 0.5  ##**why -0.5？**
        for map_y in range(tl[1] // stride, br[1] // stride):
            for map_x in range(tl[0] // stride, br[0] // stride):
                d2 = (map_x * stride + shift - x) * (map_x * stride + shift - x) + \
                    (map_y * stride + shift - y) * (map_y * stride + shift - y)
                exponent = d2 / 2 / sigma / sigma
                if exponent > 4.6052:  # threshold, ln(100), ~0.01
                    continue
                keypoint_map[map_y, map_x] += math.exp(-exponent)
                if keypoint_map[map_y, map_x] > 1:
                    keypoint_map[map_y, map_x] = 1

@Daniil-Osokin

**Comment by Daniil-Osokin** [comment]
Hi! For a better precision: move to the pixel center from bottom right corner.

**Comment by lawo123** [comment]
> Hi! For a better precision: move to the pixel center from bottom right corner.

thank you for your reply。
shift = stride / 2  move to the pixel center from bottom right corner.
why  shift = stride / 2 -0.5 ?
@Daniil-Osokin

**Comment by lawo123** [comment]
> > Hi! For a better precision: move to the pixel center from bottom right corner.
> 
> thank you for your reply。 shift = stride / 2 move to the pixel center from bottom right corner. why shift = stride / 2 -0.5 ? @Daniil-Osokin


Is it because of the opencv resize formula?   SrcX=(dstX+0.5)* (srcWidth/dstWidth) -0.5

**Comment by Daniil-Osokin** [comment]
It is to move to the pixel center. `stride` - how many pixels in the input image correspond to one cell of the network output. `stride / 2` shifts to the bottom right of center pixel.

**Comment by lawo123** [comment]
Thank you very much for your reply
