### ISSUE TITLE
Training for a smaller network input 

### ISSUE THREAD

**Issue by yolo765** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#224]
I am downsizing the input image from 368 to 128 due to inference time limit, heatmaps will be 16x16 instead of 46x46, the results don't look good. Maybe I should tune sigma = 7 and n_sigma = 4 for the smaller input size?

**Comment by Daniil-Osokin** [comment]
Hi! You can infer the same network, which was trained with original 368 resolution. Pass `--height-size 128` for the [demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L145) script. Training with smaller resolution might not result in good accuracy.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
