### ISSUE TITLE
traning question

### ISSUE THREAD

**Issue by duyuanfu** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#225]
Hello, I used the weight file 'checkpoint_iter_370000.pth' you provided for fine-tuning training, and then used the new weight file to test, the result is very poor, what is going on?

**Comment by Daniil-Osokin** [comment]
Hi! How did you run the fine-tuning procedure?

**Comment by Daniil-Osokin** [comment]
Hope, it works.
