### ISSUE TITLE
Training without results

### ISSUE THREAD

**Issue by favor6** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#226]
I trained my own datasets, and it didn't work when the model was validated. When annotating my own datasets, annotate only one person in the picture, whether it will affect the training.

**Comment by Daniil-Osokin** [comment]
Hi! If there is only one person in the your dataset image, it should be ok. If there are multiple persons inside the your dataset image, but labeled only one, this will give bad results, because not all persons were labeled.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
