### ISSUE TITLE
Generate annotations in the COCO format for a custom data

### ISSUE THREAD

**Issue by WestbrookZero** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#229]
How do I use my own data set to generate the person_keypoints_train2017.json file for training the model？

**Comment by Daniil-Osokin** [comment]
Hi! Please, follow the COCO dataset annotation [format](https://cocodataset.org/#format-data).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
