### ISSUE TITLE
The results of my test are inconsistent with those in the paper, and there is a lot of difference

### ISSUE THREAD

**Issue by shenjunyuqwert** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#230]
The ap（iou=0.5:0.95） of my test with three refinestagement is 0.262 which has a big gap with the result of 0.4 in your paper.
![ad63841c5e0825c752f9a6e433710ee](https://user-images.githubusercontent.com/59952043/148917992-7c1469f7-b96d-44c4-b710-69acf265123a.jpg)

**Comment by shenjunyuqwert** [comment]
I do it with the checkpoint_iter_370000.pth in your github project,using one refinestage in test phrase.

**Comment by Daniil-Osokin** [comment]
Hi, it looks strange. Please, post the exact command line you have run.

**Comment by Daniil-Osokin** [comment]
Hope, it works.
