### ISSUE TITLE
segmentations

### ISSUE THREAD

**Issue by alicera** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#231]
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/datasets/coco.py#L39

If using custom data, I have to label segmentations polygon ?

Can I only label keypoint and person bounding box?

**Comment by Daniil-Osokin** [comment]
Hi! Yes, you can just comment out this line. Check #127, #207 for more info about mask usage.

**Comment by alicera** [comment]
Some images in COCO has unlabeled areas, mask is used to compute loss for labeled areas only.

But I only train my data 10000 images and I don't label segmentations polygon for all.
Does your method will not train my data (loss is always 0)? Because all of the data don't label segmentations.

**Comment by Daniil-Osokin** [comment]
Please, check the previous line of code. It creates a mask and fills it with ones, so loss will be computed over all image. This line excludes from loss unlabeled areas, so you can comment it out.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by JJLimmm** [comment]
Hi,

I have a few questions after reading the tips and issues pointed out here.
I am currently using Labelme to annotate the keypoints and would convert them to the COCO format later on. 

1. What if my custom dataset only has keypoints annotated?

2. If i have the 18 keypoints like shown in the image below,  where can i change the keypoint definitions in this repo to match my usage?  
![pose_estimation_keypoints](https://user-images.githubusercontent.com/79782049/183330002-bd95bdf1-41b3-4e1f-9611-67606cbfbf2d.png)

3. And for Validation of the model, are other metrics available like PCK, PCP ([more info](https://github.com/cbsudux/Human-Pose-Estimation-101#evaluation-metrics))? Would i be able to use your validation metrics with just keypoints in my GTs?

Thanks!
