### ISSUE TITLE
Question about the result of your project

### ISSUE THREAD

**Issue by skwjdwns** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#232]
Could I know how many epochs the model has been trained and your project's performance results?

I tested your project and the performance is as below.

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.243
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.510
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.204
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.140
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.398
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.302
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.548
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.282
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.139
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.527

**Comment by Daniil-Osokin** [comment]
Hi! The training protocol is described in the readme. Can you please post the exact command line you have used to get this results?

**Comment by Daniil-Osokin** [comment]
Hope, it reproduces.
