### ISSUE TITLE
coco annotation

### ISSUE THREAD

**Issue by alicera** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#234]
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/scripts/prepare_train_labels.py#L111

I try to print "annotation['segmentation']"
```
{'counts': [43835, 3, 339, 5, 337, 8, 6, 2, 6, 1, 319, 14, 1, 9, 319, 24, 319, 24, 319, 24, 319, 8, 2, 14, 319, 6, 4, 14, 319, 4, 4, 2, 334, 2, 357, 3, 6153, 4, 338, 8, 335, 12, 331, 12, 331, 12, 331, 12, 331, 12, 331, 12, 332, 5, 339, 4, 331, 6, 4, 1, 331, 8, 334, 8, 334, 11, 332, 12, 331, 12, 331, 12, 331, 12, 331, 11, 332, 9, 335, 9, 335, 8, 337, 7, 337, 8, 334, 10, 332, 12, 331, 12, 331, 12, 331, 12, 331, 12, 331, 11, 332, 10, 334, 3, 2, 3, 336, 1, 41156, 6, 336, 8, 334, 10, 332, 12, 331, 12, 331, 12, 331, 12, 331, 12, 331, 12, 331, 12, 332, 10, 334, 8, 337, 4, 87108, 6, 336, 8, 334, 10, 332, 12, 331, 12, 331, 12, 331, 12, 331, 12, 331, 12, 331, 12, 332, 10, 334, 8, 337, 4, 17921], 'size': [343, 640]}
```

But the coco format  "segmentation"
```
{
	"segmentation": [[510.66,423.01,511.72,420.03,510.45......]],
	"area": 702.1057499999998,
	"iscrowd": 0,
	"image_id": 289343,
	"bbox": [473.07,395.93,38.65,28.67],
	"category_id": 18,
	"id": 1768
},
```

Where are the 'counts' and  'size'

**Comment by Daniil-Osokin** [comment]
Hi! Do you have the error running this script with the COCO dataset?

**Comment by alicera** [comment]
I dont meet any warning.
The original json (coco) will generate the 'counts' and 'size' after doing prepare_train_labels.py

**Comment by Daniil-Osokin** [comment]
If you mean difference in the formats, segmented polygons can be in 2 different formats: list of vertices coordinates and in RLE. `counts` and `size` refer to RLE. You may check [here](https://stackoverflow.com/questions/49494337/encode-numpy-array-using-uncompressed-rle-for-coco-dataset) for the details.
