### ISSUE TITLE
Init weights of non-backbone networks

### ISSUE THREAD

**Issue by nikhilchh** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#240]
When u start training from scratch u initialize weights of backbone using mobilenet model. But what about other non-backbone weight ? Are they also initialized somewhere or random init for them ?

**Comment by Daniil-Osokin** [comment]
Hi, check the `torch.nn.Conv2d` [docs](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html#conv2d) (in the end).
