### ISSUE TITLE
onnx export and onnx inference?

### ISSUE THREAD

**Issue by jinfagang** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#241]
onnx export and onnx inference?

**Comment by Daniil-Osokin** [comment]
Hi, you can check the [README](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#conversion-to-openvino-format) for the export to ONNX.

**Comment by jinfagang** [comment]
@Daniil-Osokin Hi, just wonder if the postprocessing such as resize on heatmap and pafs, and selecting keypoints from heatmap can merged into model graph or not? If so, it can be more efficient maybe

**Comment by Daniil-Osokin** [comment]
Do not know, you may try.

**Comment by Daniil-Osokin** [comment]
Ok, closing.

**Comment by jinfagang** [comment]
Sorry for the reply, here is the conclusion: it's not likely to wrap heat map calculation to onnx, but using post processing is OK though, not very slow.
