### ISSUE TITLE
Make the model smaller

### ISSUE THREAD

**Issue by liamsun2019** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#245]
Hi, just wonder if there's any chance to make the model smaller so as to be deployed to resource-constrained devices such as embedded cpu/npu. Any suggestions? Big thanks.

**Comment by Daniil-Osokin** [comment]
Hi! Yes, there are plenty of techniques, such as network pruning, knowledge distillation or just experiments with network design. Actually this network already runs 4-6 fps on the Movidius VPU. As quick thing to try, use no refinement stages or decrease network input resolution.

**Comment by liamsun2019** [comment]
Thanks. 4~6 fps is far from real-time 30 fps. My target is to achieve 30fps, i.e, near the performance of movenet. I will try any possible ways to make improvement anyway.

**Comment by Daniil-Osokin** [comment]
You may try it as is or check quick options I have described above.

**Comment by liamsun2019** [comment]
OK. BTW, I'm curious about the input size 368x368. Is there any special reason for such size?

**Comment by Daniil-Osokin** [comment]
For the inference you can use any resolution. In general, smaller resolution - worse results.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
