### ISSUE TITLE
Inference very slow on mac

### ISSUE THREAD

**Issue by gsrujana** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#247]
I tried running the cpu version of the python demo on macbook with video cam. The models runs really slow. Any suggestions on how to improve framerate?
Thanks

**Comment by Daniil-Osokin** [comment]
Hi! You can try to run the [C++ demo with OpenVINO](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo) or try to run with torch script. Also you can pass [`--height-size 192`](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L145) or less to the demo script for the faster inference.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
