### ISSUE TITLE
How to test video with openvino

### ISSUE THREAD

**Issue by Hans56789** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#249]
Excuse me, I want to use openvino to test the number of frames of video. How to do it? I haven't used openvino. Please explain it

**Comment by Daniil-Osokin** [comment]
Hi, please follow OpenVINO docs and support.

**Comment by Hans56789** [comment]
When I download it, how can I operate it? I haven't used this software before. Can you tell me？Thank you very much!!!!!

**Comment by Daniil-Osokin** [comment]
Please follow the [official instructions](https://docs.openvino.ai/latest/get_started.html).

**Comment by Hans56789** [comment]
Please tell me what "human-pose-estimation.xml" is. I didn't find it after configuring openvino.
![6VY_DCN2FQZUDE9N7P%2R_9](https://user-images.githubusercontent.com/82496916/157606251-ef6ff392-127a-4d3a-8fb9-0e0e8e672261.png)

**Comment by Daniil-Osokin** [comment]
You have to download model to use it. Check instructions [here](https://stackoverflow.com/questions/59372361/downloading-pre-trained-models-from-openvino-toolkit-pre-trained-models-by-ubun) or follow the official documentation.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
