### ISSUE TITLE
pose coordinates for each person

### ISSUE THREAD

**Issue by prashant-bansod** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#25]
@Daniil-Osokin  I was looking for pose coordinates of all people present in a frame.
I called the function `convert_to_coco_format(pose_entries,all_keypoints)` inside the run_demo function.  If there are two people in a frame will that give me pose coordinates of each individual?
I checked the output but it is showing coordinates of one person only.  Maybe I am wrong. I would appreciate your advice. Thank you.

**Comment by Daniil-Osokin** [comment]
I've recently added pose id tracking code, it also has [facility](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L112) to convert processing results to list of poses. Hope, it will make results interpretation easier.
