### ISSUE TITLE
How to run the demo with  image?

### ISSUE THREAD

**Issue by houshuaishuai** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#250]
when i run "python demo.py   --checkpoint-path default_checkpoints/checkpoint_iter_370000.pth --images  data/2.jpg" ,it flash quit?  thanks a lot.

**Comment by Daniil-Osokin** [comment]
Hi! Images are processed one by one, so with 1 image you probably did not catch it. Set `delay=0` [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L90).

**Comment by houshuaishuai** [comment]
It works ! Thank you very much,

**Comment by Daniil-Osokin** [comment]
Great, that it helped!

**Comment by houshuaishuai** [comment]
I follow the readme file trained all 3 step,got the best AP50.6% after 52,0000 iterators.do you think is there have any imporvement in this project ? like you said in papers knowledge distillation, and quantization&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Daniil-Osokin/lightweight-human-pose-estimation.pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 凌晨0:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Daniil-Osokin/lightweight-human-pose-estimation.pytorch] How to run the demo with  image? (Issue #250)





 
Great, that it helped!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

checkpoint_iter_520000.pth (83.89M, 2022年04月14日 17:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7e383764ac80f8cf25cb575910380b1a50015550000a58511c5b0e0602150d54070d1a06505b5b18015e075c005d0c0c5001515536223956595d540f4657505b45675e10534a6600030807540616494159380a&code=187d6895
