### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by younes-h** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#251]
I have encountered an error while trying to val.py on coco val2017 : 
1/ I run this : 
python val.py --labels /content/lightweight-human-pose-estimation.pytorch/data/coco/annotations/person_keypoints_val2017.json --images-folder /content/lightweight-human-pose-estimation.pytorch/data/coco/val2017 --checkpoint-path /content/lightweight-human-pose-estimation.pytorch/checkpoint_iter_370000.pth

2/ after execution, I obtained this
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by Daniil-Osokin** [comment]
Hi! Do you need any help with this?

**Comment by younes-h** [comment]
Yes.
I didn't find the cause of this error ?

**Comment by younes-h** [comment]
It works fine now after reimplementing the evaluation method.
Thanks

**Comment by Daniil-Osokin** [comment]
Cool!
