### ISSUE TITLE
If I want to change to OCHuman dataset, what do I need to modify in your code

### ISSUE THREAD

**Issue by Hans56789** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#252]
Data and from：https://github.com/liruilong940607/OCHumanApi
Thank you very much!!!

**Comment by Daniil-Osokin** [comment]
Hi! Please follow [TRAIN-ON-CUDTOM-DATASET](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md) guide.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
