### ISSUE TITLE
Smile, fingers

### ISSUE THREAD

**Issue by UcefMountacer** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#253]
Hello,

Thanks for this model, it's amazing.

## **Question**

I wanted to know, since you trained on coco2017 dataset, this model should be able to detect smiles and fingers poses. 

![hand_result](https://user-images.githubusercontent.com/47783157/158843362-3589d721-1992-4176-aa66-ba4585ffdf9a.png)
![face_result](https://user-images.githubusercontent.com/47783157/158843397-574e2ff2-913c-4304-b3c5-ff9109219451.png)

Is it possible? I saw that you guys select which output to show, there 4 outputs of the model and only index -2 is taken (so 3 output of heatmap is used)

## **Hypothesis**
```
    stage2_heatmaps = stages_output[-2]
    heatmaps = np.transpose(stage2_heatmaps.squeeze().cpu().data.numpy(), (1, 2, 0))
    heatmaps = cv2.resize(heatmaps, (0, 0), fx=upsample_ratio, fy=upsample_ratio, interpolation=cv2.INTER_CUBIC)

    stage2_pafs = stages_output[-1]
    pafs = np.transpose(stage2_pafs.squeeze().cpu().data.numpy(), (1, 2, 0))
    pafs = cv2.resize(pafs, (0, 0), fx=upsample_ratio, fy=upsample_ratio, interpolation=cv2.INTER_CUBIC)

    return heatmaps, pafs, scale, pad
```

Is accessing the other 3 results the key to get detection of hand and smile pose ?

Thanks

**Comment by UcefMountacer** [comment]
I guess I have to train on custom dataset...I tried it but had some issues

```
RuntimeError: The size of tensor a (69) must match the size of tensor b (19) at non-singleton dimension 1
```
Is it related to checkpoint not being good for training on another number of keypoints (here 68) ? I doubt that since checkpoint path is required :D 

Is there some other parameter that should be changed ?

**Comment by Daniil-Osokin** [comment]
Hi! Yes, you need to add custom dataset and modify the model and pose parsing code correspondingly. Try to follow the [TRAIN-ON-CUSTOM-DATASET.md](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md) to get the details what need to be modified. Also #235, #237 threads may be helpful while debugging.
> RuntimeError: The size of tensor a (69) must match the size of tensor b (19) at non-singleton dimension 1
This error says (most probably), that model predicts tensor with 69 channels, but dataset produces tensor with 19 channels. So, modify dataset code to match model output.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by UcefMountacer** [comment]
Thank you, it is clear.

The guide was also really good, but I understand that there are a lot of details regarding this topic. Thanks for pointing out the fact that there is a dataset file to change too.
