### ISSUE TITLE
Integration with ROS

### ISSUE THREAD

**Issue by akamob** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#254]
Hi, Thank you for the great work.

Based on my application, I hope I can use your package as a ros topic like [this](https://github.com/ravijo/ros_openpose).

May i have your suggestions to achieve it?
Any help is much appreciated:)

**Comment by Daniil-Osokin** [comment]
Hi! It looks like a code adaptation for the ROS should be performed, e.g. creating a ROS package. I have found [this](https://github.com/ActiveIntelligentSystemsLab/pytorch_enet_ros) example, which uses `LibTorch` to run the network in ROS. Once network can be inferred, you will need a network output post-processing code. You can take it from the [C++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo).

**Comment by akamob** [comment]
Hi, thank you for your reply!

Do you mean I can use the example you mentioned to load Pre-trained model in your work? and if the .pth model loaded successfully, then I can use your C++ demo code to estimate pose?

I am sorry if that sounds trivial. I am new to ROS.
Thank you:)

**Comment by Daniil-Osokin** [comment]
C++ example contains the code, which is necessary to convert network output into poses. To run the network inference in ROS, you can check the link, which runs `LibTorch` in ROS.

**Comment by akamob** [comment]
Hi, thank you for your reply:)

I will try to achieve it. If I have some new problems then I would contact you again.

Thank you!

**Comment by Daniil-Osokin** [comment]
Great!
