### ISSUE TITLE
I meet a problem when I run Step 4.

### ISSUE THREAD

**Issue by Candy-CY** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#256]
Validation...
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 136, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "/Aistation010808/LHPE/val.py", line 127, in evaluate
    avg_heatmaps, avg_pafs = infer(net, img, scales, base_height, stride)
  File "/Aistation010808/LHPE/val.py", line 83, in infer
    height, width, _ = normed_img.shape
ValueError: not enough values to unpack (expected 3, got 1)

Hello, I am Candy，I hope you can help me solve this problem. The information above ,I meet it when I run Step 4. I choose the weight file is checkpoint_iter_40000.pth.  So the Step 4  command line is changed to 
python train.py --train-images-folder ./COCO_HOME/train2017/ --prepared-train-labels prepared_train_annotation.pkl --val-labels val_subset.json --val-images-folder ./COCO_HOME./val2017/ --checkpoint-path ./default_checkpoints/checkpoint_iter_40000.pth --weights-only --num-refinement-stages 3
I think that only changing the weight file isn't the cause of the problem, so I hope you can help me to solve it. Thank you！

**Comment by Daniil-Osokin** [comment]
Hi! I believe that something with the images path. Try the `./COCO_HOME/val2017/ ` (without the `.` after `COCO_HOME`).

**Comment by Candy-CY** [comment]
> Hi! I believe that something with the images path. Try the `./COCO_HOME/val2017/ ` (without the `.` after `COCO_HOME`).

Thank you for your reply. I think the images path is ok , I'm running the program on the school server, so the data sets path should change accordingly. I tried a method ‘Comment out the offending part of the code ’ ( train.py  from  'if num_iter % val_after == 0: '  to  'net.train() ' ). Then I ran the Step 4,  I was surprised that the program didn't fail at the previous iteration.So far, the program is still running.

**Comment by Daniil-Osokin** [comment]
Cool!

**Comment by Candy-CY** [comment]
> Cool!

(I am running Step 4) This program has been running for four days , I want to know how much will it run iteration after it stops ?  Is it 420000 or 380000 ? view the train.py code，I don't  find the variable about iteration information which you define. I hope you can help me understand this variable more clearly！Thank you !

**Comment by Daniil-Osokin** [comment]
The program will run for [280 epochs](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L76). You can get the total number of iterations by multiplying number of epochs by number of iterations per epoch.

**Comment by Candy-CY** [comment]
> The program will run for [280 epochs](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/train.py#L76). You can get the total number of iterations by multiplying number of epochs by number of iterations per epoch.

Thank you for your reply!  I followed your instructions and counted the number of iterations when it will stopped.  The step 4 is training the train2017 set. In general，the training will be stopped after iteration 420000. But after 420,000 iterations, the program is still running. The same problem occurs when I training the validation sets. ( stop after iteration 20000) . I looked at the code of train.py and didn't find any problems. I am very confused now, and I hope you can give me some suggestions to understand this project well.

**Comment by Daniil-Osokin** [comment]
Actually, the training will stop after 280 epochs. A single epoch may contain different number of iterations, according the batch size (number of dataset samples per single iteration) and the total dataset size, `num_iterations = ceil(datast_size / batch_size)`. Anyway, you may add a `break` if specific number of iterations is achieved.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
