### ISSUE TITLE
Output format problem

### ISSUE THREAD

**Issue by JessePrince** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#258]
Hi! Thanks for your great job! 
I'm trying to use the validation result to retrain the model, but the output JSON file is not exactly the same with the COCO format(image information, bbox...), the script prepare_train_model.py can't be used to convert the ouput JSON file to the .pkl file. is there any method to convert the output format to the COCO format?
Thanks a lot!

**Comment by Daniil-Osokin** [comment]
Hi! Output is in COCO format for predictions. You may try to convert it into COCO annotations format, check the official docs.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
