### ISSUE TITLE
caffe train.prototxt

### ISSUE THREAD

**Issue by zhangyunming** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#26]
hi, i have seen the deploy.prototxt in tf-lightweight openpose,  so can you give the train.prototxt of lightweight openpose in caffe， thanks

**Comment by Daniil-Osokin** [comment]
You can find one in the original Caffe [implementation](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/example_proto/pose_train_test.prototxt).

**Comment by zhangyunming** [comment]
thanks for your relpy ,  i know the train.prototxt of openpose, i want to get the train.prototxt of your lightweight openpose,can you release it?

**Comment by Daniil-Osokin** [comment]
They are the same, except network structure. So you can just copy network structure from deploy to train.

**Comment by zhangyunming** [comment]
ok，thanks
