### ISSUE TITLE
What does BODY_PARTS_PAF_IDS mean

### ISSUE THREAD

**Issue by yuan243212790** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#260]
I cannot understand what `BODY_PARTS_PAF_IDS` means, can you please help:
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/modules/keypoints.py#L7

**Comment by Daniil-Osokin** [comment]
Hi! Please check training on custom dataset guide for clarifications.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
