### ISSUE TITLE
How to use all the validation sets of coco for validation? Is the third step of training only a subset for verification?

### ISSUE THREAD

**Issue by Hans56789** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#261]
Is the third step of training only a subset for verification?
![I B})N5)_0NMA2@_W}UI7KP](https://user-images.githubusercontent.com/82496916/165874105-2b4ca32c-6bc3-4b82-aff5-5b95e53515e1.png)

**Comment by Hans56789** [comment]
![5DZ 4M7V``ZC9IQN0KNI99H](https://user-images.githubusercontent.com/82496916/165904999-88a2ec58-bbd4-41db-831c-5a1babac7af9.png)
When I input the verified terminal command, an error appears as shown in the figure. How to solve it?

**Comment by Daniil-Osokin** [comment]
Hi! I believe the path or the file with annotation for validation subset itself is wrong. Can you find `caption` key in the file with annotation for validation subset you are using?

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
