### ISSUE TITLE
loss nan

### ISSUE THREAD

**Issue by neverstoplearn** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#263]
Iter: 100
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 200
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 300
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 400
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 500
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 600
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 700
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 800
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 900
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1000
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1100
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1200
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1300
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1400
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1500
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1600
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1700
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1800
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 1900
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2000
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2100
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2200
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2300
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2400
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2500
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2600
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2700
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2800
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 2900
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3000
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3100
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3200
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3300
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3400
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3500
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3600
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3700
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3800
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 3900
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4000
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4100
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4200
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4300
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4400
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4500
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4600
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4700
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4800
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 4900
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Iter: 5000
stage1_pafs_loss:     nan
stage1_heatmaps_loss: nan
stage2_pafs_loss:     nan
stage2_heatmaps_loss: nan
Validation...
Running test for keypoints results.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 170, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 130, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "/home/zhengxin/lightweight-human-pose-estimation/val.py", line 160, in evaluate
    run_coco_eval(labels, output_name)
  File "/home/zhengxin/lightweight-human-pose-estimation/val.py", line 22, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "/home/zhengxin/anaconda3/envs/pytorch14/lib/python3.6/site-packages/pycocotools/coco.py", line 329, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

how can i fix it?

**Comment by Daniil-Osokin** [comment]
Hi! `NaN` as loss value tells that there is a problem during loss computation. Did you modify the original code?

**Comment by neverstoplearn** [comment]
> Hi! `NaN` as loss value tells that there is a problem during loss computation. Did you modify the original code?

change the batchsize fixed it. thanks.
