### ISSUE TITLE
use realtime on mobile 

### ISSUE THREAD

**Issue by mahna3411** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#264]
i use this file

Model( name='LightWeight Human Pose Estimation (ONNX)', # https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch url='https://drive.google.com/uc?export=dowload&id=1--Ij_gIzCeNA488u5TA4FqWMMdxBqOji', sha='5960f7aef233d75f8f4020be1fd911b2d93fbffc', filename='onnx/models/lightweight_pose_estimation_201912.onnx')

for get Human Pose on Mobile ! I work on a frame and it works. But I want to use it in real time How can I reduce its size or is there a file that is lighter?

**Comment by Daniil-Osokin** [comment]
Hi! You can try to decrease network input size as much as possible for your use case, e.g. try `192x144` or even smaller.

**Comment by mahna3411** [comment]
> Hi! You can try to decrease network input size as much as possible for your use case, e.g. try `192x144` or even smaller.

I did this before but it does not work, I have now found a lighter data

**Comment by Daniil-Osokin** [comment]
Great, that you have found one for your needs!
