### ISSUE TITLE
about keypoints group

### ISSUE THREAD

**Issue by chenj133** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#265]
I get a very strange result about keypoints group like the picture:
![class0](https://user-images.githubusercontent.com/55866399/172089612-0418730c-d97c-4e1e-ac37-47e8a2076deb.JPG)
the right keypoints group is inaccurate, how can I improve the group result

**Comment by Daniil-Osokin** [comment]
Hi! You can try to increase the network input resolution to avoid this. Try to pass `--height-size 1024` to the `demo.py`, it might help to some extent.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
