### ISSUE TITLE
Meaning of Confidence values

### ISSUE THREAD

**Issue by NomiMalik0207** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#267]
In coco dataset joints with zero values are always be like (0,0,2).
Can you please where you are using confidence value of (x,y,1) and (x,y,0).
What is the difference b/w confidence value=1 and 2?

**Comment by NomiMalik0207** [comment]
reorder_map = [1, 7, 9, 11, 6, 8, 10, 13, 15, 17, 12, 14, 16, 3, 2, 5, 4]
I believe, you change this order according to OpenPose. As zero is nose in orignal COCO, you didnt mention zero in this ordering. Can you explain a little?

**Comment by Daniil-Osokin** [comment]
For code adjustment to a custom dataset, please check [TRAIN-ON-CUSTOM-DATASET.md](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md).

**Comment by NomiMalik0207** [comment]
BTW, I am following all the settings provided in mentioned file :( . 
Couldnt find the answer of my question from that file.

**Comment by Daniil-Osokin** [comment]
What is the problem you are solving? You may use any keypoints order you like in your project. COCO has 17 keypoints, OpenPose rearranges them and adds one more - neck. For compatibility with the original OpenPose order we have preserved this rearrangement.

**Comment by NomiMalik0207** [comment]
Thank You alot. I have tained your model foer MPII and it is working fine.
