### ISSUE TITLE
BODY_PART_PAF_IDS

### ISSUE THREAD

**Issue by leftbackn3** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#270]
I have a query related to how to define BODY_PARTS_PAF_ID for custom dataset?

I referred to TRAIN_ON_CUSTOM_DATA documentation.

BODY_PART_PAF_ID list seems to be a list of list where individual list in the list contains two corresponding indices. Does the order of the indices matter? Here for 18 keypoints it is defined as-
([12, 13], [20, 21], [14, 15], [16, 17], [22, 23], [24, 25], [0, 1], [2, 3], [4, 5],
                      [6, 7], [8, 9], [10, 11], [28, 29], [30, 31], [34, 35], [32, 33], [36, 37], [18, 19], [26, 27])

if [20,21] came before [12,13], will that affect the result? In case if I just made this list in sequence like [0,1][1,2]..to [36,37], will that have an effect on the result as well?

**Comment by Daniil-Osokin** [comment]
Hi! In general you may use any ordering. They are also specify the order in which body parts will be [grouped together](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md#how-persons-keypoints-are-grouped-into-instances). It makes sense to start from the most confident part, e.g. neck, and connect everything to it. You need to assemble somehow keypoints into persons. If you start from left shoulder-elbow part, it will allocate data for the new person. Then if you next proceed with the right  shoulder-elbow (part which is not connected directly with left elbow), it will also allocate data for the new person. You will need to merge two data arrays together into one persons after that. If you instead will start from the neck and add next parts sequentially, where the next part is connected with previous, you will not need to merge different pieces of data for the same person.

**Comment by leftbackn3** [comment]
Yes, in BODY_PARTS_KPT_IDs we are starting from the neck [1, 2], [1, 5], [2, 3]..starting from the neck and then gradually proceeding to other parts 1 to2 2 to 3 and so on.

However in BODY_PART_PAF_IDS the first value is [12,13]. As per definition, 12 13 are network indices of the output of the corresponding keypoint pairs. The first two keypoint pairs are [1,2] and [1,5]. How are these two pairs related to the indices [12,13]? Is there something in the model architecture that plays a part in the BODY_PART_PAF_ID definition?

**Comment by Daniil-Osokin** [comment]
As defined. For keypoints pair 1 and 2, the corresponding PAF maps in the output PAF tensor are with the indices 12 (dx) and 13 (dy). The same rule for the next keypoints pair 1 and 5, for them the corresponding PAF maps in the output PAF tensor are with the indices 20 (dx) and 21 (dy).

**Comment by leftbackn3** [comment]
Okay this is how we are defining them. This aspect is clear.

Why does ./modules/keypoints.py and ./dataset/coco.py have different ordering for BODY_PART_KPT_IDS definition?

Will they be the same or there is a reason behind this difference?

**Comment by Daniil-Osokin** [comment]
They have the consistency between arrays, but just the different order. It is a legacy.

**Comment by leftbackn3** [comment]
Thanks a lot for the clarifications.
