### ISSUE TITLE
What is "processed_other_annotations" in processed file for training?

### ISSUE THREAD

**Issue by NomiMalik0207** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#271]
After using 'prepared train labels.py', in the new generated file we have a list named as 'processed_other_annotations", What is the purpose of this annotation? for custom dataset, in which we donot have info like segmentation, obj_pose etc. How to generate these annotations?

**Comment by Daniil-Osokin** [comment]
To train for keypoints prediction, you need a keypoints for all persons inside the input image. "Other annotations" contain other persons keypoints inside the image, as you can see in the code or with doing the debug visualization. This code uses specific augmentation, which makes each person centered in the image and has specific height. Other persons, which exist in the image, just add their keypoints. You are free to not use such augmentation and just make random crops inside the given image. Do not hesitate to check the issues of this repo, they already have useful tips.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
