### ISSUE TITLE
Coordinates with respect to bone points

### ISSUE THREAD

**Issue by james525-wq** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#272]
Hello, can you output the coordinate position of the skeleton

**Comment by Daniil-Osokin** [comment]
Hi! You can get the coordinates of each persons keypoints from [keypoints](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L59) array of person.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
