### ISSUE TITLE
Meet problem in coco.py line120

### ISSUE THREAD

**Issue by Candy-CY** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#273]
Hello again, I'm Candy! Now I meet some problems in code and hope you can give me  some methods to solve it.
These days,  I am trying a new keypoints model (eg. openpose contains 18 keypoints), now I want to add some new keypoints base on it , so I hope my model can recongnize 22 keypoints in total, but based on your code, I have changed the essential information about  keypoints list (BODY_PARTS_KPT_IDS) in the code、 the code of PAF list (BODY_PARTS_PAF_IDS) and add some weight parameters about these. 
About the dataset, we use the dataset which is labeled by our team and change its type same as coco, but the code is still not to go, the wrong infomation as follow: 
datasets/coco.py", line 120, in _generate_paf_maps
    keypoint_a = label['keypoints'][BODY_PARTS_KPT_IDS[paf_idx][0]]
TypeError: list indices must be integers or slices, not float
Since this is a newly defined model about keypoints, I think I must have some mistakes in the process of modifying your code.
I hope you can give me some suggestions about creating new model based on your code, so that I can quickly solve the problem and reproduce my model based on your code.
Thank you again! Wish you all the best in your work and happy everyday！

**Comment by Daniil-Osokin** [comment]
Hi! The error is general to Python not the pose estimation code. It tells that one of your list indices, possibly the `paf_idx` is `float`, but has to be the integer. So, you can either use `int(paf_idx)` instead, or check why `paf_idx` is `float`. In general, you need o extend the [arrays](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md#what-is-body_parts_kpt_ids-and-body_parts_paf_ids) with new keypoints pair and modify keypoint heatmaps generation code to support more keypoints.

**Comment by Candy-CY** [comment]
Thank you for your reply! Recently, I debug the 120 code line and find the list about the paf_idx value, even the list about keypoints value is not wrong , so I am confused about this problem. I also extend the list of BODY_PARTS_KPT_IDS、BODY_PARTS_PAF_IDS and the sigma value about PAF maps, but also get same wrong in this code line. 
I didn't understand the process about keypoint heatmaps generation code in this program every well. I hope you can give me a general explanation about  the keypoint heatmaps generation.
Thank you again! Wish you all the best in your work and happy everyday！

**Comment by Candy-CY** [comment]
Ok,Thank you again ! If I have any questions later, I hope you can help me to slove them !

**Comment by Candy-CY** [comment]
Hi, Dan！After the train.py and the val.py code has been modified, our dataset can now be used in the model for training, and obtained some .pth files. I thought it meant the model had been successfully trained, when I run the demo.py to the model, I found that the test images or the vedio have no labeled information after passing the code, I was very confused to get this result. What do you think have made this happen? dataset or the code ? 
Thank you ! Waiting for your reply!

**Comment by Daniil-Osokin** [comment]
Hi! You can check one of closed issues in this repository for debugging tips, e.g. #235. The first thing to try is to overfit during training on small dataset, e.g. 4 or 16 images without augmenations. If loss has decreased significantly, then it is time to train on bigger dataset, then check accuracy on validation dataset. Since you have trained model, you can visualize its heatmaps to see if keypoints are predicted at proper place (where person has it).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
