### ISSUE TITLE
Steps needed to run model on TensorRT

### ISSUE THREAD

**Issue by mrgiba** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#275]
Hello,

I successfully used this model a while ago on a server, and now I'd like to see how to test it out on a Jetson Nano device. 

Looking at similar issues for the 3D model (like [issue-41](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/issues/41) and [issue-78](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/issues/78)), I see that some code changes have been added to support conversion of the model to TensorRT, and I also noticed that demo code has different a flow for the TensorRT use case. Is all that also needed for the 2D model ?

Thanks

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by janezlapajne** [comment]
Hello, how many FPS could you achieve by using this network on Jetson Nano? Thanks! 😃
