### ISSUE TITLE
Fine Tuning query

### ISSUE THREAD

**Issue by leftbackn3** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#277]
HI,

I am fine tuning checkpoints_370000.pth

Shall I keep the num_refinements_stages value as 3? or use the default value as mentioned in train.py?

**Comment by Daniil-Osokin** [comment]
More refinements stages give you more refinement. You can choose any number, that suits or your needs,

**Comment by leftbackn3** [comment]
Thank You @Daniil-Osokin
