### ISSUE TITLE
Custom Dataset Annotation format

### ISSUE THREAD

**Issue by JJLimmm** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#278]
Hi,

I have a few questions after reading the tips and issues pointed out here.
I am currently using Labelme to annotate the keypoints and would convert them to the COCO format later on. 

1. What if my custom dataset only has keypoints annotated?

2. If i have the 18 keypoints like shown in the image below,  where can i change the keypoint definitions in this repo to match my usage?  
![pose_estimation_keypoints](https://user-images.githubusercontent.com/79782049/183330002-bd95bdf1-41b3-4e1f-9611-67606cbfbf2d.png)

3. And for Validation of the model, are other metrics available like PCK, PCP ([more info](https://github.com/cbsudux/Human-Pose-Estimation-101#evaluation-metrics))? Would i be able to use your validation metrics with just keypoints in my GTs?

Thanks!

_Originally posted by @JJLimmm in https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/231#issuecomment-1207600173_

**Comment by Daniil-Osokin** [comment]
Hi! It is ok, you can convert this format to COCO annotation format. Just throw away the neck and reorder keypoints as in COCO dataset, you can check #134 or the official COCO site for the COCO keypoints order. You can check additional [metric](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch/blob/master/modules/calc_pckh.py) in the neighborhood repository. It has the code for a single-person pose estimation.

**Comment by Daniil-Osokin** [comment]
To use the code without modifications, you need to convert the data to COCO format. You can take just bounding box around person keypoints. Segmentation, masks are not necessary, check the #231.

**Comment by JJLimmm** [comment]
I see, so i can do without segmentation masks, but i would still require bounding boxes with my keypoints, so as to use it with COCO's evaluation metrics.

**Comment by Daniil-Osokin** [comment]
Great, that it is clear now!
