### ISSUE TITLE
paf_masks

### ISSUE THREAD

**Issue by XiaoJiNu** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#279]
Hi, there are some questions about paf_masks?
1. what is paf_masks?
2. why we use paf_masks in l2_loss function?
3. I guess that paf_masks is used for selecting paf area so that paf loss is only  calculated with paf area, is it right?

**Comment by Daniil-Osokin** [comment]
Hi! Will #231 help to get the details about masks usage?

**Comment by XiaoJiNu** [comment]
Very clear ! Thank you very much! @Daniil-Osokin

**Comment by Daniil-Osokin** [comment]
Great!
