### ISSUE TITLE
Keypoint IDs

### ISSUE THREAD

**Issue by prashant-bansod** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#28]
@Daniil-Osokin   I got the pose coordinates using `convert_to_coco_format`. I am not sure about the the pose coordiantes mapping.  Is it like the following? 
```
"keypoints": {
        0: "nose",
        1: "left_eye",
        2: "right_eye",
        3: "left_ear",
        4: "right_ear",
        5: "left_shoulder",
        6: "right_shoulder",
        7: "left_elbow",
        8: "right_elbow",
        9: "left_wrist",
        10: "right_wrist",
        11: "left_hip",
        12: "right_hip",
        13: "left_knee",
        14: "right_knee",
        15: "left_ankle",
        16: "right_ankle"
    },
```

**Comment by Daniil-Osokin** [comment]
This function outputs keypoints in [COCO](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-coco) format.

**Comment by prashant-bansod** [comment]
@Daniil-Osokin Thanks for your response. I am getting the pose coordinates in  the following format. 
`[[96.5, 19.5, 0, 0, 96.5, 18.5, 0, 0, 93.5, 17.5, 84.5, 24.5, 92.5, 26.5, 82.5, 34.5, 101.5, 34.5, 0, 0, 109.5, 33.5, 84.5, 45.5, 90.5, 46.5, 85.5, 59.5, 90.5, 60.5, 82.5, 72.5, 90.5, 73.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]` 
In this I am not considering the presence of the keypoint( just the coordiates) . 

I am trying to get the coordinates in the following format. 
`[[196.  40.]
 [180.  54.]
 [184.  56.]
 [192.  84.]
 [210.  80.]
 [174.  54.]
 [186.  78.]
 [202.  82.]
 [188. 102.]
 [188. 134.]
 [182. 164.]
 [178. 102.]
 [178. 130.]
 [176. 158.]
 [196.  38.]
 [ nan  nan]
 [190.  38.]
`
I am a bit confused with the `val.py`.I tried changing `the `convert_coco_format( )` but did not succeed to get this format. Am I looking at the right function ?

**Comment by Daniil-Osokin** [comment]
`convert_to_coco_format` returns list of pose keypoints for each found person (size: num_persons x (17*3)), where pose keypoints is a list of keypoints (size: 17 * 3), and each keypoint is represented as 3 numbers: x, y - keypoint coordinates and 3<sup>rd</sup> - its visibility. So you can just create numpy array `formatted_poses = numpy.zeros(shape=(num_persons, 17, 2), dtype=numpy.float32)` and set to proper position keypoints coordinates from the list, something like this: 
`for person_id in range(len(coco_keypoints)):`
&nbsp;&nbsp;&nbsp;&nbsp;`for keypoint_id in range(17):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`keypoint_coordinates = coco_keypoints[person_id][keypoint_id * 3:(keypoint_id * 3 + 2)]`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`if coco_keypoints[person_id][keypoint_id * 3 + 2] == 0:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`keypoint_coordinates = [numpy.nan, numpy.nan]`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`formatted_poses[person_id, keypoint_id] = keypoint_coordinates`

**Comment by prashant-bansod** [comment]
Thanks a lot for the detailed answer @Dannil-Osokin.   I tried implementing your code but it is giving me `Nan` values only.  I tried to tweak your github code a bit. Like this
```
coco_keypoints = []
scores = [] 
for n in range(len(pose_entries)):
        if len(pose_entries[n]) == 0:
            continue
        
        keypoints = np.zeros((17,2),dtype=np.float32)
        to_coco_map = [0, -1, 6, 8, 10, 5, 7, 9, 12, 14, 16, 11, 13, 15, 2, 1, 4, 3]
        person_score = pose_entries[n][-2]
        position_id = -1
        for keypoint_id in pose_entries[n][:-2]:
            position_id += 1
            if position_id == 1:  # no 'neck' in COCO
                continue
            cx, cy, score = 0, 0, 0 # keypoint not found

            #cx, cy, score, visibility = 0, 0, 0, 0  # keypoint not found
            if keypoint_id != -1:
                cx, cy, score = all_keypoints[int(keypoint_id), 0:3]
                cx = cx + 0.5
                cy = cy + 0.5
                #visibility = 1

            keypoints[to_coco_map[position_id]][0] = cx
            keypoints[to_coco_map[position_id]][1] = cy
            
            
            #newArray = np.append(keypoints,[cx,cy],axis = 0)
            # B = np.int32(keypoints[to_coco_map[position_id], 0])
            # A = np.int32(keypoints[to_coco_map[position_id], 1])
            #(keypoints[to_coco_map[position_id] * 2 + 0],keypoints[to_coco_map[position_id] * 2 + 1])=cx,cy
            #keypoints[to_coco_map[position_id] * 3 + 2] = visibility
        #coco_keypoints.append(keypoints)
        # scores.append(person_score * max(0, (pose_entries[n][-1] - 1)))  # -1 for 'neck'
        # print(type(coco_keypoints))
        return keypoints
```
This one is giving me the desired output. I am  unsure whether my appoach is right .

**Comment by Daniil-Osokin** [comment]
Looks ok, great that it works.
