### ISSUE TITLE
报“WARNING”

### ISSUE THREAD

**Issue by xieyifeng** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#280]
请问训练过程中出现以下问题是什么原因
'''
[WARNING] Not found pre-trained parameters for model.0.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.1.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.1.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.2.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.2.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.3.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.3.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.4.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.4.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.5.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.5.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.6.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.6.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.7.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.7.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.8.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.8.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.9.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.9.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.10.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.10.4.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.11.1.num_batches_tracked
[WARNING] Not found pre-trained parameters for model.11.4.num_batches_tracked
'''

**Comment by Daniil-Osokin** [comment]
Hi! Will #70 help?

**Comment by xieyifeng** [comment]
> Hi! Will #70 help?
Thanks, this solves my problem well.

**Comment by Daniil-Osokin** [comment]
Great, closing!
