### ISSUE TITLE
Can I estimate only single person?

### ISSUE THREAD

**Issue by reflelia** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#281]
Can I extract only 1 person's keypoint?

**Comment by Daniil-Osokin** [comment]
Hi! You can use only pose with the highest [confidence](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L24).

**Comment by reflelia** [comment]
Thank you! it works very well
But If I want to extract single person's keypoints heatmap, I need to fix network architecture?

**Comment by Daniil-Osokin** [comment]
You can leave network architecture as is. However for this task you need just annotations for 1 person in dataset. You can assign an empty list in the [label['processed_other_annotations']](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/datasets/coco.py#L83) for this.

**Comment by reflelia** [comment]
Can I just delete below lines in coco.py and run train.py?
`for another_annotation in label['processed_other_annotations']:
                keypoint = another_annotation['keypoints'][keypoint_idx]
                if keypoint[2] <= 1:
                    self._add_gaussian(keypoint_maps[keypoint_idx], keypoint[0], keypoint[1], self._stride, self._sigma)`
` for another_annotation in label['processed_other_annotations']:
                keypoint_a = another_annotation['keypoints'][BODY_PARTS_KPT_IDS[paf_idx][0]]
                keypoint_b = another_annotation['keypoints'][BODY_PARTS_KPT_IDS[paf_idx][1]]
                if keypoint_a[2] <= 1 and keypoint_b[2] <= 1:
                    self._set_paf(paf_maps[paf_idx * 2:paf_idx * 2 + 2],
                                  keypoint_a[0], keypoint_a[1], keypoint_b[0], keypoint_b[1],
                                  self._stride, self._paf_thickness)`

**Comment by Daniil-Osokin** [comment]
Yes, you can.

**Comment by reflelia** [comment]
Ok, I try it. Thank You!

**Comment by Daniil-Osokin** [comment]
Ok, closing.
