### ISSUE TITLE
why square video more slower than 16:9 video

### ISSUE THREAD

**Issue by reflelia** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#282]
I tested two videos 
One of video is 720 x 720
And another one is 1280 x 720
Also, I Croped 1280 x 720 to 720 x 720
But large one is faster than small one

How can I solve it?

**Comment by Daniil-Osokin** [comment]
Hi! This looks strange. Input video is [resized](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L59) to have height 256 by default with the same aspect ratio. You may try to profile, which pat of the pipeline: data preparation, network inference, results post-processing is started to take more time.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
