### ISSUE TITLE
The processing time of extract_keypoints

### ISSUE THREAD

**Issue by isshpan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#284]
Hi, thanks for the good job!I run this demo on my 2080Ti, the fps  is 20. The net inference is fast. I found that the extract_keypoints function takes me almost the whole time. Could you tell me how I can improve it? Maybe I can enduce some loss of accuracy, just for speed up. Thanks a lot!

**Comment by isshpan** [comment]
Thanks for your help!But I have tried to resize, maybe it does not make sense.My goal is to get the data (x, y, score) realtime in my python code, then I will use the data to do more things in PyTorch. Can I use the python demo to inference，and call the C++ function to get the extract result，then use python to do the next. Does this work? Thanks !

**Comment by Daniil-Osokin** [comment]
Yes, you can. This will require some engineering on your side, however I have posted the links to the C++ implementation which might help.

**Comment by isshpan** [comment]
Thanks! By the way, the fast c++ code inference can reach? Can it reach 60fps or more than it?

**Comment by Daniil-Osokin** [comment]
It depends on CPU power. I believe these FPS is possible if you will resize network output to relatively small size, e.g. 128 or 256 pixels height.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
