### ISSUE TITLE
Can I use this in my research work?

### ISSUE THREAD

**Issue by littleJeffrey** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#285]
Hi, Mr. Daniil
    I found your code is amazing. I want to use your code as a part of my research. I tried to send you an e-mail but it failed. How can I contact you. I will tell you the detail of my research. Thanks!

**Comment by Daniil-Osokin** [comment]
Hi! If it is ok, you can post you question here.

**Comment by littleJeffrey** [comment]
Thank you for the reply! Here's my request. I'm a master's student. My research is to enhance the student behavior classification accuracy in the classroom on embedded systems. The point of my research is classification. I need a lightweight skeleton extraction method. After searching, I found that Mr. Daniil's research is the most powerful. So, can I use your lightweight OpenPose research as the lightweight skeleton extraction method in my research? I will introduce Mr. Daniil's method in my research and quote Mr. Daniil's paper and github in my reference. Thank you for your kind cooperation. Have a nice day!

**Comment by Daniil-Osokin** [comment]
I am ok if you will use it in your research.
