### ISSUE TITLE
key point coordinates

### ISSUE THREAD

**Issue by ywqly** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#286]
Why do I output only 17 keypoint coordinates

**Comment by Daniil-Osokin** [comment]
Hi! The output keypoints correpond to [this format](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md#pose-output-format-coco).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
