### ISSUE TITLE
Modifying val.py for custom dataset

### ISSUE THREAD

**Issue by dtkutzke** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#287]
Does the validation code need to be modified to accommodate custom dataset keypoints? It looks like it needs significant modification, since it's dependent on COCO keypoints. For reference, I'm working with 6 keypoints, and 12 PAFs. I've tried to modify the validation code but to no avail.

**Comment by Daniil-Osokin** [comment]
Hi! Some modifications are definitely needed: convert your annotations in COCO format, adjust number of pafs and heatmaps and delete conversion from internal model keypoints order to COCO format.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
