### ISSUE TITLE
keypoint

### ISSUE THREAD

**Issue by 15154278491** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#288]
Hi, I have a question about how to print the human keypoints information.

**Comment by Daniil-Osokin** [comment]
Hi! You can get them by accessing [`keypoints`](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L23) field of the `Pose` class.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.

**Comment by 15154278491** [comment]
> Hope, it is helped.

Thank you very much.
