### ISSUE TITLE
demo question

### ISSUE THREAD

**Issue by sulei1998** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#289]
Thanks for yout great work! When i run the demo, i meet some problem.

I use the gpu to run the model, but it is very very slow.

Like this:

![image](https://user-images.githubusercontent.com/56378342/205430769-19acda28-0650-4500-b9cd-71e8bf6c911d.png)

When i use the cpu, it seems very fast. It makes me confused. Could you give me some advise?

In Ubuntu20.04, and the package info is as follows:

![image](https://user-images.githubusercontent.com/56378342/205430864-f8346e51-1414-4f11-8260-48eb8e20e390.png)

**Comment by Daniil-Osokin** [comment]
Hi! How did you noticed, that running with gpu were slower, than with cpu? In general for the first run (or on a single image), the gpu is needed to be initialized (takes some time), then weights are needed to be copied into gpu memory (also takes some time). There are no such costs for running with cpu.

**Comment by sulei1998** [comment]
> 

Because it cost 10 or more minutes to run when i use the gpu. It is normal?

**Comment by Daniil-Osokin** [comment]
I mean in which part of the pipeline you have measured the time? If you run on just 1 image - this is ok.

**Comment by sulei1998** [comment]
Ok, thank you for your explanation, i just test on 1 image and find it is slow.
