### ISSUE TITLE
something wrong about visualize dataset

### ISSUE THREAD

**Issue by lexuszhi1990** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#29]
When I visualize the dataset, use you code, I found some keypoints in picture  are misleading, e.g.

![sample-vis-kp-kp-ori-with-lines](https://user-images.githubusercontent.com/548467/58525406-39a06500-81fe-11e9-945f-466fbeed3a4f.png)

the image info is: 
{'img_paths': '000000181542.jpg', 'img_width': 640, 'img_height': 600, 'objpos': [590.4, 256.405], 'image_id': 181542}

the reason is, the man's left shoulder is marked as "not in image", so the stat number is 2, and right sholder is visualizable, so the stat number is 0, according the [code](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/a6e41cf56e0b5e2d23686de9ef15671833bdb72e/datasets/transformations.py#L40-L46)

```
converted_keypoints.insert(1, [(keypoints[5][0] + keypoints[6][0]) / 2,
                               (keypoints[5][1] + keypoints[6][1]) / 2, 0])  # Add neck as a mean of shoulders
if keypoints[5][2] == 2 and keypoints[6][2] == 2:
    converted_keypoints[1][2] = 2
elif keypoints[5][2] == 3 and keypoints[6][2] == 3:
    converted_keypoints[1][2] = 3
elif keypoints[5][2] == 1 and keypoints[6][2] == 1:
    converted_keypoints[1][2] = 1
if (converted_keypoints[1][0] < 0
        or converted_keypoints[1][0] >= w
        or converted_keypoints[1][1] < 0
        or converted_keypoints[1][1] >= h):
    converted_keypoints[1][2] = 2
```

`converted_keypoints[1][1]` is > 0 and `converted_keypoints[1][1]` is between [0, h], so finally it will insert a neck as state number 0. I change the code as blow and it works just it is:

```
converted_keypoints.insert(1, [(keypoints[5][0] + keypoints[6][0]) / 2,
                               (keypoints[5][1] + keypoints[6][1]) / 2, 1])  # Add neck as a mean of shoulders
if keypoints[5][2] == 2 or keypoints[6][2] == 2:
    converted_keypoints[1][2] = 2
elif keypoints[5][2] == 0 and keypoints[6][2] == 0:
    converted_keypoints[1][2] = 0
```

**Comment by Daniil-Osokin** [comment]
Thanks for the report! Need some time to check it.

**Comment by DHU-th** [comment]
which one should i use?

**Comment by Daniil-Osokin** [comment]
Hi! I have reproduced this, thanks again! Will retrain model and check if this affects numbers, then merge #64.

**Comment by lexuszhi1990** [comment]
you're welcome, looking forward your new model and new results

**Comment by Daniil-Osokin** [comment]
I've got 38.6% AP. It is similar to base model, so no need to update weights. Merged, thanks!
