### ISSUE TITLE
The coco dataset contains 17 key points Why can your model identify 18 key points.

### ISSUE THREAD

**Issue by liudadan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#292]
The coco dataset contains 17 key points Why can your model identify 18 key points.

**Comment by Daniil-Osokin** [comment]
Hi! The extra `neck` keypoint is placed in the middle of the left and right shoulders.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
