### ISSUE TITLE
OSError: Video 0 cannot be opened

### ISSUE THREAD

**Issue by leonhard-yu-zhang** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#297]
Hello,

I want to run this demo on intel realsense camera D455. My PC is equipped with 3 external cameras:

Intel(R) RealSense(TM) Depth Ca (usb-0000:44:00.3-2.1.4):
	/dev/video12
	/dev/video13
	/dev/video14
	/dev/video15
	/dev/video16
	/dev/video17
	/dev/media4
	/dev/media5

Intel(R) RealSense(TM) Depth Ca (usb-0000:44:00.3-2.2.4):
	/dev/video6
	/dev/video7
	/dev/video8
	/dev/video9
	/dev/video10
	/dev/video11
	/dev/media2
	/dev/media3

Intel(R) RealSense(TM) Depth Ca (usb-0000:44:00.3-2.3):
	/dev/video0
	/dev/video1
	/dev/video2
	/dev/video3
	/dev/video4
	/dev/video5
	/dev/media0
	/dev/media1

When I run "python demo.py --model human-pose-estimation-3d.pth --video 0", there is an error: "OSError: Video 0 cannot be opened".

How could I solve it?

Thanks.

**Comment by Daniil-Osokin** [comment]
Hi! You may try other camera ids, i.e. pass `--video 1` or `2`.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
