### ISSUE TITLE
Where is CocoTrainDataSet (Dataset) called__ getitem__ (self, idx) function

### ISSUE THREAD

**Issue by liudadan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#298]
Where is CocoTrainDataSet (Dataset) called__ getitem__ (self, idx) function。
I found that CocoTrainDataSet did not directly call__ getitem__ Function, but directly obtain data in the iterative process of training. images = batch_ data['image'].cuda()。 So__ getitem__ When was the function called?

**Comment by Daniil-Osokin** [comment]
Hi! It is called internally by Python, when you access elements of dataset, e.g. `dataset[2]`. In this code it happens, when you perform iterations, i.e. `for batch_data in train_loader`. You may try to read the [PyTorch example](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html) to get the details.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
