### ISSUE TITLE
How to change the number of downsample?

### ISSUE THREAD

**Issue by sulei1998** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#299]
Hi, i notice that you said "One more way to improve the accuracy is to increase network output resolution (and retrain): now it downsamples input 8 times, the most of other models downsamples input just 4 times." But i do not find a parameter to change the number of downsample. Could you give me some advice?

**Comment by Daniil-Osokin** [comment]
Hi! There is no special parameter for it. You can modify network architecture manually, e.g. set `stride=1` in some convolution with `stride=2` and set `dilation=2` for next convolutional layer. This is what we did in the paper with some layers.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
