### ISSUE TITLE
about inference time in crowed scene

### ISSUE THREAD

**Issue by lianuo** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#3]
@Daniil-Osokin Thanks for your works 
when I check the inference time, and in a  crowed scene with up to 30 or more person the speed is very slow

net forward ->0.06s
extract_keypoints->0.10s
group_keypoints->2.4s

is it possible to optimize the  group_keypoints and extract_keypoints on GPU?
Thanks~

**Comment by Daniil-Osokin** [comment]
Hi!
Guess you've ran python demo. It was added just for results preview, not the speed measurements, and I believe some optimizations are possible, need some time to profile it. For now you may try heavily optimized [c++](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo) demo.

**Comment by lianuo** [comment]
@Daniil-Osokin Thank you~
