### ISSUE TITLE
Why scale the mask size? Does this damage the label information and cause the model accuracy to drop?

### ISSUE THREAD

**Issue by liudadan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#301]
Why scale the mask size? Does this damage the label information and cause the model accuracy to drop?

        mask = cv2.resize(sample['mask'], dsize=None, fx=1/self._stride, fy=1/self._stride, interpolation=cv2.INTER_AREA)

**Comment by Daniil-Osokin** [comment]
Hi! The mask should be scaled together with the image to correspond the same regions.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
