### ISSUE TITLE
The size of pictures during training is [3, 368, 368], and the size of pictures during verification is not uniform. Why unify the picture size during training. Why not unify the image size when verifying.

### ISSUE THREAD

**Issue by liudadan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#302]
The size of pictures during training is [3, 368, 368], and the size of pictures during verification is not uniform. Why unify the picture size during training. Why not unify the image size when verifying.

**Comment by Daniil-Osokin** [comment]
Hi! Will #171 help?

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
