### ISSUE TITLE
Help me!! object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

### ISSUE THREAD

**Issue by YOOHYOJEONG** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#303]
Hi, was trying to training coco keypoint dataset in the order written on this link(https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#training 
).
When I was trying to validation the model during training(train.py --train-images-folder <COCO_HOME>/train2017/ --prepared-train-labels prepared_train_annotation.pkl --val-labels val_subset.json --val-images-folder <COCO_HOME>/val2017/ --checkpoint-path <path_to>/mobilenet_sgd_68.848.pth.tar --from-mobilenet) using coco keypoint dataset, it says like this :

Traceback (most recent call last):
  File "train.py", line 167, in <module>
    train(args.prepared_train_labels, args.train_images_folder, args.num_refinement_stages, args.base_lr, args.batch_size,
  File "train.py", line 130, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "/workspace/lightweight_openpose/val.py", line 160, in evaluate
    run_coco_eval(labels, output_name)
  File "/workspace/lightweight_openpose/val.py", line 24, in run_coco_eval
    result = COCOeval(coco_gt, coco_dt, annotation_type)
  File "/workspace/env-light_openpose/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/workspace/env-light_openpose/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 529, in __init__
    self.setKpParams()
  File "/workspace/env-light_openpose/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 518, in setKpParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 200, in linspace
  File "/workspace/env-light_openpose/lib/python3.8/site-packages/numpy/core/function_base.py", line 121, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer 

This is my python venv spec :
RTX 3090, ubuntu 18.04, torch=1.8.2+cu111, torchaudio=0.8.2, torchvision=0.9.2+cu11
python=3.8
matplotlib=3.6.3
numpy=1.24.2
opencv-python=4.7.0.68
pycocotools=2.0.0
wheel=0.38.4

Since we judged that the problem is caused by the version of numpy,
I tried to downgraded the numpy version to 1.7 by referring to this( https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/70 ).

But, The numpy 1.7 version does not match the matplotlib 3.6.3 version.
And,  When I run python train.py --train-images-folder <COCO_HOME>/train2017/ --prepared-train-labels prepared_train_annotation.pkl --val-labels val_subset.json --val-images-folder <COCO_HOME>/val2017/ --checkpoint-path <path_to>/mobilenet_sgd_68.848.pth.tar --from-mobilenet
after downgraded the version of matplotlib that matches the numpy version, the following error occurs :
**valueerror: numpy.ndarray size changed, may indicate binary incompatibility. expected 96 from c header, got 80 from pyobject**

OR

**valueerror: numpy.ndarray size changed, may indicate binary incompatibility. expected 96 from c header, got 88 from pyobject**

I'm using python venv instead of conda env. Is this the problem?
Do I have to use a cond environment?
What can I do?

Help me...

Thank you.

**Comment by YOOHYOJEONG** [comment]
Wow !!!!
Thanks to you, I solved it.

Thank you very much!!!!!!!!!!!!!!!!!!!!!!

**Comment by Daniil-Osokin** [comment]
Great!
