### ISSUE TITLE
Errors encountered during validation. Nothing is written in the detections.json file.

### ISSUE THREAD

**Issue by YOOHYOJEONG** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#304]
Hi, Thank you very much for your help last time.
I need your help because I faced another error.

- 1
I want to train my custom dataset(with a different number of keypoints than the coco). So, I followed this link(https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md) and modified the code to fit my custom dataset.
But, I encountered the following error at the verification stage :

```
Validation...
Running test for keypoints results.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    train(args.prepared_train_labels, args.train_images_folder, args.num_refinement_stages, args.base_lr, args.batch_size,
  File "train.py", line 134, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "/workspace/lightweight_openpose/val.py", line 174, in evaluate
    run_coco_eval(labels, output_name)
  File "/workspace/lightweight_openpose/val.py", line 22, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "/workspace/env-light_openpose/lib/python3.8/site-packages/pycocotools/coco.py", line 329, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
```
      
     

My custom dataset have 6 num keypoints. 
So, I checked following this link(https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/197) : 

```python
def evaluate(labels, output_name, images_folder, net, multiscale=False, visualize=False):
    net = net.cuda().eval()
    base_height = 368
    scales = [1]
    if multiscale:
        scales = [0.5, 1.0, 1.5, 2.0]
    stride = 8
    dataset = CocoValDataset(labels, images_folder)
    coco_result = []
    for sample in dataset:
        # file_name = sample['file_name']
        img = sample['img']

        avg_heatmaps, avg_pafs = infer(net, img, scales, base_height, stride)

        total_keypoints_num = 0
        all_keypoints_by_type = []
        # for kpt_idx in range(18):  # 19th for bg
        for kpt_idx in range(6):
            total_keypoints_num += extract_keypoints(avg_heatmaps[:, :, kpt_idx], all_keypoints_by_type, total_keypoints_num)
            print("TOTAL KEYPOINTS NUM : ", total_keypoints_num)

        pose_entries, all_keypoints = group_keypoints(all_keypoints_by_type, avg_pafs)
        
        print("pose_entries length", len(pose_entries))
        print("all_keypoints_by_type length: ", len(all_keypoints_by_type))
        print("avg_pafs length ", len(avg_pafs))

        coco_keypoints, scores = convert_to_coco_format(pose_entries, all_keypoints)
        
        print("RESULT KEYPOINTS : ", coco_keypoints, "SCORES : ", scores)

        # image_id = int(file_name[0:file_name.rfind('.')])
        image_id = sample['image_id']
        for idx in range(len(coco_keypoints)):
            coco_result.append({
                'image_id': image_id,
                'category_id': 1,  # person
                'keypoints': coco_keypoints[idx],
                'score': scores[idx]
            })

        print("coco results length : ", len(coco_result))
        print("========================================")

        if visualize:
            for keypoints in coco_keypoints:
                for idx in range(len(keypoints) // 3):
                    cv2.circle(img, (int(keypoints[idx * 3]), int(keypoints[idx * 3 + 1])),
                               3, (255, 0, 255), -1)
            cv2.imshow('keypoints', img)
            key = cv2.waitKey()
            if key == 27:  # esc
                return

    with open(output_name, 'w') as f:
        json.dump(coco_result, f, indent=4)

    run_coco_eval(labels, output_name)
```

***output:***   
```
TOTAL KEYPOINTS NUM :  0
TOTAL KEYPOINTS NUM :  0
TOTAL KEYPOINTS NUM :  1
TOTAL KEYPOINTS NUM :  1
TOTAL KEYPOINTS NUM :  1
TOTAL KEYPOINTS NUM :  1
pose_entries length 0
all_keypoints_by_type length:  6
avg_pafs length  1080
RESULT KEYPOINTS :  [] SCORES :  []
coco results length :  0
```
and + errors

Is there any part that I corrected wrong?

   
   
- 2
Also, nothing is recorded in the detections.json file during training. So my detections.json file is an empty file.
Is this the cause of the error?
I don't know why nothing is recorded in the detections.json file. When does the detections.json file become an empty file?
What exactly is the role of the detections.json file? 
   
  
    
- 3
Last, Why was keypoint[2] used like "keypoint[2]==1:visible and ==2:not in image" at datasets/transformations.py(https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/datasets/transformations.py#L12)?
coco keypoint docs(https://cocodataset.org/#format-data:~:text=v%3D0%3A%20not%20labeled%20(in%20which%20case%20x%3Dy%3D0)%2C%20v%3D1%3A%20labeled%20but%20not%20visible%2C%20and%20v%3D2%3A%20labeled%20and%20visible) says "v=0: not labeled (in which case x=y=0), v=1: labeled but not visible, and v=2: labeled and visible".
   
   
   
Thank you.

**Comment by Daniil-Osokin** [comment]
Hi! `detections.json` is a file, which stores detections from all images. If it is empty, it is likely training goes wrong, the model just does not predict any persons. I suggest to visualize input image and target heatmaps, are they looks consistent to each other. If not, this might be a reason of not trained model.

**Comment by YOOHYOJEONG** [comment]
Thank you for your reply.
I will check input image and target heatmaps.


And, Can I get an answer to the last question?

I use custom data sets labeled "v=0: not labeled (in which case x=y=0), v=1: labeled but not visible, and v=2: labeled and visible" according to the Coco document(https://cocodataset.org/#format-data:~:text=v%3D0%3A%20not%20labeled%20(in%20which%20case%20x%3Dy%3D0)%2C%20v%3D1%3A%20labeled%20but%20not%20visible%2C%20and%20v%3D2%3A%20labeled%20and%20visible),
but I wonder why they use it as "keypoint[2]==1:visible and ==2:not in image" in datasets/transformations.py(

[lightweight-human-pose-estimation.pytorch/datasets/transformations.py](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/datasets/transformations.py#L12)

Line 12 in [1590929](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/commit/1590929b601535def07ead5522f05e5096c1b6ac)

 for keypoint in keypoints:  # keypoint[2] == 0: occluded, == 1: visible, == 2: not in image 
)?

Does this affect learning?

**Comment by YOOHYOJEONG** [comment]
Thank you. 
I'll try. I'll try to bring good news.

Thank you for your kind reply every time.

**Comment by YOOHYOJEONG** [comment]
I'm sorry for leaving a question again when I was closing this issue.

I tried to visualize the heat map and the following results are.

```python
    net = DataParallel(net).cuda()
    net.train()
    for epochId in range(current_epoch, 280):
        scheduler.step()
        total_losses = [0, 0] * (num_refinement_stages + 1)  # heatmaps loss, paf loss per stage
        batch_per_iter_idx = 0
        for batch_data in train_loader:
            if batch_per_iter_idx == 0:
                optimizer.zero_grad()

            images = batch_data['image'].cuda()
            keypoint_masks = batch_data['keypoint_mask'].cuda()
            paf_masks = batch_data['paf_mask'].cuda()
            keypoint_maps = batch_data['keypoint_maps'].cuda()
            paf_maps = batch_data['paf_maps'].cuda()

            tmp_img = images.squeeze().permute(1,2,0).cpu().numpy()
            tmp_img = np.uint8(255*tmp_img)
            tmp_img = cv2.resize(tmp_img, (500, 500))
            
            tmp_heat = keypoint_maps.squeeze().permute(1,2,0).cpu().numpy()
            tmp_heat = np.uint8(255*tmp_heat)

            heat_img = cv2.applyColorMap(tmp_heat[-1], cv2.COLORMAP_JET)
            heat_img = cv2.resize(heat_img, (500,500))
            
            keypoint_mask = keypoint_masks.squeeze().permute(1,2,0).cpu().numpy()
            keypoint_mask = np.uint8(255*keypoint_mask)

            keypoint = cv2.applyColorMap(keypoint_mask[-1], cv2.COLORMAP_JET)
            keypoint = cv2.resize(keypoint, (500,500))
            keypoint = cv2.cvtColor(keypoint, cv2.COLOR_BGR2GRAY)
            
            heatmap_img = cv2.addWeighted(heat_img, 0.7, tmp_img, 0.3, 0)
            final_img = cv2.copyTo(tmp_img, keypoint, tmp_img)
            cv2.imwrite('/workspace/lightweight_openpose/data/heatmaps/keypoint_mask.png', final_img)
            cv2.imwrite('/workspace/lightweight_openpose/data/heatmaps/heatmap.png', heatmap_img)
```


keypoint heatmap + input image result(keypoint_mask.png) :
![image](https://user-images.githubusercontent.com/86641457/221497948-5630789b-fb37-4525-9f07-669bdf76775e.png)

keypoint mask + input image result(heatmap.png) : 
![image](https://user-images.githubusercontent.com/86641457/221497994-af8b14dd-2f3f-42b4-8256-a03c0ddfee10.png)

   
   

And,  To get the target heat map, I modified [val.py ](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/val.py#L113) as follows :

```python

def evaluate(labels, output_name, images_folder, net, multiscale=False, visualize=False):
    net = net.cuda().eval()
    base_height = 368
    scales = [1]
    if multiscale:
        scales = [0.5, 1.0, 1.5, 2.0]
    stride = 8

    dataset = CocoValDataset(labels, images_folder)
    coco_result = []
    for sample in dataset:
        file_name = sample['file_name']
        img = sample['img']
        tmp_img = img.copy()
        tmp_img = cv2.resize(tmp_img, (500, 500))

        avg_heatmaps, avg_pafs = infer(net, img, scales, base_height, stride)
        avg_heatmap = avg_heatmaps.copy()
        avg_heatmap = np.uint8(255*avg_heatmap)
        heat_img = cv2.applyColorMap(avg_heatmap[-1], cv2.COLORMAP_JET)
        heat_img = cv2.resize(heat_img, (500, 500))

        final_img = cv2.addWeighted(heat_img, 0.8, tmp_img, 0.2, 0)
        cv2.imwrite('/workspace/lightweight_openpose/data/heatmaps/val_heatmap.png', final_img)
```

target heatmap(val_heatmap.png) :
![image](https://user-images.githubusercontent.com/86641457/221498234-de0e43f0-c7fd-4584-b283-66267fc7e12a.png)

   
   
I knew intuitively that this result I got was a mess. 😭😥😢
Does this result mean that the model is not properly trained?

**Comment by Daniil-Osokin** [comment]
Think so. It seems, that target data was not properly prepared (with a proper target data you should have heatmap peaks at pigs keypoints locations). Suggest to check keypoints coordinates transformation to heatmap peaks. BTW, for visualization during training, suggest to add a loop over batch:
```
for batch_id, tmp_img in enumerate(images.data.cpu().numpy()):
    tmp_img = (tmp_im * 256 + 128).transpose((1, 2, 0)).astype(np.uint8)
    background_heatmap = batch_data['keypoint_maps'][batch_id, -1]
    cv2.imshow('input image', tmp_img)
    cv2.imshow('1 - heatmaps', background_heatmap)
    cv2.waitKey()
    and so on...
```

**Comment by YOOHYOJEONG** [comment]
It hasn't been long since I started studying, so I'm very immature.
Therefore, your answer is very helpful to me.
Thank you VERY MUCH.   
   

Thanks to your kind reply, I was able to check the keypoint heatmap as follows:
![image](https://user-images.githubusercontent.com/86641457/221787925-106dae94-bfe5-4f61-9c1a-e265f58acc28.png)   
   
   
What I'm most curious about is how to modify [this](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/val.py#L52) when the number of keypoints is less than coco.

I think I need to modify [that part](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/1590929b601535def07ead5522f05e5096c1b6ac/val.py#L52) for evaluation, is that right?

**Comment by Daniil-Osokin** [comment]
For correct metric computation, you just need to store keypoints in the [COCO format](https://cocodataset.org/#format-data). I believe it might be great to check [keypoints grouping](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/TRAIN-ON-CUSTOM-DATASET.md#how-persons-keypoints-are-grouped-into-instances) code once again. It may be the reason of empty predictions, if predicted heatmaps are reasonable.

**Comment by YOOHYOJEONG** [comment]
Thank you very much for your kind reply.
It helped me a lot.

**Comment by xin4431** [comment]
Hello, excuse me. I have the same problem as you. How did you solve it?

**Comment by YOOHYOJEONG** [comment]
@xin4431 
Hi, I had a problem with my dataset. detections.json was empty because the model did not learn properly and could not detect any objects during the verification process.
When I visualized heatmap, the heatmap came out badly and I decided that the model was not learning my dataset properly.
