### ISSUE TITLE
The problem of estimating keypoint of wrist

### ISSUE THREAD

**Issue by BigMouthFlower** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#309]
Thank you for such a great work. I use the pre-trained model 'checkpoint_iter_370000.pth'. Everythin goes well, but a problem occured when it estimate the wrist. If I horizontally stretch my arm, the model will unable to find my wrist. Why this happends?
Here are 2 examples. Parts in red circle is the lost of wrist.
![image](https://user-images.githubusercontent.com/63338220/232795046-c126a30a-b14e-41f7-9ac1-9eef80824a44.png)
![image](https://user-images.githubusercontent.com/63338220/232795073-ca7a7569-7f3f-4fcd-a65a-2d83405fc4c0.png)

**Comment by Daniil-Osokin** [comment]
Hi! This might be likely out of domain images, e.g. not similar to the training set. You can improve network performance by fine-tuning on the target data.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.

**Comment by BigMouthFlower** [comment]
> Hope, it is helped.

thanks a lot, I think its because of the difference between training set an target data as you say. Fortunately, it doesnt ignore the key point all the time. Its more likely 'shaking'. For some frame, the model can get all key points correctly. So for application, I can set a threshold for frame. Only continuous frame losing the specific key point will be counted as a changing. After setting the threshold, my application can run properly most time.
Thanks your model and reply again!
