### ISSUE TITLE
use the code on another dataset

### ISSUE THREAD

**Issue by pordeli** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#31]
I have used Openpose on my images. I want to try this code too and compare the results. What are the steps to do it and is it possible?

**Comment by Daniil-Osokin** [comment]
I would suggest to start with [python demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#python-demo). It [parses](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L112) results into [Pose](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L7),  which can be used further. If you want to compare how method is fast, please consider [c++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo).

**Comment by Daniil-Osokin** [comment]
Hope, it helps.
