### ISSUE TITLE
How to solve the occlusion problem during human tracking

### ISSUE THREAD

**Issue by liudadan** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#310]
Hello dear author, I used your code for human tracking and found that it is affected by occlusion. Is there a method that is efficient and agrees to an effective tracking algorithm to solve this problem in case of occlusion.

**Comment by Daniil-Osokin** [comment]
Hi! If you need more than [built-in tracker](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L77), you may try [OC-SORT](https://github.com/noahcao/OC_SORT) for that.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
