### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by ywqly** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#313]
Hello, I am using a custom data set for training. My data set has the same 17 key points as the coco format, but it has the following errors,
Running test for keypoints results.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 130, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "D:\lightweight-human-pose-estimation.pytorch-master\val.py", line 160, in evaluate
    run_coco_eval(labels, output_name)
  File "D:\lightweight-human-pose-estimation.pytorch-master\val.py", line 22, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\pycocotools\coco.py", line 324, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by Daniil-Osokin** [comment]
Hi! Try to compare coco keypoints annotation file structure with your annotation file, this can help with debugging.

**Comment by ywqly** [comment]
I want to use the quick verification method, but it has the following error, I don't think this is very important, but I don't understand why the code reads it
Traceback (most recent call last):
  File "scripts/make_val_subset.py", line 35, in <module>
    'licenses': data['licenses'],
KeyError: 'licenses'

**Comment by Daniil-Osokin** [comment]
Just add necessary key (`licenses`) into the dictionary with an empty list value.

**Comment by ywqly** [comment]
Thank you for your reply, I solved this problem but the result it got is very strange, the verification result is all 0, and then the same error occurs again
Validation...
Running test for keypoints results.
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
DONE (t=0.03s).
Accumulating evaluation results...
DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.000
Iter: 500
stage1_pafs_loss:     8.76414207458496
stage1_heatmaps_loss: 2.8462799644470214
stage2_pafs_loss:     8.299758377075195
stage2_heatmaps_loss: 2.5582490158081055
Iter: 600
stage1_pafs_loss:     10.326668319702149
stage1_heatmaps_loss: 3.335077877044678
stage2_pafs_loss:     9.55616424560547
stage2_heatmaps_loss: 2.945261993408203
Validation...
Running test for keypoints results.
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    args.checkpoint_after, args.val_after)
  File "train.py", line 130, in train
    evaluate(val_labels, val_output_name, val_images_folder, net)
  File "D:\lightweight-human-pose-estimation.pytorch-master\val.py", line 160, in evaluate
    run_coco_eval(labels, output_name)
  File "D:\lightweight-human-pose-estimation.pytorch-master\val.py", line 22, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\pycocotools\coco.py", line 324, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by Daniil-Osokin** [comment]
Now error says, that something is wrong with detection file. Does it correspond to the [keypoint detection results format](https://cocodataset.org/#format-results)?

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.

**Comment by xin4431** [comment]
Hello, I have the same problem, how did you solve it? Thank you
