### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by ywqly** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#314]
May I ask how to calculate fps in python.demo.py of 2D human pose estimation

**Comment by ywqly** [comment]
Thank you for your reply. I would like to ask how to measure the fps of this code. I tried many methods and got an error.

**Comment by Daniil-Osokin** [comment]
Just use [this code](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L120) to compute fps.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
