### ISSUE TITLE
I also encountered this ：problem:AssertionError: Results do not correspond to current coco set！

### ISSUE THREAD

**Issue by xin4431** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#316]
Hi, @Daniil-Osokin 
I'm training a personal data set of 20 key points,
But I met the same problem with him[#313](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/313)
```
Traceback (most recent call last):
  File "D:/Deep learning/lightweight_openpose/val.py", line 211, in <module>
    evaluate(labels, output_name, images_folder, net, args.multiscale, visualize=True)
  File "D:/Deep learning/lightweight_openpose/val.py", line 188, in evaluate
    run_coco_eval(labels, output_name)                               
  File "D:/Deep learning/lightweight_openpose/val.py", line 23, in run_coco_eval
    coco_dt = coco_gt.loadRes(dt_file_path)
  File "D:\ProgramData\Anaconda3\envs\byte\lib\site-packages\pycocotools-2.0-py3.8-win-amd64.egg\pycocotools\coco.py", line 324, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
```
I did the following experiment using a picture
In [val.py](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py), I modify the code in `convert_to_coco_forma`t like this：
```
        keypoints = [0] * 20 * 3   
        to_coco_map = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```
The resulting` detections.json` content is shown below:
![image](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/assets/99191183/9938b29d-50e9-4f10-9a6f-e1b521fe6367)
My val_label.json format is as follows:
![image](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/assets/99191183/667f69fc-c780-402d-ad41-c39f66ee1235)
Can you tell me where my problem is?
I am very much looking forward to your answer. The existence of this problem prevents me from evaluating my model

**Comment by Daniil-Osokin** [comment]
Great, that it works!
