### ISSUE TITLE
Why does the ap drop when Dilated MobileNet v2 is used?

### ISSUE THREAD

**Issue by xin4431** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#317]
Dilated MobileNet v1 was used to deepen the network depth, enlarge the receptive field, and improve ap.

![image](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/assets/99191183/92c5b5bd-38b4-451a-9408-d27b5495c60d)

But why does the ap drop when Dilated MobileNet v2 is used? Won't the depth of the network improve the accuracy?
If I use ResNet-50 as backbone, will the accuracy be improved?

**Comment by Daniil-Osokin** [comment]
Hi! This is an area of research. Our experiments did not give good results with MobileNetV2 out of the box. However one may use MobileNetV2 and get better (or worse) results. ResNet-50 is also a good network, so worth trying. The purpose of this work is to achieve real-time speed on CPU for pose estimation, while maintain comparable to OpenPose baseline accuracy. With ResNet accuracy may be higher, but the inference speed may be lower, so it is a trade-off.

**Comment by xin4431** [comment]
Thank you for your answer
