### ISSUE TITLE
Evaluation metrics 

### ISSUE THREAD

**Issue by sathishram12** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#318]
I am bit confused about oks metrics evaluation of openpose models. If am understanding is right we trained vgg or mobilenet model with fixed shape and evaluating the model by dynamic multi scale values right?. Why not fixed model size lets say 368X368. I am bit confused here. In official paper they mentioned 60% of AP. Did they used actual input image size or model input image size to get that output

**Comment by Daniil-Osokin** [comment]
These method runs on the whole image (bottom-up approach). Image is resized by the shortest side to fixed dimension with saving initial image aspect ratio to have reasonable persons proportions (that is why not using 368x368 resolution for all input images). To get 60% of AP they do multi-scale inference and also flip the image, then average the results from all scales and flips.

**Comment by sathishram12** [comment]
Thanks a lot. It helps me a lot on evaluating my model performance
