### ISSUE TITLE
the model not giving straight skeleton

### ISSUE THREAD

**Issue by Nimaro76** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#320]
Hello, 

I used your model with D435I camera. however, the skeleton in 3D will not remain straight when I go further away from the camera . it is like it gets rotated slightly. can you please guide me whether you encountered the same issue ? thank you for your help

**Comment by Daniil-Osokin** [comment]
Hi! This repository provides pose estimation in 2D coordinates. So looks like this problem somewhere inside the code, which  transforms into 3D. To have proper visualization you need to find intrinsics and extrinsics of your camera and use them for proper transform in 3D space (if you just append `z` coordinate to 2D coordinates).

**Comment by Nimaro76** [comment]
Hello, sorry for the confusion, I mean this repository :https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch  which is also yours . I tried it and the 3D skeleton is not straight

**Comment by Daniil-Osokin** [comment]
You can still try the suggestion:
> To have proper visualization you need to find intrinsics and extrinsics of your camera and use them for proper transform in 3D space (if you just append z coordinate to 2D coordinates).

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
