### ISSUE TITLE
change the size of the input of the network

### ISSUE THREAD

**Issue by WalterSenpai** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#321]
Hi Daniil-Osokin

I was wondering if I could change the size of input image in val.py without any problems in keypoints. I changed the network into a fixed size which only accept inputs of  1000 x 1000. Right now, I encountered problem with the method infer in line 116, val.py. I can't change the input of the network into a fixed size. Can you help me with that?

Thank you 
@Daniil-Osokin

**Comment by Daniil-Osokin** [comment]
Hi! You can use `demo.py` passing `--height_size 1000` parameter or add `height_size` parameter [logic](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L145) to the val script.

**Comment by WalterSenpai** [comment]
alright, thank you so much!
