### ISSUE TITLE
heat maps vs. confidence maps

### ISSUE THREAD

**Issue by ywqly** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#322]
How to visualize heat maps vs. confidence maps

**Comment by Daniil-Osokin** [comment]
Hi! Heatmap and confidence map is the same thing. You can call `cv2.imshow` directly with heatmap array or normalize it to 0-1 range before.

**Comment by Daniil-Osokin** [comment]
You may follow #235 thread, it has such code for visualization.
