### ISSUE TITLE
Train on custom dataset question

### ISSUE THREAD

**Issue by cyhsien** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#324]
Hello, I need help training a custom dataset using the coco-annotator. However, the keypoint format of the tool is different from the coco dataset, which is causing issues with training. Can you offer any solutions?

![螢幕擷取畫面 2024-01-02 113733](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/assets/155410024/55a931f9-654d-490c-8df1-1e4f9736414e)
![螢幕擷取畫面 2024-01-02 113459](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/assets/155410024/60d1c4ee-4ad4-46f7-a170-f86f6424cc20)

**Comment by Daniil-Osokin** [comment]
Hi! I expect, that `coco-annotator` should directly dump annotation in COCO format, as they mention in the [README](https://github.com/jsbroks/coco-annotator?tab=readme-ov-file#features). If something went wrong, you may try to convert obtained annotation to COCO format, using the [official format description](https://cocodataset.org/#format-data).

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
