### ISSUE TITLE
Lines

### ISSUE THREAD

**Issue by ywqly** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#326]
Hello author, how to make the lines detected by the pose thicker

**Comment by Daniil-Osokin** [comment]
Hi! You can increase line thickness from `2` to `4` [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L62).

**Comment by Daniil-Osokin** [comment]
Hope, it is helped
