### ISSUE TITLE
C++ demo

### ISSUE THREAD

**Issue by JuanF2019** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#327]
The provided instructions for running the C++ demo no longer works as the link returns 404. I found out with this link:

https://docs.openvino.ai/2024/omz_demos_human_pose_estimation_demo_cpp.html

That demo is provided via Open Model Zoo at demos/human_pose_estimation_demo:

https://github.com/openvinotoolkit/open_model_zoo/tree/master

Could you please update the instructions on README?

**Comment by Daniil-Osokin** [comment]
Hi! Thanks, updated in #328
