### ISSUE TITLE
can't download pretrained model

### ISSUE THREAD

**Issue by Panshangka** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#34]

**Comment by Daniil-Osokin** [comment]
Navigate to [pre-trained model](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#pre-trained-model) section, make right click on the link, select save link as and download starts.

**Comment by Panshangka** [comment]
Thanks, by the way, I want to transfer the pretrained model to caffe using microsoft mmdnn, but the pretrained model is just the weight file which is not supported. So is there another solution for this?

**Comment by Daniil-Osokin** [comment]
In the [pre-trained model](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#pre-trained-model) section there is description, how to convert this checkpoint to ONNX. And ONNX can be read with mmdnn.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
