### ISSUE TITLE
About net structure

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#35]
@Daniil-Osokin 
Q1: Does cpm in the network mean Convolutional Pose Machines?
Q2: Where did cpm idea come from?It seems like that it's very important for result
Q3: In #27, ELU was talked.Is it a good idea using ELU in InitialStage and RefinementStage?  Because , in InitialStage, BN is not used.In RefinementStage,some layers have no BN after ReLU.

**Comment by Daniil-Osokin** [comment]
Hi, `cpm` means Convolutional Pose Machines, in the code this just the name for additional layers to adopt features of backbone for pose estimation. I believe using `ELU` is a good idea to tackle `dead neurons` problem, and as it was discussed in #27 in this code this is a legacy to reproduce the paper results. Absence of BN in some layers is also legacy, we've released new [code](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch) for single-person pose estimation with more BNs.

**Comment by MoonBunnyZZZ** [comment]
> Hi, `cpm` means Convolutional Pose Machines, in the code this just the name for additional layers to adopt features of backbone for pose estimation. I believe using `ELU` is a good idea to tackle `dead neurons` problem, and as it was discussed in #27 in this code this is a legacy to reproduce the paper results. Absence of BN in some layers is also legacy, we've released new [code](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch) for single-person pose estimation with more BNs.

Thank you  for your reply.I will enjoy your new work.

**Comment by MoonBunnyZZZ** [comment]
> Hi, `cpm` means Convolutional Pose Machines, in the code this just the name for additional layers to adopt features of backbone for pose estimation. I believe using `ELU` is a good idea to tackle `dead neurons` problem, and as it was discussed in #27 in this code this is a legacy to reproduce the paper results. Absence of BN in some layers is also legacy, we've released new [code](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch) for single-person pose estimation with more BNs.

Did you ever test ELU in gccpm-look-into-person-cvpr19.pytorch?

**Comment by Daniil-Osokin** [comment]
No, it was not the purpose there.

**Comment by MoonBunnyZZZ** [comment]
> No, it was not the purpose there.

In your opinion, if using mobilenet v3 as backbone, which one layer to truncate？

**Comment by Daniil-Osokin** [comment]
By default, try to reuse all features, except classifier. Just add dilations and remove strides to save spatial resolution (have heatmaps and pafs 8 times smaller than input image).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
