### ISSUE TITLE
Points information

### ISSUE THREAD

**Issue by yustinaivanova** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#36]
Thank You, @Daniil-Osokin , for your awesome work! I would like to ask, are there any explanations about the human points? In which order do they go in detection?
Thank You!

**Comment by Daniil-Osokin** [comment]
Hi, you can check the order [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L9), or:

![OpenPose order](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/media/keypoints_pose_18.png)

**Comment by Daniil-Osokin** [comment]
Hope, its clear now.

**Comment by yustiks** [comment]
Thank You, @Daniil-Osokin , for the clarification. Just another small question:
what is the 18th point in the list of pose entries?
```
 "pose_entries": [
        [
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            3.0,
            6.0,
            7.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            -1.0,
            1.5556692151419864,
            3.0
        ]
```

**Comment by Daniil-Osokin** [comment]
It is right ear.

**Comment by yustiks** [comment]
@Daniil-Osokin are You sure? all the other points are number for a point in an array of points. And this element is a float number.

**Comment by Daniil-Osokin** [comment]
18th element in the list is right ear, and element by 18th index is pose confidence. We've described output format [here](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/human_pose_estimation#output-format).

**Comment by yustiks** [comment]
@Daniil-Osokin Thank You very much!

**Comment by tangfayuan** [comment]
> 18th element in the list is right ear, and element by 18th index is pose confidence. We've described output format [here](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/human_pose_estimation#output-format).

**Comment by tangfayuan** [comment]
> 
> 
> 18th element in the list is right ear, and element by 18th index is pose confidence. We've described output format [here](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/human_pose_estimation#output-format).

Links can not be opened,
Can you resend that?  Thanks.

**Comment by Daniil-Osokin** [comment]
[This one](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L9) works.
