### ISSUE TITLE
Are there any hand keypoints model？

### ISSUE THREAD

**Issue by gd2016229035** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#38]
Great Job! 
Are there any Hand keypoints detection model in your code just like open pose?
Thank you~

**Comment by Daniil-Osokin** [comment]
Hi, we didn't make a hand keypoints model.

**Comment by systemcorp-ai** [comment]
from [https://github.com/Hzzone/pytorch-openpose] : https://www.dropbox.com/sh/7xbup2qsn7vvjxo/AABWFksdlgOMXR_r5v3RwKRYa?dl=0
