### ISSUE TITLE
less than 1 fps speed on cpu without using openvino toolkit

### ISSUE THREAD

**Issue by lucky630** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#39]
i am getting less than 1 fps speed on cpu (Core™ i7-6850K) by using the pretrained model without using openvino toolkit. but in the paper it was mentioned that the speed would be 26 fps.so, why there is so much performance drop.

i am using the checkpoint_iter_370000.pth pretrained model.

**Comment by Daniil-Osokin** [comment]
Please, use [c++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo) for the fastest inference.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
