### ISSUE TITLE
Conversion from Coco Keypoints to Open pose ?

### ISSUE THREAD

**Issue by timtensor** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#41]
Hi Is there a script or something similar to convert coco keypoints with `(x1,y,1,c1, ....x17,y17,c17)` format where `x,y` are co-ordinates and `c` is the confidence score .

**Comment by Daniil-Osokin** [comment]
Hi, conversion to COCO format is [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L136).

**Comment by timtensor** [comment]
Thank you , just to understand correctly , what does the input parameter `pose_entries` imply ? And the second argument `all_keypoints` is it a vector or a list of size `1x51` in the following order  `[x1,y1,c1,x2,y2,c2,x3,y3,c3,.....x17,y17,c17] `where `x1 ` and `y1`  are the cartesian co-ordinates and c1 is the confidence score ??

**Comment by Daniil-Osokin** [comment]
`all_keypoints` is an array of all found keypoints, each entry is keypoint coords, it's id and score.
`pose_entries` is a list of found poses, each pose consist of keypoints ids from `all_keypoints` array.
You need `coco_keypoints` list, which is returned from function `convert_to_coco_format`, each entry (found pose) is 51 elements array with keypoints in COCO format.

**Comment by timtensor** [comment]
Thank you , I am trying to convert 2d detector `hrnet` into the coco keypoints of `open pose`. If i want to do it for single person does `pose_entries` = 1 . For the keypoints, I have an array which i can convert into the list of 51 points which as you mentioned should be of the format `[x1,y,1,x2,y2,...x17,y17,c1,c2,...c7]` where `x,y` are cartesian coordinates and `c` are pose scores ?

**Comment by Daniil-Osokin** [comment]
COCO format is a 51 element array with cartesian coordinates and keypoint score for each keypoint.

**Comment by timtensor** [comment]
Hi i could output the , coco 51 element array as suggested , above. I am doing `single person` pose estimation . I am a bit confused what parameter does `pose_entries` stand for ??  To check it manually i had put `pose_entries` to 1 ( as it is single person) which throws an error. Perhaps I am wrong in it ??

**Comment by Daniil-Osokin** [comment]
`pose_entries` is a list of found poses, each pose consist of keypoints ids from `all_keypoints` array. If algo didn't find any pose, tis list will be empty, or, if algo find more than one pose, the length will be equal to number of found poses.

**Comment by timtensor** [comment]
Hi , thanks for the explanation . I am trying to use `posenet` as a 2d detector , and convert the 2d keypoints to the `open pose coco `format.`Posenet` outputs in the  `coco_format` list as mentioned above per frame `[x1,y,c1,x2,y2,c2,.... x17,y17,c17]]` . This is for single person , pose estimation. How can i use the above mentioned fucntion , as there there is no mention of `pose entries` which is used as a input argument here.

**Comment by Daniil-Osokin** [comment]
What are you going to achieve?

**Comment by timtensor** [comment]
Hi , what i have is a set of` COCO keypoints` that is extracted per frame per second with `x,y` cartesian co-ordinates and `c` as confidence score for each joints. I wanted to convert each of these `COCO keypoints` into `Open Pose COCO keypoints` per frame per second and compare the differences

**Comment by Daniil-Osokin** [comment]
If you want to convert keypoints from MS COCO into OpenPose format, just rearrage them, according to OpenPose [order](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-coco). Neck can be obtained as the middle between left and right shoulders.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
