### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by mathblue** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#42]
Hi, I tried to train the net with a custom dataset created with coco-annotator (https://github.com/jsbroks/coco-annotator) but the function CocoTrainDataset inside coco.py doesn't return anything (len(dataset) is 0 after dataset=CocoTrainDataset(...)).
Any help?
Anyway is it actually possible to train that model on custom datasets (with fewer keypoints maybe) ?
Thanks

**Comment by Daniil-Osokin** [comment]
If you have data in MS COCO format, you can follow [training](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#training) paragraph to train the model. Training on a dataset with different number of keypoints is possible, however you will need to understand and modify the code.

**Comment by mathblue** [comment]
Ok thank you for replying, I managed to train it with 18 keypoints custom dataset but for other numbers do I even have to change the model layers?

**Comment by mathblue** [comment]
Thank you for replying, I managed to train it on my custom dataset with fewer keypoints but I can't understand the purpose of the "sigmas" array in pose.py and how to set BODY_PARTS_PAF_IDS if I have fewer keypoints.
(When I pass some images for inference only 2 keypoints are connected and the bbox is too small and maybe is due to my bad numbers in "sigmas" and in BODY_PARTS_PAF_IDS)
Thanks again

**Comment by mathblue** [comment]
Another thing, I am using google colab because I don't have gpu on my computer but it seems that during training the gpu usage is 0

**Comment by Daniil-Osokin** [comment]
We use them for tracking persons id in video (between frames), see [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L16) and [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L64).

**Comment by mathblue** [comment]
thanks!

**Comment by edwardnguyen1705** [comment]
Hi @mathblue ,
Have you successfully completed the training and inference on your custom dataset? Could you share steps how to do that? Thank you very much.

**Comment by mathblue** [comment]
Hi, yes I've been able to train that code on any custom dataset modifying
actually few things, I can change the number of keypoints and use Coco
annotator to annotate new images. I don't know why but I didn't always get
excellent results but anyway not bed results.
I'm happy to share the way I did it, I remember that I even wrote a small
tutorial where I explain it. It's quite a lot of time since I worked on
those things but as soon as I'll have a bit of time I'll put the things
together and I'll send you the documentation.

Il giorno sab 6 giu 2020 alle ore 17:28 Thanh (Edward) Nguyen <
notifications@github.com> ha scritto:

**Comment by edwardnguyen1705** [comment]
Hi @mathblue ,
Thank you for your time. I am really curious and interested in your work, especially training the model on a subset of keypoints. I am looking forward to your tutorial.

**Comment by mathblue** [comment]
All right, i should have put everything needed to run the code in this repository, I hope the description is clear enough!
https://github.com/mathblue/Custom-Pose-Estimation-Yaw-Roll-Pitch-detection-tensorrt-compilation

**Comment by edwardnguyen1705** [comment]
Hi @mathblue ,
Thank you so much!

**Comment by edwardnguyen1705** [comment]
Hi @Daniil-Osokin ,
Could you explain a little bit about the `ConvertKeypoints` class?
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/a52ab66b77f788cf9619857a4956f82c50e276be/datasets/transformations.py#L7

Especially, these two lines:
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/411ff9fd5f6125e1879cb73f6b4f90090184edad/datasets/transformations.py#L38
and
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/411ff9fd5f6125e1879cb73f6b4f90090184edad/datasets/transformations.py#L41
I guess `keypoints[5] and keypoints[6]` are not shoulders?

**Comment by Daniil-Osokin** [comment]
Hi, it converts `keypoints` which contains keypoints in COCO order to `converted_keypoints` in internal order (just remapping and addition of neck keypoint). Shoulders are correspond to the 5th and 6th indices in [original COCO annotation](http://cocodataset.org/#keypoints-eval).

**Comment by edwardnguyen1705** [comment]
Hi @Daniil-Osokin ,
Thank you. You're right: the COCO order
` "keypoints": ["nose","left_eye","right_eye","left_ear","right_ear","left_shoulder","right_shoulder","left_elbow","right_elbow","left_wrist","right_wrist","left_hip","right_hip","left_knee","right_knee","left_ankle","right_ankle"]`
