### ISSUE TITLE
the version of requirements

### ISSUE THREAD

**Issue by EasonGZY** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#43]
hi, I saw the requirements are "torch==0.4.1
torchvision==0.2.1
pycocotools==2.0.0
opencv-python==3.4.0.14
numpy==1.14.0" I think they are a little bit old. And when I tried to run the 'pip install -r requirements.txt' I get ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.0.14 
I have already installed the torch 1.2.0, torchvision 0.3.0 pycocotools 2.0.0,  
and opencv-python 4.1.0.25, dose that version work?
thanks!

**Comment by Daniil-Osokin** [comment]
It will work. Thanks, we may relax requirements with `>=` condition.

**Comment by Daniil-Osokin** [comment]
Thanks, #47
