### ISSUE TITLE
training step

### ISSUE THREAD

**Issue by myOpenCV** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#46]
Hi:
   all,
   when I follow the traing steps, in the step 3, I run the training codes, there are no errors, however, the code has stayed in this screen for more than 10 hours, there is no other print information, has anyone ever met this situation?
   thanks!
![QQ截图20191009094122](https://user-images.githubusercontent.com/18274241/66445358-1671a600-ea79-11e9-82bb-d74a64a63dfe.png)

**Comment by Daniil-Osokin** [comment]
Hi, I don't see network training progress here. It looks like something wrong with dataset, do you use MS COCO and converted it to internal format accordingly (described in [step 2](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#training))? Here you validate network, which does not train enough (or at all). So heatmap output is totally wrong, and keypoints groupping has just too many candidates to group, thats why validation takes so long. Suggest to check the dataset.

**Comment by myOpenCV** [comment]
> Hi, I don't see network training progress here. It looks like something wrong with dataset, do you use MS COCO and converted it to internal format accordingly (described in [step 2](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#training))? Here you validate network, which does not train enough (or at all). So heatmap output is totally wrong, and keypoints groupping has just too many candidates to group, thats why validation takes so long. Suggest to check the dataset.

Hi, thanks for your response, follow your advice, I check the dataset and the code worked.
thanks a lot.
