### ISSUE TITLE
What is AP?

### ISSUE THREAD

**Issue by mirth** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#49]
Does it correspond to `Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ]`?

**Comment by Daniil-Osokin** [comment]
AP is the Average Precision metric, [defined](http://cocodataset.org/#keypoints-eval) for evaluation on MS COCO dataset. It's corresponds to `AP at OKS=.50:.05:.95` (the first line in the evaluation output).
