### ISSUE TITLE
Matching Parts to Pose

### ISSUE THREAD

**Issue by mengkeat** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#52]
When matching the body parts to form the human pose, the pose_entry in modules/keypoints.py does not seem to be merged. Is it possible for the parts to be assembled such that two pose_entry is actually from the same person and that when adding in a part, it then becomes necessary to merge the 2 pose_entry together ?

**Comment by Daniil-Osokin** [comment]
This may happen, the [requirement](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/keypoints.py#L197) for pose entry is to have at least 3 keypoints and has score bigger than a threshold. So it is possible to have two entries: left leg and right hand, which belong to the same person.

**Comment by mengkeat** [comment]
Thanks for clarification. I guess that the merge is not done because it was not required as long as the poses are rendered ? As in it is not because of some other technical/scientific reason ?

**Comment by Daniil-Osokin** [comment]
Because this happens not very often.

**Comment by mengkeat** [comment]
Thanks again.
