### ISSUE TITLE
Average Precision on OpenVINO

### ISSUE THREAD

**Issue by mirth** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#53]
Have you performed validation run for model that have been converted to OpenVINO?

**Comment by Daniil-Osokin** [comment]
All models, which available publicly through OpenVINO, passed accuracy check (see [accuracy checker](https://github.com/opencv/open_model_zoo/tree/master/tools/accuracy_checker) for the details). The accuracy should be the same.
