### ISSUE TITLE
About the heatmap and paf value

### ISSUE THREAD

**Issue by fh520** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#55]
hi, thanks for your nice work, but i still have some questions about the code.
1). keypoint_map[map_y, map_x] += math.exp(-exponent)
As mentioned in the original paper, it takes maximun of the confidence maps, but in the code, it takes sum of the confidence maps.  So I wonder why you take the sum, maybe it's a trick？I modified this line of code like this: keypoint_map[map_y, map_x] = max(keypoint_map[map_y, map_x] , math.exp(-exponent)), and the experiment is still going on.
2)paf_map[0, y, x] = x_ba
paf_map[1, y, x] = y_ba
paf values takes the average values, but your code implements didn't take the average.

**Comment by Daniil-Osokin** [comment]
1. You can leave `max`, it shouldn't make a lot of difference.
2. Paf corresponds to single person, so average values between pafs of two persons makes them unsuitable for both, so just set one of pafs.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
