### ISSUE TITLE
the issues of add on the joint

### ISSUE THREAD

**Issue by CzJakethedog** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#56]
Dear Sir,

Currently I am doing research project for my degree. I have some problem with adding an extra point at the middle hip (pelvis), I have change the part connection by following the parameter from [https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/pose/poseParameters.cpp]
I am using 19 points. 
The issue now I am facing is about the val.py
when the code function `group_keypoints(all_keypoints_by_type, pafs, pose_entry_size=19, min_paf_score=0.05, demo=False)` operating, my 'kpts_b" always get the error 'IndexError: list index out of range'.

Hope you can tell me how to add on the point like how you add 'neck' by using COCO dataset.

Thank you so much.

**Comment by Daniil-Osokin** [comment]
I believe the main milestone here is to understand <del>(the paper)</del> what are `BODY_PARTS_KPT_IDS` and `BODY_PARTS_PAF_IDS`,  for this check #8 (you may also find some useful information in other issues). Basically you need to extend them properly (add proper values to the end), and make network to predict additional heatmap for pelvis and additional pafs (you may add two: left_hip->pelvis, right_hip->pelvis or so). The code in grouping will handle it automatically.

**Comment by CzJakethedog** [comment]
Thanks for the reply.
I wonder that for the BODY_PARTS_KPT_IDS and BODY_PARTS_PAF_IDS, do I need to extend it by following the order? because currently I referred the BODY_19N parameter from the CMU-Perceptual-Computing-Lab/poseParameters.cpp

**Comment by CzJakethedog** [comment]
Dear Sir,

Now i think my model could be trained after reading all the others posts.
However, I have some issues with the cocoeval.py problem, 
`File "/home/cz/.virtualenvs/pytorch/lib/python3.5/site-packages/pycocotools/cocoeval.py", line 223, in computeOks
    dx = xd - xg
ValueError: operands could not be broadcast together with shapes (18,) (17,) `

how did you troubleshoot this for 'neck' last time?

**Comment by CzJakethedog** [comment]
Dear Sir, 

I think now my problem is about the cocoapi to evaluate my model, the AP is 0.000 always. May I know how did you configure the API?

**Comment by Daniil-Osokin** [comment]
To extend this code with new pafs (and new keypoint, `BODY_PARTS_KPT_IDS` and `BODY_PARTS_PAF_IDS` need to be extended, as mentioned above. To evaluate through COCO API, you need to pass results in [COCO format](http://cocodataset.org/#format-data), it expects 17 keypoints. In validation script keypoints are [converted](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L136) from internal to COCO format.

**Comment by CzJakethedog** [comment]
Thanks for the reply. I have some questions again.
For the validation script, let say I have added on one extra point which is pelvis. 
In `to_coco_map = [0, -1, 6, 8, 10, 5, 7, 9, 12, 14, 16, 11, 13, 15, 2, 1, 4, 3]` here, I tried add one more point, maybe like the neck (-1), pelvis (-8), but the AP still being 0.000
I also skipped the part_id of "pelvis" like how you skipped for "neck", could you tell me which part you have edited also?

**Comment by Daniil-Osokin** [comment]
COCO evaluation expects 17 keypoints in each pose, so if you have added pelvis as 19th keypoint, you do not need to modify `to_coco_map`. `base_height` is the height of network input, image height will be rescaled to it before network inference. You may try to evaluate provided pre-trained model, it should not have zero AP.

**Comment by CzJakethedog** [comment]
if I do not edit the `to_coco_map`, the 'BODY_PARTS_KPT_IDS' and 'BODY_PARTS_PAF_IDS' will be out of the index. I have tried the whole day, probably it is the problem from dataset, maybe the MPII dataset is required.

**Comment by Daniil-Osokin** [comment]
What else can help? You see, COCO evaluation expects a file with detection results and gold labels (I believe you make evaluation on COCO dataset). So you may run evaluation for provided pre-trained model, then compare content of this output file with detections `detections.json` to output file file after your modifications and check the differences.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
