### ISSUE TITLE
how can we read the coordinates of  one keypoint

### ISSUE THREAD

**Issue by wangzheliu** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#57]
hey,Where are the 0-18 keypoints defined in the main.cpp or other files, and how can the coordinates of  one joint be read

**Comment by Daniil-Osokin** [comment]
Hi, [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L143) keypoints are saved in COCO [format](http://cocodataset.org/#format-results): `x_kpt_1, y_kpt_1, visibility_kpt_1, x_kpt_2,` and so on. You can get coordinates from it.

**Comment by wangzheliu** [comment]
thank you，but I want get coordinates in C++ program,I  use x_kpt_1 in c++ program，it is  undefined.

**Comment by wangzheliu** [comment]
> 
> 
> Hi, [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L143) keypoints are saved in COCO [format](http://cocodataset.org/#format-results): `x_kpt_1, y_kpt_1, visibility_kpt_1, x_kpt_2,` and so on. You can get coordinates from it.

thank you，but I want get coordinates in C++ program,I use x_kpt_1 in c++ program，it is undefined.

**Comment by wangzheliu** [comment]
if (FLAGS_r) {
                for (HumanPose const& pose : poses) {
                    std::stringstream rawPose;
                    rawPose << std::fixed << std::setprecision(0);
                    for (auto const& keypoint : pose.keypoints) {
                        rawPose <<""<< keypoint.x << "," << keypoint.y << ";";
                    }
                    //rawPose << pose.score;
					std::cout << rawPose.str() << std::endl;
					outfile << rawPose.str() << std::endl;

you use these code in c++ program.

**Comment by Daniil-Osokin** [comment]
In this case, you just need `keypoint.x` and `keypoint.y`.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
