### ISSUE TITLE
using the onnx model with opencv

### ISSUE THREAD

**Issue by berak** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#58]
hi  ;)
i'm trying to use the [lightweight-human-pose model](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py#L783-L787) [on colab](https://colab.research.google.com/drive/186N1ZF5UrCCD2lKMWjQYAAK35DV9Geje#scrollTo=vxUNWtml8hNW):

```
!wget 'https://drive.google.com/uc?export=dowload&id=1T2Kq01WXzPMrQdnEOUEiVBhwouW8Pka5' -O pose.onnx

net = cv2.dnn.readNet("pose.onnx")
# load 256x256 image and sent through net
net.dumpToFile("pose_dot.txt")
!dot pose_dot.txt -Tpng -opose_dot.png
```
and the last layer :
![Clipboard01](https://user-images.githubusercontent.com/854416/70997603-c4cb4480-20d5-11ea-9a8a-7b987387fe3c.jpg)

that looks weird. 38 heatmaps ? shouldn't it have 19 heat and 2x19 paf maps (=57) ?
or, if it's meant to be used for single persons , 19 heatmaps only ?

i look at the model: 
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/55093417d383c25a0f2454eba352198c944290d1/models/with_mobilenet.py#L90

and it should have returned [heatmaps, pafs] here:
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/55093417d383c25a0f2454eba352198c944290d1/models/with_mobilenet.py#L86

but it looks to me, like we only have the pafs returned from the forward pass in opencv

the [newly added opencv Keypoints model](https://github.com/opencv/opencv/pull/15189/files#diff-6de938636906f03a3c475c556f5c8878R166) tries to loop over all of them, and results look quite bad ;(

**Comment by berak** [comment]
wrong repo, apologies for the noise.

(i'll reopen at opencv if nessecary)

**Comment by berak** [comment]
i made another test, converting the pretrained checkpoint_iter_370000.pth to onnx, using your script,
and the output layers there look as expected:

![Clipboard02](https://user-images.githubusercontent.com/854416/71083950-7335bf00-2194-11ea-86c1-5967f690a58e.jpg)

again, i think, the [model in opencv_extra](https://github.com/opencv/opencv_extra/blob/4fdb88f83fe39f969e9945f531045a5a0f51b827/testdata/dnn/download_models.py#L783-L787)  is broken

**Comment by Daniil-Osokin** [comment]
Hi! Nice to see you here, thanks for pointing this out! As I see, that code doesn't support multi-person pose estimation, so it is probably ok that model has one output. However, they left not the right one =). Will you create a PR/issue to OpenCV?

**Comment by berak** [comment]
hey, for sure i will raise an issue on opencv,  but i don't have a solution to the actual problem.

the [opencv_extra model](https://drive.google.com/uc?export=dowload&uid=1T2Kq01WXzPMrQdnEOUEiVBhwouW8Pka5) is broken, but i have no idea, how it came into life. ;(
do you have any helpful clues ?

**Comment by Daniil-Osokin** [comment]
I believe the commit author should check, then reconvert the model with right output (heatmaps, not pafs) and upload proper model. If you want, you can do it by yourself, just remove last `pafs` output in [the model](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/models/with_mobilenet.py#L123): `return stages_output[:-1]` and remove last [output name](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/convert_to_onnx.py#L13) from conversion script correspondingly.

**Comment by berak** [comment]
the current model luckily has heatmaps and pafs in seperate outputs, so it can be used as is.

issue moved on to opencv, so i'll close this one.
