### ISSUE TITLE
caffe c++ demo speed is too slow

### ISSUE THREAD

**Issue by lxy5513** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#59]
Hi, First of all, thank your great project.  
I convert the pytorch model to caffe, then realized it in c++ code, the accuracy is pretty good But I met the speed problem.

```
    Caffe::set_mode(Caffe::GPU);
    ...
    double t1 = static_cast<double>(cv::getTickCount());
    net_->Forward();
    double t2 = static_cast<double>(cv::getTickCount());
    double inferenceTime = (t2 - t1) / cv::getTickFrequency() * 1000;
    std::cout << "model infrence time is: " << inferenceTime << std::endl;
   ...
```

In my GPU card (1080ti), It needs about 30 ms for each inference, Could you please tell the reason or potential fix method ? thanks a lot.

**Comment by Daniil-Osokin** [comment]
Hi, did you test inference speed in PyTorch? There can be different reasons:
* What is the network input resolution?
* How was model converted to caffe, does it have depthwise separable convolutions?
* Does caffe has depthwise separable convolution layer?
* Was caffe built with (recent) cudnn?

**Comment by lxy5513** [comment]
Thanks for your kindly respose.    

I have  test in Pytorch python demo, the inference time is 18 ms (input shape is  torch.Size([1, 3, 256, 456])


For caffe model 
for 1 .   
 the resolution is 256 * 344  

for 2 and 3:
I convert pytorch to caffe by the project https://github.com/xxradon/PytorchToCaffe 
I can't figure out whether It have depthwise seperable convolution, The caffe model prototxt is here: 
[tinypose.prototxt.txt](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/files/3981523/tinypose.prototxt.txt)

for 4 .   
I build caffe with cudnn 10.0 
[xyliu caffe]$ ldd build/tools/caffe | grep cudnn
	libcudnn.so.7 => /opt/cudnn-10.0-linux-x64-v7.6.5.32/lib64/libcudnn.so.7 (0x00007f8f6a57a000)

**Comment by lxy5513** [comment]
I change resolution to 256*192 but the speed is still slow, about 33 FPS

**Comment by Daniil-Osokin** [comment]
I believe you can have the same inference speed in caffe as with PyTorch if will use [depthwise separable convolution](https://github.com/yonghenglh6/DepthwiseConvolution). However, it should run about 6-4 ms per single 256x456 image. Looks like something happened.

**Comment by lxy5513** [comment]
Thank you a lot, I will respose the result later after dig into depthwise separable convolutions in caffe.

**Comment by Daniil-Osokin** [comment]
You just need to replace convolutions with group size == input channels with depthwise convolution layer in your `.prototxt`  (example is [here](https://github.com/yonghenglh6/DepthwiseConvolution/blob/master/example/depthwised_mobilenet_deploy.prototxt#L66)). Feel free to reopen when done.

**Comment by lxy5513** [comment]
So kind of you! At last I realize the caffe model with depthconv, The speed of inference is about 10ms.

**Comment by Daniil-Osokin** [comment]
Great, that it works!
