### ISSUE TITLE
How to smooth pose data/ keypoints?

### ISSUE THREAD

**Issue by musab1234** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#60]
There is a lot of jitters in keypoints detections, is there any filter to smooth keypoints?

**Comment by Daniil-Osokin** [comment]
Hi!
Can you provide the video with jitter?

**Comment by Daniil-Osokin** [comment]
New year - new features, check it out #61! :christmas_tree: :snowman_with_snow: :space_invader: I've set [default parameters](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/one_euro_filter.py#L24), you can adjust them for your needs (e.g. decrease beta for stronger smoothing).

**Comment by musab1234** [comment]
This is awesome , great work @Daniil-Osokin . Thanks.
