### ISSUE TITLE
Testing: Video and Image Testing on Pre-trained Weights

### ISSUE THREAD

**Issue by NaeemKhan333** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#63]
Thank you very much for your work, but I have some problems while I am using pre-trained weights that you have given in your repo. I have downloaded the "mobilenet_sgd_68.848.pth.tar" weights and run the following command
"python demo.py --checkpoint-path=mobilenet_sgd_68.848.pth.tar --video=222.mp4 "
It is not working for the person ....it is giving 0 key points . I dont why it is happening ,No Error is occurring....can u elaborate what is the reason for this. Will I need to convert the weights or any thing other to change.

**Comment by Daniil-Osokin** [comment]
Hi! This is not a pre-trained model for pose estimation, it used to initialize network and start training (to reproduce results or make own experiments). To run the demo please use [this](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#pre-trained-model) one.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
