### ISSUE TITLE
CPU test on Mac15'  Dual-Core Intel Core i5 speed is way slower than expectation

### ISSUE THREAD

**Issue by mikecheninoulu** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#66]
Hi, I implement the CPU version of the code, using the provided model.

`python demo.py --checkpoint-path data/checkpoint_iter_370000.pth --video 0 --cpu`

But it cannot achieve the expected speed (26 fps on CPU), my speed is around 3 seconds per frame...

Any solutions?

**Comment by Daniil-Osokin** [comment]
Do you use OpenVINO as inference engine? It also has dedicated [c++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
