### ISSUE TITLE
Efficiency

### ISSUE THREAD

**Issue by hundanLi** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#67]
It seems that the efficiency is not so good. I ran the demo on cpu, just got around 0.3 FPS.

**Comment by Daniil-Osokin** [comment]
Hi, python demo is just for the quick results preview. Please, consider [c++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo) for the best performance.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by hundanLi** [comment]
Thank you for your reply.
