### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xe2'.

### ISSUE THREAD

**Issue by LexTran** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#68]
Hi there! I've been trying to run your demo code in python, however I've met the problem as follow:
Traceback (most recent call last):
  File "demo.py", line 157, in <module>
    checkpoint = torch.load(args.checkpoint_path, map_location='cpu')
  File "C:\Users\PC\.conda\envs\pytorch\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\PC\.conda\envs\pytorch\lib\site-packages\torch\serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xe2'.
I don't understand what's going on. I thought it might because my OS is windows, but when I use a Ubuntu virtual maching to run it, it shows the same eroor, hope you can help me, thanks a lot

**Comment by Daniil-Osokin** [comment]
Hi! Did your checkpoint downloaded properly, so it's ~83.9 MB (to download just make a right mouse click on the [link](https://download.01.org/opencv/openvino_training_extensions/models/human_pose_estimation/checkpoint_iter_370000.pth) and select "Save link as")?

**Comment by LexTran** [comment]
Thanks for your help, I will give it a try. I will let you know if it works.

**Comment by LexTran** [comment]
Thanks for your help, I will give it a try. I will let you know if it works.

**Comment by LexTran** [comment]
It worked! Thanks to you!!

**Comment by Daniil-Osokin** [comment]
Glad it helped!
