### ISSUE TITLE
iOS CoreML-model convert report

### ISSUE THREAD

**Issue by mbotsu** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#69]
Hi.

Lightweight-OpenPose (checkpoint_iter_370000.pth) could be converted to a CoreML-model.
I did well thanks to your research results.

This is a report.

[Can Lightweight-OpenPose Pytorch-Model be used with SwiftOpenPose?](https://gist.github.com/mbotsu/8c712093884cb64f9477881cb182dbc2)

**Comment by Daniil-Osokin** [comment]
Thanks, really great to see it!
