### ISSUE TITLE
how to download the pre-trained model?

### ISSUE THREAD

**Issue by izhxxx** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#72]
I open the Website, "https://download.01.org/opencv/openvino_training_extensions/models/human_pose_estimation/checkpoint_iter_370000.pth", but I found it's error codes and cannot download. Do you have any other way to download it?

**Comment by Daniil-Osokin** [comment]
Hi, to download just make a right mouse click on the [link](https://download.01.org/opencv/openvino_training_extensions/models/human_pose_estimation/checkpoint_iter_370000.pth) and select "Save link as"

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
