### ISSUE TITLE
where is 2d-keypoints output json file after run human-pose-estimation-demo?

### ISSUE THREAD

**Issue by huangjie-gren** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#74]
hello,
Very appreciate for your work of optimization of openpose.And I am new to openVINO ,I want to know if there will be a 2d-keypoints json file output after I run human-pose-estimation-demo ?And I only see the raw value by using '-r' option in command line ,without any explanation of what these data means.Could you give some informations?Raw data is as follows: 

165,173 173,236 156,248 -1,-1 -1,-1 190,232 194,186 210,98 173,365 94,378 98,490 219,361 298,423 398,490 173,165 177,169 -1,-1 198,190 300

**Comment by Daniil-Osokin** [comment]
Hi! With `-r` flag demo [prints](https://github.com/opencv/open_model_zoo/blob/master/demos/human_pose_estimation_demo/main.cpp#L181) each pose keypoints coordinates: `x,y`, spaces separate keypoints from each other. New pose starts from new line. Keypoints have [this](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-coco) order, not found keypoint has `-1,-1` coordinates. Last value in line is pose score (confidence). So you can parse this output or customize code to output it in `json`.

**Comment by huangjie-gren** [comment]
OK,I get it. Thank you very much for your prompt reply!

**Comment by Daniil-Osokin** [comment]
Ok, closing.
