### ISSUE TITLE
dyld: Library not loaded: @rpath/libtbb.dylib

### ISSUE THREAD

**Issue by yxt132** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#75]
I am trying to run the demo using Openvino. Here is the command:

<path>/human_pose_estimation_demo -m human-pose-estimation.xml -i "cam"

I am getting error messages as below:

dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /opt/intel/openvino_2020.2.117/deployment_tools/inference_engine/lib/intel64/libinference_engine_legacy.dylib
  Reason: image not found
Abort trap: 6

Any idea how to fix it? By the way, I am running it inside Anaconda on my Macbook. The Python demo worked fine but it was too slow.

Thanks

**Comment by Daniil-Osokin** [comment]
Hi, did you set [environmental variables](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_macos.html)? If this does not help, try to add folder with this library to `DYLD_LIBRARY_PATH`:
```
export DYLD_LIBRARY_PATH=<path_to_folder_with_libinference_engine_legacy.dylib>:$DYLD_LIBRARY_PATH
```

**Comment by yxt132** [comment]
Thank you for your quick response. I added the folder as you instructed and got another error:

yld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /opt/intel/openvino_2020.2.117/deployment_tools/inference_engine/lib/intel64/libinference_engine_legacy.dylib
  Reason: no suitable image found.  Did find:
	/opt/intel/openvino_2020.2.117/deployment_tools/inference_engine/lib/intel64/libinference_engine_legacy.dylib/libtbb.dylib: stat() failed with errno=20
Abort trap: 6

Then I try to set the environmental variables using setupvars.sh. The following error messages popped up:

InferenceEngine: 0x103dd3d88
Parsing input parameters
2020-04-22 09:29:39.984 human_pose_estimation_demo[7454:316230] +[AVCaptureDevice authorizationStatusForMediaType:]: unrecognized selector sent to class 0x7fff9ccc66a0
[ERROR:0] global /localdisk/jenkins/workspace/OpenCV/OpenVINO/2020.2/build/osx/opencv/modules/videoio/src/cap.cpp (265) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!

[ ERROR ] Cannot open input file or camera: cam


I verified that the camera is working by using openCV.

**Comment by yxt132** [comment]
I gave up on mac. I guess the problem might be that some libraries are missing. I switched to windows and made it work. Thanks, I will close this issue.

**Comment by Daniil-Osokin** [comment]
Did you link with OpenCV from OpenVINO during testing camera? OpenVINO provides own optimized build of OpenCV, this may be the issue of different behavior.
