### ISSUE TITLE
Usage of keypoint visibility in the generation of keypoint_maps and paf_maps

### ISSUE THREAD

**Issue by yushuinanrong** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#76]
Hi @Daniil-Osokin,

Again, thanks for sharing this great work!
I was checking your training code and wasn't sure about the following lines:
https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/411ff9fd5f6125e1879cb73f6b4f90090184edad/datasets/coco.py#L71-L87

Is keypoint[2] stands for the visibility of a joint? If so, then in coco:
if visibility == 0 that keypoint not in the image.
if visibility == 1 that keypoint is in the image BUT not visible namely maybe behind of an object.
if visibility == 2 that keypoint looks clearly. not hidden.

Why you choose to add gaussian for those unavailable and occluded joints while ignore the visible ones?

**Comment by Daniil-Osokin** [comment]
Hi, code uses [converted](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/scripts/prepare_train_labels.py#L49-L54) annotations, so initial COCO keypoint visibility value changed to internal one. Actually there is no need to convert visibility in this way, it is just a legacy.

**Comment by yushuinanrong** [comment]
@Daniil-Osokin 
Got it, thank you.

**Comment by guker** [comment]
got it
