### ISSUE TITLE
dataloder stuck

### ISSUE THREAD

**Issue by lyupei** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#77]
hi, I'm using torch1.4 and sometimes the dataloader stuck when fetching the last batch, and I notice that you have added the cv2.setNumThreads(0) code to prevent freeze of dataloader.

Do you have any idea what may cause this?

**Comment by Daniil-Osokin** [comment]
Hi, this is the issue with [long history](https://github.com/pytorch/pytorch/issues/1355). You may try something from recent suggestions or try older PyTorch versions. I have encountered no freezes with 1.3, however the issue may be in particular configuration of system.

**Comment by lyupei** [comment]
tks for your reply!
I'll check older torch version and some other settings.
I'll comment here if some works.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
