### ISSUE TITLE
dataset resize inequality

### ISSUE THREAD

**Issue by www516717402** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#78]
Thank your for great project. In coco data **coco.py** file 
1. Assume input image shape (640, 460, 3)
2. mask shape result : (80, 58)
[code in project](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/411ff9fd5f6125e1879cb73f6b4f90090184edad/datasets/coco.py#L48)
3. keypoint_maps shape result: (80, 57)
[code in project](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/411ff9fd5f6125e1879cb73f6b4f90090184edad/datasets/coco.py#L74)
4. modify
`keypoint_maps = np.zeros(shape=(n_keypoints + 1,
                                        int((n_rows / self._stride+0.5)), int((n_cols / self._stride+0.5))), dtype=np.float32)`

**Comment by www516717402** [comment]
I know, points process in data augment.

**Comment by Daniil-Osokin** [comment]
Hi! You are right, for the inference image size must be divisible by 8. That is why we have use [padding](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/val.py#L91).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
