### ISSUE TITLE
total_keypoints_num is not uses

### ISSUE THREAD

**Issue by sunbin1357** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#81]
you obtain total_keypoints_num, but you do not use it.

**Comment by Daniil-Osokin** [comment]
Hi, actually it is used to maintain global keypoints index [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/keypoints.py#L44).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
