### ISSUE TITLE
mean_values parameter error in macOS

### ISSUE THREAD

**Issue by ali-gulzar** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#83]
When trying to convert onxx file to binary file for C++ demo, I get the following error:

```
zsh: no matches found: data[128.0,128.0,128.0]
```

This is the parameter value of --mean_values. Is this a probllem in macOS?

**Comment by Daniil-Osokin** [comment]
Hi, looks like you need to escape this block with quotes (`"data[128.0,128.0,128.0]"`), as suggested [here](https://github.com/ohmyzsh/ohmyzsh/issues/31).

**Comment by ali-gulzar** [comment]
Thank you, it worked.
