### ISSUE TITLE
Match IDs keypoints and Bounding box 

### ISSUE THREAD

**Issue by rykymai** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#88]
I have a question. I'm labelling a human pose enstimation dataset.
I have to add the keypoints and boundingbox containing the person. Is there a difference in putting in first place the keypoints or adding the BB first? ( I'm wondering that because if a apply Keypoints first and then the BB, COCO annotator shows me two IDs on the right panel, if I apply first the BB and then the keypoints it allows me to associate BB e keypoints with a unique ID).
<img width="1508" alt="85221781-04d9ef80-b3b7-11ea-8655-6d94894bf17b" src="https://user-images.githubusercontent.com/28538355/85271061-8cd4fd80-b47a-11ea-8046-143036f9d9f5.png">

**Comment by Daniil-Osokin** [comment]
Hi! The second option looks right. You should end up with the following structure for each person:
![Screenshot from 2020-06-23 00-11-04](https://user-images.githubusercontent.com/2491976/85335832-52a14580-b4e6-11ea-8357-cc3e538abbb4.png)
You can label some small number of images (e.g. 4), take the annotation and check if it has corresponds to the [COCO data format](http://cocodataset.org/#format-data).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
