### ISSUE TITLE
Hand keypoint tracking demo missing

### ISSUE THREAD

**Issue by leavittx** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#89]
Hi,
Shouldn't there be a demo for that indeed?
Looks a bit incomplete compared to original openpose without it to me

**Comment by Daniil-Osokin** [comment]
Hi! No, it should not. However it is quite easy to extend this code with hands support. If this is a popular feature, I will possibly add it.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
