### ISSUE TITLE
Humanpose Demo - Shapes issue in Python

### ISSUE THREAD

**Issue by dgraeber** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#9]
Nice work on this repo!  I am able to convert the pretrained model to onnx and then to IR format with no issue (using your README).  The model works with running the demo (C++ and shell script ./human-pose) but I am trying to also run it with the Python plugin.  Using your code to reshape the input image and then calling the python plugin, I get the following: 
ValueError: could not broadcast input array from shape (1,3,256,384) into shape (1,3,256,456) .

Have you run the model from python on OpenVino?  Just curious (hoping to save myself some time)....

**Comment by Daniil-Osokin** [comment]
Actually no, but this output looks like that the shape of input image differs from pre-defined (during conversion to onnx) shape of network input layer. In this case network input layer (as well as the rest network) needs to be reshaped, please check this [sample](https://github.com/opencv/dldt/blob/2018/inference-engine/ie_bridges/python/sample/benchmark_app/benchmark.py#L86). It shows how to reshape network for different batch size, but can be adapted for different weight and height.

**Comment by dgraeber** [comment]
Thanks!  I was able to reshape the network prior to inference call and things flowed.  I will look at how to change the shape before conversion to onnx (just to be thorough)

**Comment by Daniil-Osokin** [comment]
Nice :+1: , thanks for the interest to the work!
