### ISSUE TITLE
CPU usage got 100% on GPU inference mode

### ISSUE THREAD

**Issue by Lukikay** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#91]
Hi, thanks for providing this lightweight OpenPose implement. 

The project runs well for me, but I noticed the CPU usage got 100% on the GPU inference mode with webcam. I tested on RTX 2080Ti GPU and i7 9700, but it was around 15 fps, and CUDA usage was only 10%. I tested this on the python version.

I'm confusing about it, why it takes lower CUDA usage but gets lower fps. I tried to disable the tracking and smoothing modules, but the CPU usage still spent 100%.

In addition, the 3D pose embed version (lightweight-human-pose-estimation-3d-demo.pytorch) also got 100% CPU usage but can exactly obtain 30 fps, which is the upper limit frames rate of my webcam's feed. By the way, I measured the FPS by the python's datetime module instead of OpenCV.

Thanks in advance.

**Comment by Daniil-Osokin** [comment]
Hi! There is results post-processing part in the code, which is implemented in python and not very fast. For better CPU utilization run [C++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo). 3D pose estimation code offloads post-processing to C++ (if you successfully run `setup.py install`), so this may be the issue with different fps.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
