### ISSUE TITLE
unable to extract pretrained model

### ISSUE THREAD

**Issue by athulvingt** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#93]

**Comment by Daniil-Osokin** [comment]
Hi! You do not need to extract any model, just use it as is.

**Comment by wuyenlin** [comment]
I am also running into similar issue. I downloaded the pre-trained model from Google Drive and ran Step 3 of Training but it returns a sequence of WARNING saying no pre-trained parameters found.

**Comment by athulvingt** [comment]
Do you meant to train a model on pre-trained MobileNet v1 weights or do inference on a pre-trained model?

**Comment by Daniil-Osokin** [comment]
It is ok. We use pre-trained on ImageNet weights of MobileNet v1 classification network to initialize pose estimation model, so weights related to pose estimation part of the network are missed in it (and that is because it warnings, not errors), see #70.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
