### ISSUE TITLE
How to batch images to get all the key coordinates?

### ISSUE THREAD

**Issue by sunriselqq** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#94]
Hello, I've been using Openpose to get the coordinates of the nodes to set up a data set. How to batch process photos?

**Comment by Daniil-Osokin** [comment]
Hi! For the inference images need to be [normalized](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/07f795b15eeef542850f5a7d30ad236a6cb0bf76/val.py#L82) and [padded](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/07f795b15eeef542850f5a7d30ad236a6cb0bf76/val.py#L91), so if images have the same size, you can make batch inference, then follows regular post-processing for each image [outputs](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/07f795b15eeef542850f5a7d30ad236a6cb0bf76/val.py#L96-L108).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
