### ISSUE TITLE
Single Person detection

### ISSUE THREAD

**Issue by vishruthys** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#96]
Hi, 
Is there any way I can only estimate poses for only one person with multiple people in the frame?
I am testing with demo.py

I went through all the closed issues but couldn't find any which related to my question. 

Thank you for your work.

**Comment by Daniil-Osokin** [comment]
Hi! You can use at most one person from all detected, just modify [L105](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L105) to `for n in range(min(1, len(pose_entries))):`. However it will be just some person from all found. You may probably want the biggest visible person to display, for that case just sort [current_poses](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L119) by `bbox` area and display the biggest.

**Comment by vishruthys** [comment]
Thank You very much, I got what I wanted.

**Comment by sana15** [comment]
How did you map persons in an image from Ground truth and prediction if they are many number of persons in an image
