### ISSUE TITLE
c++ code for model post-processing

### ISSUE THREAD

**Issue by sunbin1357** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#97]
Can you provide c++ code for model post-processing？

**Comment by Daniil-Osokin** [comment]
Hi! You can find it in [c++ demo](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch#cpp-demo) or check it in [OpenVINO's github](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/human_pose_estimation_demo/src/human_pose_estimator.cpp#L194).

**Comment by sunbin1357** [comment]
Does this c++ code run the TensorRT model？

Daniil-Osokin <notifications@github.com> 于2020年7月25日周六 上午3:12写道：

**Comment by Daniil-Osokin** [comment]
It runs model in [OpenVINO](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit.html) format.

**Comment by sunbin1357** [comment]
Do I need to change a lot if I want to run the TensorRT model？

Daniil-Osokin <notifications@github.com> 于2020年7月26日周日 下午7:56写道：

**Comment by Daniil-Osokin** [comment]
You need to rewrite [network inference with OpenVINO](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/human_pose_estimation_demo/include/human_pose_estimator.hpp#L62) and link over TensorRT.

**Comment by sunbin1357** [comment]
If I run the pytorch model(.pth),  Do I only need to rewrite
InferenceEngine::ExecutableNetwork
executableNetwork? Since I am not very proficient in c++, I would like to
change it if there is not much code to be modified.

Daniil-Osokin <notifications@github.com> 于2020年7月27日周一 上午3:17写道：

**Comment by Daniil-Osokin** [comment]
I believe it will take a time anyway.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
