### ISSUE TITLE
Questions about data processing

### ISSUE THREAD

**Issue by sunbin1357** [Daniil-Osokin/lightweight-human-pose-estimation.pytorch#98]
Your data processing code is as follows：
```
    height, width, _ = img.shape
    scale = net_input_height_size / height

    scaled_img = cv2.resize(img, (0, 0), fx=scale, fy=scale, interpolation=cv2.INTER_CUBIC)
    scaled_img = normalize(scaled_img, img_mean, img_scale)
    min_dims = [net_input_height_size, max(scaled_img.shape[1], net_input_height_size)]
    padded_img, pad = pad_width(scaled_img, stride, pad_value, min_dims)

    tensor_img = torch.from_numpy(padded_img).permute(2, 0, 1).unsqueeze(0).float()
```
I modify the code, and the model cannot work. what is the difference of your provided codes and the following code:

```
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
img = cv2.resize(img, (224, 224))
tensor_img = transform(img)[None, ...]
```

**Comment by Daniil-Osokin** [comment]
Hi! You can compare output for both pieces of code on the same resolution and check the difference. I believe the main reason is in resize, image should be downsampled with the same aspect ratio as original image. Without that objects will be skewed, and network does not expect it. So proper code for resize will be:
```
scale = 224 / img.shape[0]
img = cv2.resize(img, dsize=None, fx=scale, fy=scale)
```
Actually this is exactly what is written in the original code above. I suggest to use it.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
